### ISSUE TITLE
SSL error: could not verify peer

### ISSUE THREAD

**Issue by dz0ny** [travis-ci/travis.rb#141]
```
➤ travis report                                                     ~/project 1
System
Ruby:                     Ruby 1.9.3-p194
Operating System:         Ubuntu 13.10
RubyGems:                 RubyGems 1.8.23

CLI
Version:                  1.6.3
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2013-11-27 16:22:08 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis setup`:
    Travis::Client::Error: SSL error: could not verify peer
        from /var/lib/gems/1.9.1/gems/travis-1.6.3/lib/travis/client/session.rb:190:in `raw'
        from /var/lib/gems/1.9.1/gems/travis-1.6.3/lib/travis/client/session.rb:164:in `get_raw'
        from /var/lib/gems/1.9.1/gems/travis-1.6.3/lib/travis/client/session.rb:130:in `config'
        from /var/lib/gems/1.9.1/gems/travis-1.6.3/lib/travis/cli/api_command.rb:122:in `load_gh'
        from /var/lib/gems/1.9.1/gems/travis-1.6.3/lib/travis/cli/repo_command.rb:76:in `detect_api_endpoint'
        from /var/lib/gems/1.9.1/gems/travis-1.6.3/lib/travis/cli/repo_command.rb:19:in `setup'
        from /var/lib/gems/1.9.1/gems/travis-1.6.3/lib/travis/cli/command.rb:166:in `execute'
        from /var/lib/gems/1.9.1/gems/travis-1.6.3/lib/travis/cli.rb:58:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.6.3/bin/travis:19:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

Same goes for travis login

**Comment by tabolario** [comment]
Getting this with a fresh install of the gem on Ubuntu 14.04/Ruby 2.2

`travis report`:

```
System
Ruby:                     Ruby 2.2.0-p0
Operating System:         Ubuntu 14.04
RubyGems:                 RubyGems 2.4.5

CLI
Version:                  1.7.5
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-02-21 14:01:47 -0500

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "tabolario"
Verify SSL:               no
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, insecure, current)
```

**Comment by rkh** [comment]
@tabolario are you saying yo see this error even though you've set the connection to insecure?

**Comment by tabolario** [comment]
@rkh Sorry forgot to mention that. Yes, I'm getting this error even when `--insecure` is passed to any command.

**Comment by MitchK** [comment]
Same issue with me. I was logged in with Travis Enterprise and wanted to switch back to travis-ci.org.

```gem install travis --pre``` did not help.

```
$ travis login -IE
/Library/Ruby/Gems/2.0.0/gems/travis-1.7.7.travis.678.5/lib/travis/client/session.rb:213:in `raw': SSL error: could not verify peer (Travis::Client::SSLError)
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7.travis.678.5/lib/travis/client/session.rb:184:in `get_raw'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7.travis.678.5/lib/travis/client/session.rb:132:in `config'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7.travis.678.5/lib/travis/cli/api_command.rb:122:in `load_gh'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7.travis.678.5/lib/travis/cli/login.rb:45:in `github'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7.travis.678.5/lib/travis/cli/login.rb:31:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7.travis.678.5/lib/travis/cli/login.rb:40:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7.travis.678.5/lib/travis/cli/command.rb:198:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7.travis.678.5/lib/travis/cli.rb:64:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7.travis.678.5/bin/travis:18:in `<top (required)>'
	from /usr/bin/travis:23:in `load'
	from /usr/bin/travis:23:in `<main>'
````
I have internet access without a proxy or firewall.

**Comment by PierreFritsch** [comment]
To others getting MitchK's stack trace with GitHub/Travis enterprise on Yosemite 10.10.3 with insecure connection: It doesn't help trying to get back in time to travis `pre` version from Sept. 12, 2014, nor does it help to update to current version travis 1.8.0 (with or without `pre`).

**Comment by nayena** [comment]
I am having the same issues with OS X Yosemite 10.10.4 as well.

**Comment by jirutka** [comment]
I have the same issues on OS X 10.9.5 (Mavericks). I’ve already tried to recompile Ruby, but nothing helps. It works with `--insecure`, but `encrypt-file` ignores this option.

```
$ travis report
System
Ruby:                     Ruby 2.2.2-p95
Operating System:         Mac OS X 10.9.5
RubyGems:                 RubyGems 2.4.5

CLI
Version:                  1.8.0
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-08-01 00:30:42 +0200

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                SSL error: could not verify peer
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)
```

**Comment by jirutka** [comment]
Sorry, this was problem on my side. I’ve had outdated root certificates in openssl installed via Homebrew. The simplest solution was to reinstall openssl, to let it bootstrap root certificates from Keychain.

**Comment by jirutka** [comment]
What the hell… `travis report`, `travis whoami` and other commands now works without `--insecure`, but `encrypt-file` still doesn’t work.

**Comment by dominic-miglar** [comment]
I have the same error on Ubuntu 12.04. @rkh Do you know how to fix that already?
- CA Certificates are up2date
- Ruby 1.9.1
- I have tried multiple versions of travis.rb (1.7.7, 1.8.0, also with --pre prefix when installing with gem)
- On another machine (with archlinux) it works perfectly......


Command:

```
dmiglar@octopus:~$ travis login --debug --explode
** Loading "/home/myuser/.travis/config.yml"
** Timeout::Error: execution expired
** Loading gh
** GET "config"
**   took 0.11 seconds
/var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/client/session.rb:213:in `raw': SSL error: could not verify peer (Travis::Client::SSLError)
	from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/client/session.rb:184:in `get_raw'
	from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/client/session.rb:132:in `config'
	from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/api_command.rb:122:in `load_gh'
	from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/login.rb:45:in `github'
	from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/login.rb:31:in `login'
	from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/login.rb:40:in `run'
	from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli/command.rb:198:in `execute'
	from /var/lib/gems/1.9.1/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
	from /var/lib/gems/1.9.1/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:19:in `load'
	from /usr/local/bin/travis:19:in `<main>'
```

**Comment by rkh** [comment]
No, I don't know why this is happening. On SSL errors it should now switch automatically between bundled CAs and system CAs, depending on which one works, and always use system CAs for other hosts.

**Comment by mcqueary** [comment]
I'm having this issue in OS X El Capitan (10.11.3).

```
System
Ruby:                     Ruby 2.3.0-p0
Operating System:         Mac OS X 10.11.3
RubyGems:                 RubyGems 2.5.2

CLI
Version:                  1.8.2
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2016-02-10 11:01:56 -0700

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
[mcqueary-mb:~/Dropbox/git/jnats] larry% travis login --debug --explode
** Loading "/Users/larry/.travis/config.yml"
** Loading gh
** GET "config"
**   took 0.0013 seconds
/usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/session.rb:216:in `raw': SSL error: could not verify peer (Travis::Client::SSLError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/session.rb:186:in `get_raw'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/session.rb:134:in `config'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/api_command.rb:126:in `load_gh'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/login.rb:45:in `github'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/login.rb:31:in `login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/login.rb:40:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:22:in `load'
	from /usr/local/bin/travis:22:in `<main>'
```

**Comment by dzen** [comment]
I managed to make `travis encrypt` work by changing the ruby library used to connect to the API:

```
travis encrypt "user:t0K3n" --add notifications.slack --adapter net-http
```

**Comment by adizam** [comment]
Still getting the issue :)

**Comment by cholcombe973** [comment]
I just hit this also

**Comment by leusonmario** [comment]
I have the same problem. I'm using the API to get some information of some projects. Sometimes it works fine but there are moments that does not.

`/var/lib/gems/2.1.0/gems/travis-1.8.3.travis.745.4/lib/travis/client/session.rb:216:in raw: SSL error: could not verify peer (Travis::Client::SSLError)
	from /var/lib/gems/2.1.0/gems/travis-1.8.3.travis.745.4/lib/travis/client/session.rb:186:in get_raw
	from /var/lib/gems/2.1.0/gems/travis-1.8.3.travis.745.4/lib/travis/client/session.rb:166:in get
	from /var/lib/gems/2.1.0/gems/travis-1.8.3.travis.745.4/lib/travis/client/session.rb:323:in fetch_many
	from /var/lib/gems/2.1.0/gems/travis-1.8.3.travis.745.4/lib/travis/client/session.rb:102:in block in find_many
	from /var/lib/gems/2.1.0/gems/travis-1.8.3.travis.745.4/lib/travis/client/session.rb:329:in cached
	from /var/lib/gems/2.1.0/gems/travis-1.8.3.travis.745.4/lib/travis/client/session.rb:102:in find_many
	from /var/lib/gems/2.1.0/gems/travis-1.8.3.travis.745.4/lib/travis/client/repository.rb:92:in builds
	from /var/lib/gems/2.1.0/gems/travis-1.8.3.travis.745.4/lib/travis/client/repository.rb:127:in each_build`

**Comment by doutriaux1** [comment]
same issue here

**Comment by dnadeau4** [comment]
Works using `--adapter net-http` option.
``travis encrypt "FOO=6\\&a\\(5\\!1Ab\\\\" --adapter net-http``

**Comment by shawnzhu** [comment]
* I can not reproduce this error when using default endpoint (`https://api.travis-ci.org`) and faraday adapter `typhoeus`.
* I can reproduce this against Travis CI enterprise with faraday adapter `typhoeus`:

## What happened
all travis commands against my travis ci enterprise failed with error message `SSL error: could not verify peer` when using option `--no-insecure`.

```shell
$ bin/travis report -X --no-insecure --debug --debug-http --adapter typhoeus
** Loading "/Users/shawnzhu/.travis/config.yml"
System
Ruby:                     Ruby 2.4.0-p0
Operating System:         Mac OS X 10.12.4
RubyGems:                 RubyGems 2.6.8

CLI
Version:                  1.8.8
Plugins:                  "travis-build"
Auto-Completion:          yes
Last Version Check:       2017-03-09 16:43:12 -0500

Session
API Endpoint:             https://<travis-ci-enterprise>/api
** GET "users/"
I, [2017-03-09T16:43:18.661925 #57760]  INFO -- : get https://<travis-ci-enterprise>/api/users/
D, [2017-03-09T16:43:18.661989 #57760] DEBUG -- request: User-Agent: "Travis/1.8.8 (Mac OS X 10.12.4 like Darwin; Ruby 2.4.0-p0; RubyGems 2.6.8; command report) Faraday/0.11.0 Typhoeus/0.8.0"
Accept: "application/vnd.travis-ci.2+json"
Authorization: "token <this-is-not-a-valid-token>"
I, [2017-03-09T16:43:18.750319 #57760]  INFO -- Status: 0
D, [2017-03-09T16:43:18.750538 #57760] DEBUG -- response: 
**   took 0.089 seconds
Logged In:                SSL error: could not verify peer
Verify SSL:               yes
Enterprise:               yes

Endpoints
enterprise "default":     https://<travis-ci-enterprise>/api (access token, current)
org:                      https://api.travis-ci.org/ ()

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
** Storing "/Users/shawnzhu/.travis/config.yml"
```

It works when using arg `--adapter net-http`.

## Problem

The actual difference at SSL/TLS layer when using different faraday adapter is the SSL options. When using default adapter (i.e., `typhoeus`), it explicitly specified CA certs in travis CLI code: https://github.com/travis-ci/travis.rb/blob/c90b1434643c0b63209c7f5f03a749ff445c1501/lib/travis/client/session.rb#L20 while my travis ci enterprise uses cert issued not by the 3 CAs in `/assets/cacerts.pem` which will fail all API requests sent by Travis CI CLI.

## Proposal

Empty `SSL_OPTIONS` when using default faraday adapter. It won't make it less secure but consistent with that in adapter `net-http` (which is default adapter on Windows platforms)

If that's ok, I'm happy to create a PR.

**Comment by waynr** [comment]
> Works using --adapter net-http option.

:confused: how is this an acceptable solution? Doesn't this imply that none of your communciations with any servers are encrypted?
