### ISSUE TITLE
NoMethodError: undefined method `receive' for nil:NilClass and color issue

### ISSUE THREAD

**Issue by WildCard65** [travis-ci/travis.rb#198]
```
System
Ruby:                     Ruby 1.9.3-p484
Operating System:         Ubuntu 14.04
RubyGems:                 RubyGems 1.8.23

CLI
Version:                  1.6.11
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2014-06-07 18:04:26 -0400

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "WildCard65"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `receive' for nil:NilClass
        from /var/lib/gems/1.9.1/gems/pusher-client-0.6.0/lib/pusher-client/socket.rb:206:in `block in connect_internal'
        from /var/lib/gems/1.9.1/gems/pusher-client-0.6.0/lib/pusher-client/socket.rb:205:in `loop'
        from /var/lib/gems/1.9.1/gems/pusher-client-0.6.0/lib/pusher-client/socket.rb:205:in `connect_internal'
        from /var/lib/gems/1.9.1/gems/pusher-client-0.6.0/lib/pusher-client/socket.rb:76:in `connect'
        from /var/lib/gems/1.9.1/gems/travis-1.6.11/lib/travis/client/listener.rb:123:in `listen'
        from /var/lib/gems/1.9.1/gems/travis-1.6.11/lib/travis/client/methods.rb:89:in `listen'
        from /var/lib/gems/1.9.1/gems/travis-1.6.11/lib/travis/client/artifact.rb:40:in `body'
        from /var/lib/gems/1.9.1/gems/travis-1.6.11/lib/travis/cli/logs.rb:19:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.6.11/lib/travis/cli/command.rb:181:in `execute'
        from /var/lib/gems/1.9.1/gems/travis-1.6.11/lib/travis/cli.rb:60:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.6.11/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'
```

Above block happened when sourcemod's spcomp was activated:  

```
Compiling freak_fortress_2.sp...
SourcePawn Compiler 1.5.4-dev+b73d067
Copyright (c) 1997-2006, ITB CompuPhase, (C)2004-2008 AlliedModders, LLC
```

Also another issue with travis logs, on rare occasions, it does not reset ubuntu 14.04 LTS's terminal coloring back to white, it stays at what ever color used last. And the above line of what I got from travis logs command before the error was in green due to this returning 0:  

```
The command "echo "Got to implement work around to knew sourcemod bash compile script."" exited with 0.
```

**Comment by ZyX-I** [comment]
```
System
Ruby:                     Ruby 1.9.3-p551
Operating System:         Linux
RubyGems:                 RubyGems 2.0.14

CLI
Version:                  1.7.4
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-01-01 17:25:02 +0300

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "ZyX-I"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `receive' for nil:NilClass
        from /home/zyx/.gem/ruby/1.9.1/gems/pusher-client-0.6.0/lib/pusher-client/socket.rb:206:in `block in connect_internal'
        from /home/zyx/.gem/ruby/1.9.1/gems/pusher-client-0.6.0/lib/pusher-client/socket.rb:205:in `loop'
        from /home/zyx/.gem/ruby/1.9.1/gems/pusher-client-0.6.0/lib/pusher-client/socket.rb:205:in `connect_internal'
        from /home/zyx/.gem/ruby/1.9.1/gems/pusher-client-0.6.0/lib/pusher-client/socket.rb:76:in `connect'
        from /home/zyx/.gem/ruby/1.9.1/gems/travis-1.7.4/lib/travis/client/listener.rb:123:in `listen'
        from /home/zyx/.gem/ruby/1.9.1/gems/travis-1.7.4/lib/travis/client/methods.rb:90:in `listen'
        from /home/zyx/.gem/ruby/1.9.1/gems/travis-1.7.4/lib/travis/client/artifact.rb:53:in `body'
        from /home/zyx/.gem/ruby/1.9.1/gems/travis-1.7.4/lib/travis/cli/logs.rb:39:in `display_log'
        from /home/zyx/.gem/ruby/1.9.1/gems/travis-1.7.4/lib/travis/cli/logs.rb:23:in `run'
        from /home/zyx/.gem/ruby/1.9.1/gems/travis-1.7.4/lib/travis/cli/command.rb:198:in `execute'
        from /home/zyx/.gem/ruby/1.9.1/gems/travis-1.7.4/lib/travis/cli.rb:64:in `run'
        from /home/zyx/.gem/ruby/1.9.1/gems/travis-1.7.4/bin/travis:18:in `<top (required)>'
        from /home/zyx/.gem/ruby/1.9.1/bin/travis:23:in `load'
        from /home/zyx/.gem/ruby/1.9.1/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

The issue happens *always* when streaming logs just before receiving the very last chunk at least in case of failed builds.

**Comment by StephenTurley** [comment]
I just got the same error when streaming logs on version 1.7.5
```
System
Ruby:                     Ruby 2.1.5-p273
Operating System:         Fedora 21
RubyGems:                 RubyGems 2.2.2

CLI
Version:                  1.7.5
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-03-23 20:44:47 -0400

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "StephenTurley"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `receive' for nil:NilClass
        from /home/stephen/.gem/ruby/gems/pusher-client-0.6.0/lib/pusher-client/socket.rb:206:in `block in connect_internal'
        from /home/stephen/.gem/ruby/gems/pusher-client-0.6.0/lib/pusher-client/socket.rb:205:in `loop'
        from /home/stephen/.gem/ruby/gems/pusher-client-0.6.0/lib/pusher-client/socket.rb:205:in `connect_internal'
        from /home/stephen/.gem/ruby/gems/pusher-client-0.6.0/lib/pusher-client/socket.rb:76:in `connect'
        from /home/stephen/.gem/ruby/gems/travis-1.7.5/lib/travis/client/listener.rb:123:in `listen'
        from /home/stephen/.gem/ruby/gems/travis-1.7.5/lib/travis/client/methods.rb:90:in `listen'
        from /home/stephen/.gem/ruby/gems/travis-1.7.5/lib/travis/client/artifact.rb:53:in `body'
        from /home/stephen/.gem/ruby/gems/travis-1.7.5/lib/travis/cli/logs.rb:39:in `display_log'
        from /home/stephen/.gem/ruby/gems/travis-1.7.5/lib/travis/cli/logs.rb:23:in `run'
        from /home/stephen/.gem/ruby/gems/travis-1.7.5/lib/travis/cli/command.rb:198:in `execute'
        from /home/stephen/.gem/ruby/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
        from /home/stephen/.gem/ruby/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
        from /home/stephen/bin/travis:23:in `load'
        from /home/stephen/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by grosser** [comment]
Same here:

```
/opt/boxen/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:206:in `block in connect_internal': undefined method `receive' for nil:NilClass (NoMethodError)
	from /opt/boxen/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `loop'
	from /opt/boxen/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `connect_internal'
	from /opt/boxen/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:76:in `connect'
	from /opt/boxen/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/travis-1.7.6/lib/travis/client/listener.rb:123:in `listen'
	from /opt/boxen/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/travis-1.7.6/lib/travis/client/methods.rb:90:in `listen'
	from /opt/boxen/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/travis-1.7.6/lib/travis/client/artifact.rb:54:in `body'
	from ./script/travis_failures.rb:61:in `block (2 levels) in <main>'
```

Always happens at the end of jobs that where still live when streaming started ... so I guess @connection is getting unset ... I'm running multiple logs in multiple threads if that could be an issue ...

**Comment by Sagar2366** [comment]
Same error on ubuntu 16.04
An error occurred running `travis compile`:
    NoMethodError: undefined method `jobs' for nil:NilClass
        from /home/ubuntu/.travis/travis-build/init.rb:79:in `set_up_config'
        from /home/ubuntu/.travis/travis-build/init.rb:28:in `run'
        from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /home/ubuntu/.travis/travis-build/bin/travis:29:in `load'
        from /home/ubuntu/.travis/travis-build/bin/travis:29:in `<main>'
