### ISSUE TITLE
Github Release setup fails

### ISSUE THREAD

**Issue by Miladiir** [travis-ci/travis.rb#199]
After using `travis setup releases` and entering the correct credentials 100 times I always get this error that suggests that there is a problem with Github two factor authentication.

BTW, the credentials I used are the correct ones. I just logged in with the same One Time Code aswell...

```
System
Ruby:                     Ruby 2.0.0-p451
Operating System:         Mac OS X 10.9.3
RubyGems:                 RubyGems 2.0.14

CLI
Version:                  1.6.11
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2014-06-08 12:24:23 +0200

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis setup --org`:
    RuntimeError: Validation Failed
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/tools/github.rb:206:in `rescue in login'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/tools/github.rb:195:in `login'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/tools/github.rb:204:in `rescue in login'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/tools/github.rb:195:in `login'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/tools/github.rb:74:in `possible_tokens'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/tools/github.rb:41:in `each_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/tools/github.rb:36:in `with_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/cli/setup/releases.rb:12:in `block in run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/cli/setup/service.rb:61:in `block in deploy'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/cli/setup/service.rb:52:in `configure'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/cli/setup/service.rb:60:in `deploy'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/cli/setup/releases.rb:11:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/cli/setup.rb:47:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/cli/command.rb:181:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/lib/travis/cli.rb:60:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.6.11/bin/travis:18:in `<top (required)>'
        from /usr/bin/travis:23:in `load'
        from /usr/bin/travis:23:in `<main>'
```

**Comment by evils** [comment]
Same problem here

**Comment by fikovnik** [comment]
@wclyffe's fix worked for me as well - deleting "automatic releases for ..." token in github.

**Comment by bill-auger** [comment]
this happened to me today also - it is 100% repeatable every time the command fails or is terminated early - this happened for me i typed control chars into the filename and killed with CTRL-C

i too was able to get past this using @wclyffe's suggestion but i then hit another error
```
Encrypt API key? |yes| y
resource not found ({"file":"not found"})
```
seems to be the same as #237 -  i can generate another token manually but the ```travis encrypt``` command give the same "resource not found" error - trying again then produces the original error until   the personal access token is deleted again

**Comment by patcon** [comment]
Ditto, but @wclyffe's solution doesn't work, as I don't have a `temporary token`...

**Comment by noraesae** [comment]
@wclyffe's solution works here, but the token was in `Personal access tokens`, not in `Applications`.

**Comment by voltagex** [comment]
Also got this - I want to use an access token, not my username and password

**Comment by voltagex** [comment]
```
travis setup releases --debug
** Loading "/home/voltagex/.travis/config.yml"
** GET "repos/voltagex/rpi2-gstreamer-build"
**   took 0.11 seconds
** Loading gh
** GET "config"
**   took 0.15 seconds
Username: voltagex
Password for voltagex: ****************************************
** GitHub API: POST /authorizations
** Storing "/home/voltagex/.travis/error.log"
This API can only be accessed with username and password Basic Auth
for a full error report, run travis report --org
```

**Comment by DanVanAtta** [comment]
Hello, I've run into this a few times. The error message could be a bit more helpful. I hit this pretty frequently when tokens were already created once. Two tokens cannot be recreated with the same name, so re-running `travis setup releases` will always fai with this error. It often has not been very obvious to me the cause of the failure, a very helpful update I would suggest is to change the error message to say something like "could not create the github personal access token named: 'automatic releases for ...', a token with that name already exists."

**Comment by jobevers** [comment]
Same issue here:

```
$ travis setup releases
Detected repository as jobevers/lbry, is this correct? |yes| yes
Username: jobevers
Password for jobevers: ********
Two-factor authentication code for jobevers: [...]
no suitable github token found

$ travis setup releases
Username: jobevers
Password for jobevers: ********
Two-factor authentication code for jobevers: [...]
Validation Failed
for a full error report, run travis report --org

$ travis report --org
System
Ruby:                     Ruby 2.3.0-p0
Operating System:         Mac OS X 10.11.4
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.2
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2016-05-23 11:02:28 -0500

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis setup --org`:
    RuntimeError: Validation Failed
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:208:in `basic_auth'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:214:in `rescue in basic_auth'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:208:in `basic_auth'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:221:in `login'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:49:in `each_token'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/tools/github.rb:36:in `with_token'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/cli/setup/releases.rb:12:in `block in run'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/cli/setup/service.rb:61:in `block in deploy'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/cli/setup/service.rb:52:in `configure'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/cli/setup/service.rb:60:in `deploy'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/cli/setup/releases.rb:11:in `run'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/cli/setup.rb:55:in `run'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/bin/travis:23:in `load'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/bin/travis:23:in `<main>'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/jobevers/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by erikdw** [comment]
I tried to follow @wclyffe 's answer, but it lacked a full URL in this statement:
> I noticed that a new personal access token `temporary token` has been created on the `settings/applications` page

So, I assumed that `settings/applications` page meant:   https://github.com/settings/applications

Unfortunately, it seems that the token settings have moved to another page on GitHub.  Right now I have to go to this URL on github in order to see the tokens:
* https://github.com/settings/tokens

So the current solution to this problem, assuming you are in the same situation as me (regenerating the token for a GitHub project that already has a token listed in https://github.com/settings/tokens) is to delete the existing token on https://github.com/settings/tokens, and then rerun the `travis setup releases` command.

**Comment by amyliu1062** [comment]
@Joshua-Anderson  how to make oauth token? do u have an url to introduce it ?

**Comment by amyliu1062** [comment]
@noraesae `Personal access tokens` in where ? where can i find ?

**Comment by ankon** [comment]
> I noticed that a new personnal access token temporary token has been created on the settings/applications page on the first run of travis setup releases. If I delete that token before running travis setup releases again, it works.

Maybe it helps to actually fix this in the client, rather than having people get stuck with a useless error message:
~~~~
$ travis login --pro -E --skip-completion-check --skip-version-check
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: ankon
Password for ankon: ......
Two-factor authentication code for ankon: .........
/usr/local/bundle/gems/faraday-0.9.2/lib/faraday/response/raise_error.rb:13:in `on_complete': GH request failed (GH::Error)
verb:               :post
url:                /authorizations
headers:            {"User-Agent"=>"GH/0.14.0", "Accept"=>"application/vnd.github.v3+json,application/vnd.github.beta+json;q=0.5,application/json;q=0.1", "Accept-Charset"=>"utf-8", "X-GitHub-OTP"=>"........."}
error:              Faraday::ClientError: the server responded with status 422
payload:            {"scopes":["user:email","repo","read:org"],"note":"temporary token to identify with the travis command line client against https://api.travis-ci.com/"}
response_status:    422
response_headers:   {"server"=>"GitHub.com", "date"=>"Fri, 04 Nov 2016 15:04:23 GMT", "content-type"=>"application/json; charset=utf-8", "content-length"=>"218", "connection"=>"close", "status"=>"422 Unprocessable Entity", "x-ratelimit-limit"=>"5000", "x-ratelimit-remaining"=>"4938", "x-ratelimit-reset"=>"1478272714", "x-github-media-type"=>"github.v3; format=json", "access-control-expose-headers"=>"ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval", "access-control-allow-origin"=>"*", "content-security-policy"=>"default-src 'none'", "strict-transport-security"=>"max-age=31536000; includeSubdomains; preload", "x-content-type-options"=>"nosniff", "x-frame-options"=>"deny", "x-xss-protection"=>"1; mode=block", "x-github-request-id"=>"2599EB84:5895:4A5A19:581CA376"}
response_body:      {"message":"Validation Failed","errors":[{"resource":"OauthAccess","code":"already_exists","field":"description"}],"documentation_url":"https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization"}
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/request/retry.rb:116:in `call'
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/request/authorization.rb:38:in `call'
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/remote.rb:79:in `http'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/token_check.rb:28:in `http'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/instrumentation.rb:16:in `block in http'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/instrumentation.rb:30:in `instrument'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/instrumentation.rb:16:in `http'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/remote.rb:86:in `request'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/remote.rb:97:in `post'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/tools/github.rb:222:in `block in login'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/tools/github.rb:210:in `basic_auth'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/tools/github.rb:214:in `rescue in basic_auth'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/tools/github.rb:208:in `basic_auth'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/tools/github.rb:221:in `login'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/tools/github.rb:80:in `possible_tokens'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/tools/github.rb:49:in `each_token'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/tools/github.rb:36:in `with_token'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/cli/login.rb:31:in `login'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/cli/login.rb:40:in `run'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
	from /usr/local/bundle/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
	from /usr/local/bundle/bin/travis:22:in `load'
	from /usr/local/bundle/bin/travis:22:in `<main>'
~~~~

When I remove that conflicting token I get slightly further, but then the client seems to fail to actually save the token:
~~~~
$ travis login --pro -E --skip-completion-check --skip-version-check
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: ankon
Password for ankon: .........
Two-factor authentication code for ankon: .........
Successfully logged in as ankon!
/usr/local/bundle/gems/faraday-0.9.2/lib/faraday/response/raise_error.rb:13:in `on_complete': GH request failed (GH::Error)
verb:               :delete
url:                /authorizations/59288280
headers:            {"User-Agent"=>"GH/0.14.0", "Accept"=>"application/vnd.github.v3+json,application/vnd.github.beta+json;q=0.5,application/json;q=0.1", "Accept-Charset"=>"utf-8", "X-GitHub-OTP"=>"........."}
error:              Faraday::ClientError: the server responded with status 401
payload:            nil
response_status:    401
response_headers:   {"server"=>"GitHub.com", "date"=>"Fri, 04 Nov 2016 15:07:10 GMT", "content-type"=>"application/json; charset=utf-8", "content-length"=>"160", "connection"=>"close", "status"=>"401 Unauthorized", "x-github-otp"=>"required; app", "x-github-media-type"=>"github.v3; format=json", "x-ratelimit-limit"=>"60", "x-ratelimit-remaining"=>"51", "x-ratelimit-reset"=>"1478274514", "access-control-expose-headers"=>"ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval", "access-control-allow-origin"=>"*", "content-security-policy"=>"default-src 'none'", "strict-transport-security"=>"max-age=31536000; includeSubdomains; preload", "x-content-type-options"=>"nosniff", "x-frame-options"=>"deny", "x-xss-protection"=>"1; mode=block", "x-github-request-id"=>"2599EB84:5893:8747B4:581CA41E"}
response_body:      {"message":"Must specify two-factor authentication OTP code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"}
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/request/retry.rb:116:in `call'
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/request/authorization.rb:38:in `call'
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/remote.rb:79:in `http'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/token_check.rb:28:in `http'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/instrumentation.rb:16:in `block in http'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/instrumentation.rb:30:in `instrument'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/instrumentation.rb:16:in `http'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/remote.rb:86:in `request'
	from /usr/local/bundle/gems/gh-0.14.0/lib/gh/remote.rb:102:in `delete'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/tools/github.rb:223:in `block (2 levels) in login'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/tools/github.rb:52:in `ensure in each_token'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/tools/github.rb:52:in `each_token'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/tools/github.rb:36:in `with_token'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/cli/login.rb:31:in `login'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/cli/login.rb:40:in `run'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
	from /usr/local/bundle/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
	from /usr/local/bundle/bin/travis:22:in `load'
	from /usr/local/bundle/bin/travis:22:in `<main>'
~~~~

This is with 2FA enabled, so maybe the second issue doesn't appear if you don't have that.
