### ISSUE TITLE
travis commands -- JSON::ParserError

### ISSUE THREAD

**Issue by Neamar** [travis-ci/travis.rb#224]
When running `travis encrypt "254bd409c0975bbdea"`, i get the following:

```
JSON::ParserError
for a full error report, run travis report
```

And `travis report`:

```
System
Ruby:                     Ruby 1.9.3-p484
Operating System:         Ubuntu 14.04
RubyGems:                 RubyGems 1.8.23

CLI
Version:                  1.7.1
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2014-08-16 13:19:18 +0200

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                invalid access token
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (access token)
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis encrypt`:
    MultiJson::LoadError: JSON::ParserError
        from /var/lib/gems/1.9.1/gems/multi_json-1.8.0/lib/multi_json/adapter.rb:19:in `load'
        from /var/lib/gems/1.9.1/gems/multi_json-1.8.0/lib/multi_json.rb:120:in `load'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/response.rb:35:in `initialize'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/remote.rb:153:in `new'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/remote.rb:153:in `modify'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/remote.rb:73:in `generate_response'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/normalizer.rb:8:in `generate_response'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/parallel.rb:27:in `generate_response'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/remote.rb:88:in `request'
        from /var/lib/gems/1.9.1/gems/gh-0.13.0/lib/gh/remote.rb:106:in `head'
        from /var/lib/gems/1.9.1/gems/travis-1.7.1/lib/travis/cli/repo_command.rb:108:in `detect_api_endpoint'
        from /var/lib/gems/1.9.1/gems/travis-1.7.1/lib/travis/cli/repo_command.rb:23:in `setup'
        from /var/lib/gems/1.9.1/gems/travis-1.7.1/lib/travis/cli/command.rb:197:in `execute'
        from /var/lib/gems/1.9.1/gems/travis-1.7.1/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.7.1/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

This happens for other commands too, `travis login`,

```
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: Neamar
Password for Neamar: ...
Two-factor authentication code for Neamar: ...
Successfully logged in as Neamar!
JSON::ParserError
for a full error report, run travis report
```

**Comment by andyli** [comment]
`sudo gem update` solved for me too!

**Comment by herschel666** [comment]
Yep, it simply seems to be `sudo gem update` …
