### ISSUE TITLE
travis encrypt error: NameError: uninitialized constant GH::Error

### ISSUE THREAD

**Issue by rhyolight** [travis-ci/travis.rb#247]
After `gem install travis`, I am trying to run `travis encrypt` with my repository directory. 

```
> travis encrypt
uninitialized constant GH::Error
for a full error report, run travis report
```

Travis report: 

```
> travis report
System
Ruby:                     Ruby 2.1.3-p242
Operating System:         Mac OS X 10.10
RubyGems:                 RubyGems 2.2.2

CLI
Version:                  1.7.4
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2014-11-20 09:59:09 -0800

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "rhyolight"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis encrypt`:
    NameError: uninitialized constant GH::Error
        from /usr/local/lib/ruby/gems/2.1.0/gems/travis-1.7.4/lib/travis/cli/repo_command.rb:110:in `rescue in detect_api_endpoint'
        from /usr/local/lib/ruby/gems/2.1.0/gems/travis-1.7.4/lib/travis/cli/repo_command.rb:106:in `detect_api_endpoint'
        from /usr/local/lib/ruby/gems/2.1.0/gems/travis-1.7.4/lib/travis/cli/repo_command.rb:23:in `setup'
        from /usr/local/lib/ruby/gems/2.1.0/gems/travis-1.7.4/lib/travis/cli/command.rb:197:in `execute'
        from /usr/local/lib/ruby/gems/2.1.0/gems/travis-1.7.4/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.1.0/gems/travis-1.7.4/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'
```

I also tried different iterations of the same command with the same error. 

```
travis encrypt AWS_SECRET_ACCESS_KEY=foobar
travis encrypt AWS_SECRET_ACCESS_KEY=foobar --repo=numenta/nupic.core
travis encrypt AWS_SECRET_ACCESS_KEY=foobar --repo=numenta/nupic.core --debug
```

This has definitely worked for me in the past in other repositories. In fact, if I `cd` into another repo...

```
> cd /Users/mtaylor/nta/nupic
> travis encrypt foo=bar --repo=numenta/nupic
Please add the following to your .travis.yml file:

  secure: "HpxZ8XYdMScPTDpoMWXoe31a2M3Y9q5cSAn3+0d+JDTOpVcTghy4exFhNViT3XwB/vs5Rv2ba63W5jDwrzuAKlyMJ+BGBbyOjGnuAgHRLgZpD+JQFWQSFvP91WoEAo8HzAQa4u6aU45D19DKz+S0ikb95ERSov4I8df/BuLp0IY="
```

It works! Is there something wrong with my [configuration file](https://github.com/numenta/nupic.core/blob/master/.travis.yml)? `travis lint` shows no errors:

```
> travis lint
Warnings for .travis.yml:
[x] in notifications section: value for webhooks section is empty, dropping
[x] in notifications.webhooks section: value for urls section is empty, dropping
[x] in notifications.webhooks.urls section: unexpected mapping
[x] your repository must be feature flagged for the os setting to be used
```

**Comment by rdh** [comment]
`gem update backports` resolved this problem for me, as reported by kops on https://github.com/travis-ci/travis.rb/issues/253

**Comment by rhyolight** [comment]
@rdh Thanks for the tip, that helped for me, too.
