### ISSUE TITLE
Travis 1.7.5 and Ruby 2.2.0 doesn't run

### ISSUE THREAD

**Issue by gennei** [travis-ci/travis.rb#261]
Update Travis 1.7.5 but doesn't run

Developmet Env
OS: OS X Yosemite
Ruby: 2.2.0-rc1
Travis: 1.7.5

console log
```
/Users/gennei/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:150:in `default_endpoint': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/gennei/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:154:in `detected_endpoint'
	from /Users/gennei/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:70:in `detected_endpoint?'
	from /Users/gennei/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:158:in `endpoint_option'
	from /Users/gennei/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli/command.rb:213:in `rescue in execute'
	from /Users/gennei/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli/command.rb:191:in `execute'
	from /Users/gennei/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
	from /Users/gennei/.rbenv/versions/2.2.0-rc1/lib/ruby/gems/2.2.0/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
	from /Users/gennei/.rbenv/versions/2.2.0-rc1/bin/travis:23:in `load'
	from /Users/gennei/.rbenv/versions/2.2.0-rc1/bin/travis:23:in `<main>'
```

**Comment by BanzaiMan** [comment]
Could you test it with 2.2.0? We are not testing travis.rb with 2.2.0 yet.

**Comment by sindresorhus** [comment]
I'm seeing this with Ruby 2.0.0 too.

OS: OS X Yosemite
Ruby: 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
Travis: 1.7.5

```
/Library/Ruby/Gems/2.0.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:150:in `default_endpoint': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:154:in `detected_endpoint'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:70:in `detected_endpoint?'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:158:in `endpoint_option'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.5/lib/travis/cli/command.rb:213:in `rescue in execute'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.5/lib/travis/cli/command.rb:191:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
	from /usr/bin/travis:23:in `load'
	from /usr/bin/travis:23:in `<main>'
```

**Comment by Aupajo** [comment]
Getting this with 2.2.0:

```
$ travis whom

/Users/pete/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:150:in `default_endpoint': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/pete/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:154:in `detected_endpoint'
	from /Users/pete/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:70:in `detected_endpoint?'
	from /Users/pete/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:158:in `endpoint_option'
	from /Users/pete/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli/command.rb:213:in `rescue in execute'
	from /Users/pete/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli/command.rb:191:in `execute'
	from /Users/pete/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
	from /Users/pete/.gem/ruby/2.2.0/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
	from /Users/pete/.gem/ruby/2.2.0/bin/travis:23:in `load'
	from /Users/pete/.gem/ruby/2.2.0/bin/travis:23:in `<main>'
```

And:

```
$ travis version
private method `load' called for Psych:Module
for a full error report, run travis report
```

**Comment by Aupajo** [comment]
Tried checking out the repo on 2.2.0.

If I call the executable directly (e.g. `bundle exec bin/travis`), everything works fine.

Three tests fail:

```
$ bundle exec rake
/Users/pete/.rubies/ruby-2.2.0/bin/ruby -S rspec spec -c
....F..................F..............................................................................F.........................................................................................................................................................................

Failures:

  1) Travis::CLI::Encrypt travis encrypt foo -i
     Failure/Error: run_cli('encrypt', 'foo', '-i').should be_success
       expected success? to return true, got false
     # ./spec/cli/encrypt_spec.rb:15:in `block (2 levels) in <top (required)>'

  2) Travis::CLI::History travis history -d
     Failure/Error: stdout.should be =~ /2013-01-13 \d+:55:17 #6180 failed:    master Associaton -> Association/
       expected: =~ /2013-01-13 \d+:55:17 #6180 failed:    master Associaton -> Association/
            got:    "2013-01-14 04:55:17 #6180 failed:    master Associaton -> Association\n"
     # ./spec/cli/history_spec.rb:11:in `block (2 levels) in <top (required)>'

  3) Travis::CLI::Status travis status -i
     Failure/Error: run_cli('status', '-i').should be_success
       expected success? to return true, got false
     # ./spec/cli/status_spec.rb:25:in `block (2 levels) in <top (required)>'

Deprecation Warnings:

Use of rspec-core's `its` method is deprecated. Use the rspec-its gem instead. Called from /Users/pete/Workspace/forkful/travis.rb/spec/client/account_spec.rb:7:in `block (2 levels) in <top (required)>'.
Use of rspec-core's `its` method is deprecated. Use the rspec-its gem instead. Called from /Users/pete/Workspace/forkful/travis.rb/spec/client/account_spec.rb:8:in `block (2 levels) in <top (required)>'.
Use of rspec-core's `its` method is deprecated. Use the rspec-its gem instead. Called from /Users/pete/Workspace/forkful/travis.rb/spec/client/account_spec.rb:9:in `block (2 levels) in <top (required)>'.
Too many uses of deprecated 'Use of rspec-core's `its` method'. Pass `--deprecation-out` or set `config.deprecation_stream` to a file for full output.

`be_false` is deprecated. Use `be_falsey` (for Ruby's conditional semantics) or `be false` (for exact `== false` equality) instead. Called from /Users/pete/Workspace/forkful/travis.rb/spec/cli/init_spec.rb:24:in `block (3 levels) in <top (required)>'.
`be_false` is deprecated. Use `be_falsey` (for Ruby's conditional semantics) or `be false` (for exact `== false` equality) instead. Called from /Users/pete/Workspace/forkful/travis.rb/spec/client/user_spec.rb:11:in `block (2 levels) in <top (required)>'.

`be_true` is deprecated. Use `be_truthy` (for Ruby's conditional semantics) or `be true` (for exact `== true` equality) instead. Called from /Users/pete/Workspace/forkful/travis.rb/spec/cli/init_spec.rb:27:in `block (3 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

87 deprecation warnings total

Finished in 3.2 seconds
272 examples, 3 failures

Failed examples:

rspec ./spec/cli/encrypt_spec.rb:14 # Travis::CLI::Encrypt travis encrypt foo -i
rspec ./spec/cli/history_spec.rb:9 # Travis::CLI::History travis history -d
rspec ./spec/cli/status_spec.rb:24 # Travis::CLI::Status travis status -i
rake aborted!
```

**Comment by miyagawa** [comment]
I had the same issue, and after debugging session on IRC, we discovered that this might be related to rubygems issue with Ruby 2.2.0 https://github.com/rubygems/rubygems/issues/784 and this will be fixed in rubygems 2.4.6 (not released at this point). I installed rubygems from the git master and confirmed it has fixed the issue for me.

**Comment by BanzaiMan** [comment]
Could another person test the process @miyagawa mentioned above? If you could confirm the fix, I'll close this as an upstream issue.

**Comment by gennei** [comment]
I tried the process of @miyagawa wrote.
I could run travis command. 

```
$ travis version
1.7.5
```

But the test does not pass. The test results are the same as those @Aupajo wrote

**Comment by BanzaiMan** [comment]
Those are known broken tests. We need to fix them.

I'm closing this now.
