### ISSUE TITLE
Is read only permission enough for a continuous integration user?

### ISSUE THREAD

**Issue by danse** [travis-ci/travis.rb#263]
I have a continuous integration user set for my organisation. The user has read only access to relevant repos in order to run build jobs with private dependencies, as in the Travis doc.

When i use the command line tool to generate a new key, i get the following error:

    \\n-----END RSA PRIVATE KEY-----\\n\",\"description\":\"key for fetching dependencies for xxx via yyy\"}}"
    **   took 0.32 seconds
    /Library/Ruby/Gems/2.0.0/gems/travis-1.7.5/lib/travis/client/session.rb:219:in `raw': {"error":"Couldn't find repository"} (Travis::Client::NotFound)

When logging with the continuous integration user credentials, i see the database listed as read only, and i see that i cannot set the keys for it.

Using my personal user, which has write permissions, i can add the key on the Travis side via the web interface, and everything works.

So is this supposed to work with read only permissions, or would the user need more permissions?

**Comment by nathanielks** [comment]
I'm encountering the same problem. I've created a user that is a member of a team with only read-only permissions and am attempting to add ssh keys to it and the repo in Travis:

```
$ travis sshkey --generate -r myorg/main --description "CI dependencies" --debug --explode
** Loading "/Users/nathaniel.schweinber/.travis/config.yml"
** Timeout::Error: execution expired
** Loading gh
** GET "config"
**   took 0.24 seconds
** GitHub API: HEAD /repos/myorg/main
** GET "repos/myorg/main"
**   took 0.6 seconds
** GET "config"
**   took 0.19 seconds
We need the GitHub login for the account you want to add the key to.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Username: the-machine-user
Password for the-machine-user: ************************************
** GitHub API: GET /user?per_page=100
**   took 0.69 seconds
** GitHub API: GET /user?per_page=100
**   took 0.24 seconds
** GitHub API: GET /repos/myorg/main?per_page=100
**   took 0.25 seconds

Generating RSA key.
Uploading public key to GitHub.
** GitHub API: POST /user/keys
**   took 0.33 seconds
Uploading private key to Travis CI.
** PATCH "settings/ssh_key/123456" "REDACTED",\"description\":\"CI dependencies\"}}"
**   took 0.15 seconds
```

I've looked at the github account and the public key has been added, but the private key is failing to be added to Travis.

**Comment by nathanielks** [comment]
I just attempted the same command using a user that _does_ have admin access and the same error appeared. I forgot to include it above, so here it is:

```
/Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/gems/travis-1.7.7/lib/travis/client/session.rb:219:in `raw': {"error":"Couldn't find repository"} (Travis::Client::NotFound)
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/gems/travis-1.7.7/lib/travis/client/session.rb:196:in `patch_raw'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/gems/travis-1.7.7/lib/travis/client/singleton_setting.rb:23:in `update'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/gems/travis-1.7.7/lib/travis/cli/sshkey.rb:67:in `block in generate_key'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/gems/travis-1.7.7/lib/travis/tools/github.rb:43:in `block in with_basic_auth'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/gems/travis-1.7.7/lib/travis/tools/github.rb:210:in `basic_auth'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/gems/travis-1.7.7/lib/travis/tools/github.rb:41:in `with_basic_auth'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/gems/travis-1.7.7/lib/travis/cli/sshkey.rb:54:in `generate_key'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/gems/travis-1.7.7/lib/travis/cli/sshkey.rb:24:in `run'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/gems/travis-1.7.7/lib/travis/cli/command.rb:198:in `execute'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/gems/travis-1.7.7/lib/travis/cli.rb:64:in `run'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/gems/travis-1.7.7/bin/travis:18:in `<top (required)>'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/bin/travis:23:in `load'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/bin/travis:23:in `<main>'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
        from /Users/nathaniel.schweinber/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

Now, I'm not sure it's a coincidence that I'm encountering the same error on the travis site, but I haven't figured out how to fix that yet. The repo I'm attempting to add is visible once I go to the organization's page in travis, but it's not available when I'm just looking at it as an owner.

**Comment by nathanielks** [comment]
FWIW I've publicized both accounts' membership and still no luck.
