### ISSUE TITLE
Travis login throws Faraday error

### ISSUE THREAD

**Issue by ezescaruli** [travis-ci/travis.rb#265]
Hello,

I'm running `travis login --pro` to login from the console, but I am getting this error:
```
Username: ezescaruli
Password for ezescaruli: *
undefined method `try' for #<Faraday::Env:0x007f87bab968f8>
for a full error report, run travis report --pro
```

`travis report --pro` throws the following:
```
System
Ruby:                     Ruby 2.1.5-p273
Operating System:         Mac OS X 10.10.1
RubyGems:                 RubyGems 2.4.3

CLI
Version:                  1.7.5
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-01-22 10:33:45 +1100

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (current)
org:                      https://api.travis-ci.org/ ()

Last Exception
An error occurred running `travis login --pro`:
    NoMethodError: undefined method `try' for #<Faraday::Env:0x007f87bab968f8>
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/remote.rb:71:in `generate_response'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/normalizer.rb:8:in `generate_response'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/parallel.rb:27:in `generate_response'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/remote.rb:88:in `request'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/gh-0.13.3/lib/gh/remote.rb:96:in `post'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/lib/travis/tools/github.rb:222:in `block in login'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/lib/travis/tools/github.rb:210:in `basic_auth'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/lib/travis/tools/github.rb:221:in `login'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/lib/travis/tools/github.rb:49:in `each_token'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/lib/travis/tools/github.rb:36:in `with_token'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/lib/travis/cli/login.rb:31:in `login'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/lib/travis/cli/login.rb:40:in `run'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/lib/travis/cli/command.rb:198:in `execute'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/bin/travis:23:in `load'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/bin/travis:23:in `<main>'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /Users/ezescaruli/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

I tried running `gem update faraday` to see if the problem was an outdated Faraday gem issue, but I'm still having the same problem. Finally I ran `gem update` to update any gem that could be outdated, but no luck again.

Anyone has faced a similar issue? Thanks!

**Comment by rjmackay** [comment]
Getting similar issues for any travis command I run, but only on a specific repo.

**Comment by oerdnj** [comment]
Is you repo an user or an organization one? I am having same problem.

**Comment by rjmackay** [comment]
Organisation repo: https://github.com/ushahidi/platform-client/

**Comment by rkh** [comment]
Oh, I think I broke that with a gh release yesterday. Could you try if
running `ruby -r back ports -S travis ...` fixes this?

**Comment by oerdnj** [comment]
Looks like it's relevant to ruby version, running the command under:

    rvm 1.9 do travis ...

makes the command succeed.

**Comment by rjmackay** [comment]
@rkh yup that worked.

**Comment by androidfred** [comment]
I'm on Cloud9 IDE where rvm 1.9 do travis doesn't work. Suggestions?

**Comment by oerdnj** [comment]
Downgrading the gh gem to previous version also works. (gem install gh -v 0.13.2)

**Comment by androidfred** [comment]
@oerdnj That worked! How did you figure that out? 

For the record, I first had to gem uninstall gh

**Comment by oerdnj** [comment]
@androidfred The @rkh said that in:

> Oh, I think I broke that with a gh release yesterday.

So it's just a previous release of gh.

**Comment by rkh** [comment]
I'm working on a new gh release to fix this.

**Comment by rkh** [comment]
Updating gh to 0.14.0 should fix this (`gem install gh`).

**Comment by ezescaruli** [comment]
Thanks, guys! Just updating the `gh` gem, as @rkh said, fixed the issue.
