### ISSUE TITLE
Unable to run travis on MRI 2.2.0p0

### ISSUE THREAD

**Issue by brixen** [travis-ci/travis.rb#271]
I installed the travis gem using MRI 2.2.0p0 but attempting to run it results in:

```
$ travis setup s3
private method `load' called for Psych:Module
for a full error report, run travis report
```

[Whole terminal output](https://gist.github.com/anonymous/3c6562ed7d9c3e916a1c).

**Comment by rkh** [comment]
What does `travis report` say, or does that not work either?

**Comment by brixen** [comment]
```
clm-bshirai:rubinius bshirai$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
clm-bshirai:rubinius bshirai$ gem install travis
Successfully installed travis-1.7.5
1 gem installed
clm-bshirai:rubinius bshirai$ travis report
/Users/bshirai/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:150:in `default_endpoint': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/bshirai/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:154:in `detected_endpoint'
	from /Users/bshirai/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:70:in `detected_endpoint?'
	from /Users/bshirai/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:158:in `endpoint_option'
	from /Users/bshirai/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli/command.rb:213:in `rescue in execute'
	from /Users/bshirai/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli/command.rb:191:in `execute'
	from /Users/bshirai/.gem/ruby/2.2.0/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
	from /Users/bshirai/.gem/ruby/2.2.0/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
	from /Users/bshirai/.gem/ruby/2.2.0/bin/travis:23:in `load'
	from /Users/bshirai/.gem/ruby/2.2.0/bin/travis:23:in `<main>'
```

**Comment by rberger** [comment]
I had the same problem. I updated my RVM and ruby to ruby-head and then was able to install travis. Not sure if being at head is what fixed it or just doing a reinstall of ruby did it.

**Comment by aruizca** [comment]
```
asymptotic-be:ajaxanywhere-os rui008$ travis report
/usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/tools/system.rb:79: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:150:in `default_endpoint': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:154:in `detected_endpoint'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:70:in `detected_endpoint?'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli/api_command.rb:158:in `endpoint_option'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli/command.rb:213:in `rescue in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli/command.rb:191:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:23:in `load'
	from /usr/local/bin/travis:23:in `<main>'
```

**Comment by rkh** [comment]
I fail to reproduce this with travis 1.7.5 and Ruby 2.2.0, unfortunately.

**Comment by aruizca** [comment]
Same problem with travis-1.7.6 nad ruby 2.2.1 on OSX 10.10.2 running `travis report` command:
```
/usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/tools/system.rb:79: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli/api_command.rb:150:in `default_endpoint': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli/api_command.rb:154:in `detected_endpoint'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli/api_command.rb:70:in `detected_endpoint?'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli/api_command.rb:158:in `endpoint_option'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli/command.rb:213:in `rescue in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli/command.rb:191:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.6/lib/travis/cli.rb:64:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.6/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:23:in `load'
	from /usr/local/bin/travis:23:in `<main>'
```

and then running `travis setup openshift' I get:
```
private method `load' called for Psych:Module
for a full error report, run travis report
```

**Comment by aruizca** [comment]
I was able to fix the problem by unistalling ruby completely and then using Homebrew to install latest Ruby version 2.2.1 and then install the travis gem.

**Comment by tsujigiri** [comment]
Same on Arch Linux:

```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
$ travis version
private method `load' called for Psych:Module
for a full error report, run travis report
$ travis report
/home/helge/.gem/ruby/2.2.0/gems/travis-1.7.6/lib/travis/cli/api_command.rb:150:in `default_endpoint': undefined method `[]' for nil:NilClass (NoMethodError)
        from /home/helge/.gem/ruby/2.2.0/gems/travis-1.7.6/lib/travis/cli/api_command.rb:154:in `detected_endpoint'
        from /home/helge/.gem/ruby/2.2.0/gems/travis-1.7.6/lib/travis/cli/api_command.rb:70:in `detected_endpoint?'
        from /home/helge/.gem/ruby/2.2.0/gems/travis-1.7.6/lib/travis/cli/api_command.rb:158:in `endpoint_option'
        from /home/helge/.gem/ruby/2.2.0/gems/travis-1.7.6/lib/travis/cli/command.rb:213:in `rescue in execute'
        from /home/helge/.gem/ruby/2.2.0/gems/travis-1.7.6/lib/travis/cli/command.rb:191:in `execute'
        from /home/helge/.gem/ruby/2.2.0/gems/travis-1.7.6/lib/travis/cli.rb:64:in `run'
        from /home/helge/.gem/ruby/2.2.0/gems/travis-1.7.6/bin/travis:18:in `<top (required)>'
        from /home/helge/.gem/ruby/2.2.0/bin/travis:23:in `load'
        from /home/helge/.gem/ruby/2.2.0/bin/travis:23:in `<main>'
```

**Comment by fenhl** [comment]
Workaround does nothing for me:

```
$ brew reinstall ruby
==> Reinstalling ruby
==> Downloading https://homebrew.bintray.com/bottles/ruby-2.2.2.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/ruby-2.2.2.yosemite.bottle.tar.gz
==> Pouring ruby-2.2.2.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/ruby/2.2.2: 1080 files, 20M
$ sudo gem update
Updating installed gems
Nothing to update
$ sudo gem uninstall travis

Select gem to uninstall:
 1. travis-1.7.7
 2. travis-1.8.0
 3. All versions
> 3
Successfully uninstalled travis-1.7.7
Remove executables:
	travis

in addition to the gem? [Yn]  y
Removing travis
Successfully uninstalled travis-1.8.0
$ sudo gem install travis
Fetching: travis-1.8.0.gem (100%)
Successfully installed travis-1.8.0
Parsing documentation for travis-1.8.0
Installing ri documentation for travis-1.8.0
Done installing documentation for travis after 2 seconds
1 gem installed
$ travis encrypt "wurstmineberg:(censored)" --add notifications.slack
private method `load' called for Psych:Module
for a full error report, run travis report
$ travis report
/usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/api_command.rb:150:in `default_endpoint': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/api_command.rb:154:in `detected_endpoint'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/api_command.rb:70:in `detected_endpoint?'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/api_command.rb:158:in `endpoint_option'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/command.rb:213:in `rescue in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli/command.rb:191:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:23:in `load'
	from /usr/local/bin/travis:23:in `<main>'
```

**Comment by romaintb** [comment]
same here, archlinux, mri 2.2.3

**Comment by aflores** [comment]
I realize this is an old post but just in case someone else runs into this.
I installed Ruby 2.3.1, and the problem went away.
