### ISSUE TITLE
travis monitor -r failed

### ISSUE THREAD

**Issue by kpp** [travis-ci/travis.rb#281]
I know I gave the wrong arg to `-r`, but it should be caught:

```
$ travis monitor -r llst
undefined method `pusher_channels' for nil:NilClass
for a full error report, run travis report
```

```
$ travis report
System
Ruby:                     Ruby 1.9.3-p484
Operating System:         LinuxMint 17
RubyGems:                 RubyGems 1.8.23

CLI
Version:                  1.7.5
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-03-20 00:06:10 +0300

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "kpp"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis monitor`:
    NoMethodError: undefined method `pusher_channels' for nil:NilClass
        from /var/lib/gems/1.9.1/gems/travis-1.7.5/lib/travis/client/listener.rb:102:in `block in subscribe'
        from /var/lib/gems/1.9.1/gems/travis-1.7.5/lib/travis/client/listener.rb:100:in `map'
        from /var/lib/gems/1.9.1/gems/travis-1.7.5/lib/travis/client/listener.rb:100:in `subscribe'
        from /var/lib/gems/1.9.1/gems/travis-1.7.5/lib/travis/client/methods.rb:89:in `listen'
        from /var/lib/gems/1.9.1/gems/travis-1.7.5/lib/travis/cli/api_command.rb:143:in `listen'
        from /var/lib/gems/1.9.1/gems/travis-1.7.5/lib/travis/cli/monitor.rb:103:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.7.5/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/1.9.1/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'

```

**Comment by BanzaiMan** [comment]
Is this still a problem? We had some Pusher problems yesterday.

**Comment by kpp** [comment]
Well, yes:
```
$ sudo gem update
Updating installed gems
Updating awesome_print
Fetching: awesome_print-1.6.1.gem (100%)
Successfully installed awesome_print-1.6.1
Updating eventmachine
Fetching: eventmachine-1.0.7.gem (100%)
Building native extensions.  This could take a while...
Successfully installed eventmachine-1.0.7
Updating ffi
Fetching: ffi-1.9.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.8
Updating ffi-rzmq
Fetching: ffi-rzmq-2.0.4.gem (100%)
Successfully installed ffi-rzmq-2.0.4
Updating pry
Fetching: pry-0.10.1.gem (100%)
Successfully installed pry-0.10.1
Updating slop
Fetching: slop-4.0.0.gem (100%)
ERROR:  Error installing slop:
	slop requires Ruby version >= 2.0.0.
Gems updated: awesome_print, eventmachine, ffi, ffi-rzmq, pry
Installing ri documentation for awesome_print-1.6.1...
Installing ri documentation for eventmachine-1.0.7...
Installing ri documentation for ffi-1.9.8...
Installing ri documentation for ffi-rzmq-2.0.4...
Installing ri documentation for pry-0.10.1...
Installing RDoc documentation for awesome_print-1.6.1...
Installing RDoc documentation for eventmachine-1.0.7...
Installing RDoc documentation for ffi-1.9.8...
Installing RDoc documentation for ffi-rzmq-2.0.4...
Installing RDoc documentation for pry-0.10.1...
```

```
$ travis monitor -r llst
undefined method `pusher_channels' for nil:NilClass
for a full error report, run travis report
```

**Comment by mrbernnz** [comment]
I'm having the same problem with this command. Has this issue been revisited?

**Comment by BanzaiMan** [comment]
The argument to the `-r` flag should be a repo slug, e.g., `travis-ci/travis.rb`.
