### ISSUE TITLE
"received" state unknown

### ISSUE THREAD

**Issue by jschneiderhan** [travis-ci/travis.rb#283]
I think the addition of the "received" state (https://github.com/travis-ci/travis-core/pull/425) needs to be reflected in states.rb. I just recently started receiving the following error:

```
Travis::Client::Error: unknown state "received" for #<Travis::Client::Build: mycompany/myproduct#4870>
/app/vendor/bundle/ruby/2.0.0/gems/travis-1.6.9/lib/travis/client/states.rb:89:in `check_state'
/app/vendor/bundle/ruby/2.0.0/gems/travis-1.6.9/lib/travis/client/states.rb:32:in `passed?'
```

I know that's an older version of the gem, but I noticed that the state is also not known on master. I'll see if I can put together a quick PR.

**Comment by jschneiderhan** [comment]
Closing because PR was merged.
