### ISSUE TITLE
travis cli stopped working against Travis CI Enterprise

### ISSUE THREAD

**Issue by MitchK** [travis-ci/travis.rb#292]
We currently experience some weird behaviour with Travis CI Enterprise & the CLI. The issue is not resolved when reinstalling ```travis``` and cleaning ```~/.travis```

```
# Travis login does work
$ travis login -X
Enterprise domain: travis-ci.mycompany.corp
Use travis-ci.mycompany.corp as default endpoint? |yes| no
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to github.mycompany.corp.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: user
Password for user: ************
Successfully logged in as user!

# File encryption fails
$ travis encrypt-file -IE .travis/id_rsa
/Library/Ruby/Gems/2.0.0/gems/travis-1.7.6/lib/travis/client/session.rb:213:in `raw': SSL error: could not verify peer (Travis::Client::SSLError)
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.6/lib/travis/client/session.rb:184:in `get_raw'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.6/lib/travis/client/session.rb:132:in `config'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.6/lib/travis/cli/api_command.rb:122:in `load_gh'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.6/lib/travis/cli/repo_command.rb:110:in `detect_api_endpoint'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.6/lib/travis/cli/repo_command.rb:23:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.6/lib/travis/cli/encrypt_file.rb:50:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.6/lib/travis/cli/command.rb:197:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.6/lib/travis/cli.rb:64:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.6/bin/travis:18:in `<top (required)>'
	from /usr/bin/travis:23:in `load'
	from /usr/bin/travis:23:in `<main>'

#  Certificate validation does not fail when calling travis ci
$ curl https://travis-ci.mycompany.corp
```

https://github.com/travis-ci/travis.rb/blob/v1.7.6/lib/travis/client/session.rb#L184
https://github.com/travis-ci/travis.rb/blob/v1.7.6/lib/travis/client/session.rb#L132
https://github.com/travis-ci/travis.rb/blob/v1.7.6/lib/travis/cli/api_command.rb#L122

Both Travis CI and GitHub Enterprise are signed with the same root certificate and it is imported to the local key store.

Cheers,
Mitch

**Comment by MitchK** [comment]
```
Use travis-ci.mycompany.corp as default endpoint? |yes| no
```
Should be yes, this was the issue.
