### ISSUE TITLE
400: "Unsupported Authorization Type" if using an access_token and requesting job.log.body

### ISSUE THREAD

**Issue by jrafanie** [travis-ci/travis.rb#294]
I have some code that needs to have an access_token for some operations (restart a build/job) but doesn't need it for others, like viewing logs from a public repository.

If I initialize a client with a token, many jobs fail to retrieve the `log.body` or `log.clean_body` with a 400 unsupported authorization type message (the **second job.log.body API** seems to fail consistently):

```ruby
require 'travis/client'

client = Travis::Client.new(:access_token => "MY_TOKEN")
repo = client.repo('travis-ci/travis.rb')
repo.recent_builds.each do |b| 
  b.jobs.each do |j| 
    puts j.id
    j.log.body
  end
end

```

Results in a failure on the second job's log every time:

```
62355772
62355773
/Users/joerafaniello/.gem/ruby/2.1.6/gems/travis-1.7.6/lib/travis/client/session.rb:221:in `raw': 400: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidArgument</Code><Message>Unsupported Authorization Type</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>token MY_TOKEN</ArgumentValue><RequestId>70642D29942104E8</RequestId><HostId>SOME_LONG_STRING</HostId></Error>" (Travis::Client::Error)
	from /Users/joerafaniello/.gem/ruby/2.1.6/gems/travis-1.7.6/lib/travis/client/session.rb:216:in `raw'
	from /Users/joerafaniello/.gem/ruby/2.1.6/gems/travis-1.7.6/lib/travis/client/session.rb:184:in `get_raw'
	from /Users/joerafaniello/.gem/ruby/2.1.6/gems/travis-1.7.6/lib/travis/client/artifact.rb:42:in `current_body'
	from /Users/joerafaniello/.gem/ruby/2.1.6/gems/travis-1.7.6/lib/travis/client/artifact.rb:50:in `body'
```

This happens on other repos also.

It looks like I can workaround this:
* nil out the the token just before calling the job.log.body API call and resetting it after
* set the token before the operations requiring the token (restart job/build, etc.) and reset it to nil after

Neither of these is very nice.

See below:

```ruby

require 'travis/client'

client = Travis::Client.new(:access_token => "MY_TOKEN")
repo = client.repo('travis-ci/travis.rb')
repo.recent_builds.each do |b| 
  b.jobs.each do |j| 
    puts j.id
    repo.session.access_token = nil
    j.log.body
    repo.session.access_token = "MY_TOKEN"
  end
end

```

Outputs (this workaround works): 

```
62355772
62355773
62355774
62355775
62355776
62355777
62355778
62355779
62355780
62355781
62299214
62299215
62299216
62299217
62299218
62299219
62299220
62299221
62299222
62299223
57651618
57651620
57651621
...
```

Here is my travis report output:

```
System
Ruby:                     Ruby 2.1.6-p336
Operating System:         Mac OS X 10.9.5
RubyGems:                 RubyGems 2.2.3

CLI
Version:                  1.7.6
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2015-05-13 16:36:54 -0400

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "jrafanie"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by jrafanie** [comment]
Am I doing something wrong? It seems that the api request for log data shouldn't include the token if it's not supported or even needed. I didn't know where to look to propose a fix. Please let me know how I can help fix this. Thanks.

**Comment by jrafanie** [comment]
I added logging of the request/responses by adding:
`faraday.response :logger`  [here](https://github.com/travis-ci/travis.rb/blob/9b3eb05542e37b99a40ab89c0e861019664c15d7/lib/travis/client/session.rb#L60) locally and captured the output [in this gist](https://gist.github.com/jrafanie/8e5f186f75422d0b39d4)

Even though I initialize the Travis::Client with an `access_token`, the first log.txt request has NO token: 
```
I, [2015-05-13T21:57:12.391132 #58927]  INFO -- : get https://s3.amazonaws.com/archive.travis-ci.org/jobs/62355772/log.txt
D, [2015-05-13T21:57:12.391199 #58927] DEBUG -- request: User-Agent: "Travis/1.7.6 (Mac OS X 10.9.5 like Darwin; Ruby 2.1.6-p336; RubyGems 2.2.3) Faraday/0.9.1 Typhoeus/0.7.1"
Accept: "application/vnd.travis-ci.2+json"
I, [2015-05-13T21:57:12.624508 #58927]  INFO -- Status: 200
```

The second log.txt request has an authorization token and fails with a 400 error:
 
```
I, [2015-05-13T21:57:13.022111 #58927]  INFO -- : get https://s3.amazonaws.com/archive.travis-ci.org/jobs/62355773/log.txt
D, [2015-05-13T21:57:13.022167 #58927] DEBUG -- request: User-Agent: "Travis/1.7.6 (Mac OS X 10.9.5 like Darwin; Ruby 2.1.6-p336; RubyGems 2.2.3) Faraday/0.9.1 Typhoeus/0.7.1"
Authorization: "token MY_TOKEN"
Accept: "application/vnd.travis-ci.2+json"
I, [2015-05-13T21:57:13.045683 #58927]  INFO -- Status: 400
```

So, it appears something is failing to clear the Authorization  header on the subsequent requests.

**Comment by jrafanie** [comment]
It looks like travis is calling
`request.headers.delete("Authorization")` [here](https://github.com/travis-ci/travis.rb/blob/9b3eb05542e37b99a40ab89c0e861019664c15d7/lib/travis/client/session.rb#L208)
in both the successful and unsuccessful log.txt request.

In the unsuccessful case,  the ivar `@names` hash keys don't match the actual header hash's keys.  Therefore, this condition in `delete` is false and the actual header Authorization field is not removed:

`if k = @names[k.downcase]` [here](https://github.com/lostisland/faraday/blob/81f16593a0138ec58bb6f25e1c2804e91589662f/lib/faraday/utils.rb#L57)

For example:
`@names.keys`: ["user-agent", "accept"]
`self.keys`: ["User-Agent", "Authorization", "Accept"]

**Comment by jrafanie** [comment]
Opened a PR on faraday to fix this issue: https://github.com/lostisland/faraday/pull/478

**Comment by jrafanie** [comment]
Closing.  This monkey patch from [the faraday PR](https://github.com/lostisland/faraday/pull/478) before my travis.rb code fixes the issue for me:

```ruby
require 'faraday/utils'

module Faraday
  module Utils
    class Headers < ::Hash
      # on dup/clone, we need to duplicate @names hash
      def initialize_copy(other)
        super
        @names = @names.dup
      end
    end
  end
end
```

**Comment by jrafanie** [comment]
cc @BanzaiMan @rkh  (you might be interested in this workaround in case others hit it)
