### ISSUE TITLE
Verification failed on setup releases

### ISSUE THREAD

**Issue by inventor02** [travis-ci/travis.rb#298]
When I run the command 'travis setup releases', the client throws a RuntimeError: Validation Failed error.

```
System
Ruby:                     Ruby 2.0.0-p481
Operating System:         Mac OS X 10.10.3
RubyGems:                 RubyGems 2.0.14

CLI
Version:                  1.7.7
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-05-29 18:00:09 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "inventor02"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis setup --org`:
    RuntimeError: Validation Failed
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/tools/github.rb:208:in `basic_auth'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/tools/github.rb:221:in `login'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/tools/github.rb:49:in `each_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/tools/github.rb:36:in `with_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/cli/setup/releases.rb:12:in `block in run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/cli/setup/service.rb:61:in `block in deploy'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/cli/setup/service.rb:52:in `configure'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/cli/setup/service.rb:60:in `deploy'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/cli/setup/releases.rb:11:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/cli/setup.rb:54:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/cli/command.rb:198:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/lib/travis/cli.rb:64:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.7.7/bin/travis:18:in `<top (required)>'
        from /usr/bin/travis:23:in `load'
        from /usr/bin/travis:23:in `<main>'
```

**Comment by rdhyee** [comment]
Me too:

error.log:

```
An error occurred running `travis setup --org`:
    RuntimeError: Validation Failed
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/tools/github.rb:208:in `basic_auth'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/tools/github.rb:221:in `login'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/tools/github.rb:49:in `each_token'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/tools/github.rb:36:in `with_token'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/cli/setup/releases.rb:12:in `block in run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/cli/setup/service.rb:61:in `block in deploy'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/cli/setup/service.rb:52:in `configure'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/cli/setup/service.rb:60:in `deploy'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/cli/setup/releases.rb:11:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/cli/setup.rb:54:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.2.0/gems/travis-1.7.7/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'
```

my environment:

```
System
Ruby:                     Ruby 2.2.2-p95
Operating System:         Mac OS X 10.9.5
RubyGems:                 RubyGems 2.4.5

CLI
Version:                  1.7.7
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-06-24 14:56:27 -0700

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "rdhyee"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

I checked that my password is correct.  When I type a bad password, I get a "Bad credentials" error instead of "Validation Failed".

**Comment by rdhyee** [comment]
Actually, I'm finding discussion at https://github.com/travis-ci/travis.rb/issues/199 helpful.

**Comment by BanzaiMan** [comment]
Closing this as a duplicate.
