### ISSUE TITLE
travis encrypt -r fails with 795: unexpected token at ''

### ISSUE THREAD

**Issue by JasonGross** [travis-ci/travis.rb#306]
``` sh-session
$ travis encrypt -r JasonGross/masters-thesis "OAUTH_TOKEN=test"
795: unexpected token at ''
for a full error report, run travis report
$ travis report
System
Ruby:                     Ruby 2.0.0-p247
Operating System:         Debian 6.0.10
RubyGems:                 RubyGems 2.0.3

CLI
Version:                  1.8.0
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2015-07-15 15:19:03 -0400

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis encrypt`:
    MultiJson::LoadError: 795: unexpected token at ''
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/2.0.0/json/common.rb:155:in `parse'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/2.0.0/json/common.rb:155:in `parse'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/multi_json-1.7.9/lib/multi_json/adapters/json_common.rb:16:in `load'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/multi_json-1.7.9/lib/multi_json/adapter.rb:19:in `load'
                from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/multi_json-1.7.9/lib/multi_json.rb:118:in `load'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/response.rb:35:in `initialize'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/remote.rb:153:in `new'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/remote.rb:153:in `modify'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/remote.rb:73:in `generate_response'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/normalizer.rb:8:in `generate_response'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/parallel.rb:27:in `generate_response'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/remote.rb:88:in `request'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/gh-0.13.0/lib/gh/remote.rb:106:in `head'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/repo_command.rb:111:in `detect_api_endpoint'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/repo_command.rb:23:in `setup'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/command.rb:197:in `execute'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
        from /afs/csail.mit.edu/u/j/jgross/.local64/lib/ruby/gems/2.0.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
        from /afs/csail.mit.edu/u/j/jgross/.local64/bin/travis:23:in `load'
        from /afs/csail.mit.edu/u/j/jgross/.local64/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by BanzaiMan** [comment]
Somehow the HEAD request to `https://api.travis-ci.org/repos/JasonGross/masters-thesis` returned something `gh` did not understand.

I'm closing this optimistically since a lot has changed since this was initially reported.
