### ISSUE TITLE
Travis installation seems failed

### ISSUE THREAD

**Issue by liudonghua123** [travis-ci/travis.rb#311]
I installed with `gem install travis -v 1.8.0 --no-rdoc --no-ri` command, and it did not shown any errors. But when I tried `travis version`, it gave me the errors below.

```
LiudonghuadeMacBook-Air:xiaozizi_blog liudonghua$ travis version
private method `load' called for Psych:Module
for a full error report, run travis report
LiudonghuadeMacBook-Air:xiaozizi_blog liudonghua$ 
LiudonghuadeMacBook-Air:xiaozizi_blog liudonghua$ 
LiudonghuadeMacBook-Air:xiaozizi_blog liudonghua$ travis report
/Users/liudonghua/.rvm/gems/ruby-2.1.5/gems/travis-1.8.0/lib/travis/cli/api_command.rb:150:in `default_endpoint': undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/liudonghua/.rvm/gems/ruby-2.1.5/gems/travis-1.8.0/lib/travis/cli/api_command.rb:154:in `detected_endpoint'
    from /Users/liudonghua/.rvm/gems/ruby-2.1.5/gems/travis-1.8.0/lib/travis/cli/api_command.rb:70:in `detected_endpoint?'
    from /Users/liudonghua/.rvm/gems/ruby-2.1.5/gems/travis-1.8.0/lib/travis/cli/api_command.rb:158:in `endpoint_option'
    from /Users/liudonghua/.rvm/gems/ruby-2.1.5/gems/travis-1.8.0/lib/travis/cli/command.rb:213:in `rescue in execute'
    from /Users/liudonghua/.rvm/gems/ruby-2.1.5/gems/travis-1.8.0/lib/travis/cli/command.rb:191:in `execute'
    from /Users/liudonghua/.rvm/gems/ruby-2.1.5/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
    from /Users/liudonghua/.rvm/gems/ruby-2.1.5/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
    from /Users/liudonghua/.rvm/gems/ruby-2.1.5/bin/travis:23:in `load'
    from /Users/liudonghua/.rvm/gems/ruby-2.1.5/bin/travis:23:in `<main>'
    from /Users/liudonghua/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    from /Users/liudonghua/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
LiudonghuadeMacBook-Air:xiaozizi_blog liudonghua$ 
LiudonghuadeMacBook-Air:xiaozizi_blog liudonghua$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
LiudonghuadeMacBook-Air:xiaozizi_blog liudonghua$
```

**Comment by ptrhlm** [comment]
`gem uninstall psych`
helped in my case. More info: [https://github.com/bbatsov/rubocop/issues/1510#issuecomment-83545184](https://github.com/bbatsov/rubocop/issues/1510#issuecomment-83545184)
