### ISSUE TITLE
undefined method `receive' in 'travis logs'

### ISSUE THREAD

**Issue by wkoszek** [travis-ci/travis.rb#322]
Hello,

I have a problem with command-line program "travis" failing.

Travis:

```
wk:/w/repos/docker_edu> travis version
1.8.0
```

Repository:

```
git clone https://github.com/wkoszek/docker_edu
```

I run:

```
travis restart
wait 10s
travis logs
```

<wait>

The output is as follows:
```
100a3d8684fafd5616ce54570ac530783f88b53d5141c096bb58649f281f86ce
** Storing "/Users/wk/.travis/error.log"
undefined method `receive' for nil:NilClass
for a full error report, run travis report --org
```

Output from `travis report --org`:

```
System
Ruby:                     Ruby 2.0.0-p481
Operating System:         Mac OS X 10.10.5
RubyGems:                 RubyGems 2.0.14

CLI
Version:                  1.8.0
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2015-09-29 23:40:43 -0700

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "wkoszek"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `receive' for nil:NilClass
        from /Library/Ruby/Gems/2.0.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:206:in `block in connect_internal'
        from /Library/Ruby/Gems/2.0.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `loop'
        from /Library/Ruby/Gems/2.0.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `connect_internal'
        from /Library/Ruby/Gems/2.0.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:76:in `connect'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/listener.rb:123:in `listen'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/methods.rb:90:in `listen'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/artifact.rb:54:in `body'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/logs.rb:39:in `display_log'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/logs.rb:23:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/command.rb:198:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
        from /usr/bin/travis:23:in `load'
        from /usr/bin/travis:23:in `<main>'
```

**Comment by harningt** [comment]
Identical issue encountered on Linux with exactly the same stack trace (although with the path slightly adjusted for ruby 2.1.0 gems in my home directory vs system.

Other relevant bits:
```
System
Ruby:                     Ruby 2.1.6-p336
Operating System:         Ubuntu 15.04
RubyGems:                 RubyGems 2.2.3

CLI
Version:                  1.8.0
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2015-10-02 00:17:12 -0400

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "harningt"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `receive' for nil:NilClass
        from /home/harningt/.gem/ruby/2.1.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:206:in `block in connect_internal'
```
