### ISSUE TITLE
travis setup releases should always set on.tags to true

### ISSUE THREAD

**Issue by FlorianFranzen** [travis-ci/travis.rb#329]
The travis documentation states:

> Please note that deploying GitHub Releases works only for tags, not for branches.

Therefore I is unclear to me why on.tags is not set to true after running `travis setup releases` as the generated config will always fail on untagged commits:

```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.1.1/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/neurosuite/libcbsdk/releases: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: Release
  code: missing_field
  field: tag_name
  resource: Release
  code: custom
  field: tag_name
  message: tag_name is not well-formed
  resource: Release
  code: custom
  message: Published releases must have a valid tag // See: https://developer.github.com/v3/repos/releases/#create-a-release
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.1.1/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.1.1/lib/octokit/middleware/follow_redirects.rb:61:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.1.1/lib/octokit/connection.rb:154:in `request'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.1.1/lib/octokit/connection.rb:28:in `post'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.1.1/lib/octokit/client/releases.rb:32:in `create_release'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/provider/releases.rb:99:in `push_app'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/provider.rb:143:in `block in deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/cli.rb:41:in `fold'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/provider.rb:143:in `deploy'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/cli.rb:32:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/lib/dpl/cli.rb:7:in `run'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.6/bin/dpl:5:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
    from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy 
```

**Comment by BanzaiMan** [comment]
Some workflows do not require `tags: true`, and the documentation reflects this now.
