### ISSUE TITLE
Is it possible to avoid using FFI?

### ISSUE THREAD

**Issue by powerman** [travis-ci/travis.rb#337]
Is there any way to use travis command without loading ffi gem?
Problem is in https://github.com/ffi/ffi/issues/77 - I don't like to disable PaX MPROTECT for /usr/bin/ruby20 binary just to use travis cli.

**Comment by powerman** [comment]
```
$ .gem/ruby/2.0.0/bin/travis
/home/powerman/.gem/ruby/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:263:in `attach': <JUNK> (RuntimeError)
	from /home/powerman/.gem/ruby/2.0.0/gems/ffi-1.9.10/lib/ffi/library.rb:263:in `attach_function'
	from /home/powerman/.gem/ruby/2.0.0/gems/ethon-0.8.0/lib/ethon/libc.rb:16:in `<module:Libc>'
	from /home/powerman/.gem/ruby/2.0.0/gems/ethon-0.8.0/lib/ethon/libc.rb:6:in `<module:Ethon>'
	from /home/powerman/.gem/ruby/2.0.0/gems/ethon-0.8.0/lib/ethon/libc.rb:1:in `<top (required)>'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/powerman/.gem/ruby/2.0.0/gems/ethon-0.8.0/lib/ethon.rb:10:in `<top (required)>'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/powerman/.gem/ruby/2.0.0/gems/typhoeus-0.8.0/lib/typhoeus.rb:2:in `<top (required)>'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/powerman/.gem/ruby/2.0.0/gems/faraday-0.9.2/lib/faraday/middleware.rb:14:in `dependency'
	from /home/powerman/.gem/ruby/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb:10:in `<class:Typhoeus>'
	from /home/powerman/.gem/ruby/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb:3:in `<class:Adapter>'
	from /home/powerman/.gem/ruby/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb:2:in `<module:Faraday>'
	from /home/powerman/.gem/ruby/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb:1:in `<top (required)>'
	from /home/powerman/.gem/ruby/2.0.0/gems/typhoeus-0.8.0/lib/typhoeus/adapters/faraday.rb:18:in `<class:Adapter>'
	from /home/powerman/.gem/ruby/2.0.0/gems/typhoeus-0.8.0/lib/typhoeus/adapters/faraday.rb:4:in `<module:Faraday>'
	from /home/powerman/.gem/ruby/2.0.0/gems/typhoeus-0.8.0/lib/typhoeus/adapters/faraday.rb:3:in `<top (required)>'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/powerman/.gem/ruby/2.0.0/gems/travis-1.8.0/lib/travis/client/session.rb:10:in `<top (required)>'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/powerman/.gem/ruby/2.0.0/gems/travis-1.8.0/lib/travis/client.rb:8:in `<top (required)>'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/powerman/.gem/ruby/2.0.0/gems/travis-1.8.0/lib/travis/cli.rb:2:in `<top (required)>'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib64/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /home/powerman/.gem/ruby/2.0.0/gems/travis-1.8.0/bin/travis:7:in `<top (required)>'
	from .gem/ruby/2.0.0/bin/travis:23:in `load'
	from .gem/ruby/2.0.0/bin/travis:23:in `<main>'
```
