### ISSUE TITLE
Errors with travis compile

### ISSUE THREAD

**Issue by Muffo** [travis-ci/travis.rb#341]
I am trying to run `travis compile` on my Ubuntu VM, but I am running into the following two issues:

```
➜  openssl git:(master) travis compile
no implicit conversion of String into Integer
for a full error report, run travis report
➜  openssl git:(master) travis report 
System
Ruby:                     Ruby 2.1.5-p273
Operating System:         Ubuntu 15.10
RubyGems:                 RubyGems 2.0.3

CLI
Version:                  1.8.0
Plugins:                  "travis-build"
Auto-Completion:          yes
Last Version Check:       2015-12-05 11:07:44 +0000

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "Muffo"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis compile`:
    TypeError: no implicit conversion of String into Integer
        from /home/muffo/.travis/travis-build/init.rb:62:in `[]'
        from /home/muffo/.travis/travis-build/init.rb:62:in `sanitize_global_env'
        from /home/muffo/.travis/travis-build/init.rb:25:in `run'
        from /home/muffo/.gem/ruby/2.1.0/gems/travis-1.8.0/lib/travis/cli/command.rb:198:in `execute'
        from /home/muffo/.gem/ruby/2.1.0/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
        from /home/muffo/.gem/ruby/2.1.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
➜  openssl git:(master) travis compile 1 
undefined method `jobs' for nil:NilClass
for a full error report, run travis report
➜  openssl git:(master) travis report   
System
Ruby:                     Ruby 2.1.5-p273
Operating System:         Ubuntu 15.10
RubyGems:                 RubyGems 2.0.3

CLI
Version:                  1.8.0
Plugins:                  "travis-build"
Auto-Completion:          yes
Last Version Check:       2015-12-05 11:07:44 +0000

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "Muffo"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis compile`:
    NoMethodError: undefined method `jobs' for nil:NilClass
        from /home/muffo/.travis/travis-build/init.rb:56:in `set_up_config'
        from /home/muffo/.travis/travis-build/init.rb:17:in `run'
        from /home/muffo/.gem/ruby/2.1.0/gems/travis-1.8.0/lib/travis/cli/command.rb:198:in `execute'
        from /home/muffo/.gem/ruby/2.1.0/gems/travis-1.8.0/lib/travis/cli.rb:64:in `run'
        from /home/muffo/.gem/ruby/2.1.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

Have I missed something in the installation?

**Comment by BanzaiMan** [comment]
Please open an issue in travis-ci/travis/ci, along with `.travis.yml`. Thank you.

**Comment by Muffo** [comment]
Will do!
Thanks
