### ISSUE TITLE
Travis monitor just says "end of file reached", does not display anything

### ISSUE THREAD

**Issue by larsbergstrom** [travis-ci/travis.rb#353]
```
[larsberg@lbergstrom servo]$ travis monitor
end of file reached
for a full error report, run travis report
[larsberg@lbergstrom servo]$ travis report
System
Ruby:                     Ruby 2.3.0-p0
Operating System:         Mac OS X 10.11.2
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.1
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2016-01-07 09:25:11 -0600

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "larsbergstrom"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis monitor`:
    EOFError: end of file reached
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:178:in `sysread_nonblock'
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:178:in `read_nonblock'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/websocket.rb:71:in `receive'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:206:in `block in connect_internal'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `loop'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `connect_internal'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:76:in `connect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.1/lib/travis/client/listener.rb:123:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.1/lib/travis/client/methods.rb:90:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.1/lib/travis/cli/api_command.rb:143:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.1/lib/travis/cli/monitor.rb:103:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.1/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.1/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.1/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
[larsberg@lbergstrom servo]$ 
```

**Comment by nr-nd** [comment]
I am running into this behavior as well; I will look further into it as time allows.

**Comment by dd1994** [comment]
+1, I meet the same

**Comment by BanzaiMan** [comment]
Hello. I have released version 1.8.2, which adds a new flag (`--debug-http`) for debugging HTTP connexions that we make. My hope is that this flag will give us insight into this issue. Please try adding this flag to problematic commands to see what the underlying issue might be.

**Please note that this command may potentially expose sensitive data, so please do be careful when you paste the output publicly.**

Thank you!

**Comment by larsbergstrom** [comment]
No change in output for me with this new command. Thanks for looking into this, and definitely let me know if there's anything I can do to help!

```
[larsberg@lbergstrom servo]$ travis monitor --debug-http
end of file reached
for a full error report, run travis report
[larsberg@lbergstrom servo]$ travis report
System
Ruby:                     Ruby 2.3.0-p0
Operating System:         Mac OS X 10.11.2
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.2
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2016-01-12 07:18:07 -0600

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "larsbergstrom"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis monitor`:
    EOFError: end of file reached
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:178:in `sysread_nonblock'
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/openssl/buffering.rb:178:in `read_nonblock'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/websocket.rb:71:in `receive'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:206:in `block in connect_internal'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `loop'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `connect_internal'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:76:in `connect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/listener.rb:123:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/methods.rb:90:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/api_command.rb:147:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/monitor.rb:103:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
[larsberg@lbergstrom servo]$ 
```

**Comment by BanzaiMan** [comment]
Ah, I see. `travis monitor` uses the Pusher client, so that flag does not take effect. I'll investigate further.

**Comment by nr-nd** [comment]
I used `git bisect` a few days ago, and ran into this issue for every single commit from latest back until the commit that added `travis monitor`. That doesn't really seem to make sense though, so I'm wondering if I didn't reinstall dependencies correctly for each commit (although I thought I did). Nevertheless, I figured I'd let you know that I tried finding the bad commit, but was unable to pinpoint any specific one (unless the monitor command never worked, which I highly doubt).

**Comment by BanzaiMan** [comment]
I need to do some more work to get HTTP debug info. Sorry about that.

**Comment by nr-nd** [comment]
No apologies necessary. Thanks for looking into this further!

**Comment by BanzaiMan** [comment]
Enabling http debugging output as I originally intended turned out to be ineffective, actually. :-/

```
$ travis monitor
I, [2016-01-13T09:21:37.597156 #13499]  INFO -- : head https://api.travis-ci.org/
D, [2016-01-13T09:21:37.597308 #13499] DEBUG -- request: User-Agent: "Travis/1.8.2 (Mac OS X 10.10.5 like Darwin; Ruby 2.1.5-p273; RubyGems 2.4.3) Faraday/0.9.2 Typhoeus/0.8.0"
Accept: "application/vnd.travis-ci.2+json"
I, [2016-01-13T09:21:39.405262 #13499]  INFO -- Status: 200
D, [2016-01-13T09:21:39.405403 #13499] DEBUG -- response: Connection: "keep-alive"
Server: "nginx"
⋮
I, [2016-01-13T09:21:40.119137 #13499]  INFO -- : get https://api.travis-ci.org/users/
D, [2016-01-13T09:21:40.119197 #13499] DEBUG -- request: User-Agent: "Travis/1.8.2 (Mac OS X 10.10.5 like Darwin; Ruby 2.1.5-p273; RubyGems 2.4.3; command monitor) Faraday/0.9.2 Typhoeus/0.8.0"
Accept: "application/vnd.travis-ci.2+json"
Authorization: "token ******"
I, [2016-01-13T09:21:40.224796 #13499]  INFO -- Status: 200
D, [2016-01-13T09:21:40.225030 #13499] DEBUG -- response: Connection: "keep-alive"
Server: "nginx"
Date: "Wed, 13 Jan 2016 14:21:40 GMT"
Content-Type: "application/json;charset=utf-8"
Content-Length: "7578"
Status: "200 OK"
Access-Control-Allow-Origin: "*"
Access-Control-Allow-Credentials: "true"
Access-Control-Expose-Headers: "Content-Type, Cache-Control, Expires, Etag, Last-Modified"
Strict-Transport-Security: "max-age=31536000"
X-Endpoint: "Travis::Api::App::Endpoint::Users"
X-Pattern: "/"
X-Oauth-Scopes: "public,private"
X-Accepted-Oauth-Scopes: "private"
Vary: "Accept,Authorization,Accept-Encoding"
Cache-Control: "private"
X-Rack-Cache: "miss"
Via: "1.1 vegur"
end of file reached
for a full error report, run travis report
```

So I'm back to square one.

**Comment by nr-nd** [comment]
Hmm, has the Pusher client been updated recently? I'm wondering if it's erroring out due to some update with that code...

**Comment by BanzaiMan** [comment]
The latest Pusher client is 0.6.2, released last May. https://rubygems.org/gems/pusher-client

**Comment by nr-nd** [comment]
Hmm, so I am currently running `travis monitor` with Pusher v0.6.0 installed, and, although I am not getting any 'live' output, the program does not error-out as it did with Pusher v0.6.2 like above.

**Comment by nr-nd** [comment]
Of course, maybe this behavior is due to Pusher silently catching IOErrors, which seems to have been fixed with the following [commit](https://github.com/pusher-community/pusher-websocket-ruby/commit/e91561f955bd72f86b4ba759655560c4c05dda73) (which is in v0.6.1 and v0.6.2).

So maybe there is something in between openssl and Pusher that is failing, but not sure what exactly at the moment.

**Comment by cscott** [comment]
I figured it out -- the travis *server side* API broke recently: it is returning `key` as the pusher API key instead of `5df8ac576dcccf4fd076` (the actual travis API key for pusher).  This is causing the pusher connection to fail.  On my node client, I see:
```
Error { type: 'WebSocketError',
  error: 'Could not find app by key key. Perhaps you\'re connecting to the wrong cluster.' }
```
from the node pusher-client package.  So this isn't really a client problem, it's a travis server side problem.  I'm going to try to figure out where the right place to report those is.

**Comment by cscott** [comment]
Filed https://github.com/travis-ci/travis-ci/issues/6002 upstream.  You can work around the issue temporarily by checking whether the pusher api key is `"key"` and if so replacing it with `5df8ac576dcccf4fd076`.

**Comment by nr-nd** [comment]
Nice find! It seems to sort of fix the issue.
Now I'm at least seeing:
> Monitoring travis-ci.org:

when I run `travis monitor` on a locally changed copy (change the following line)
[lib/travis/client/listener.rb#L177](https://github.com/travis-ci/travis.rb/blob/master/lib/travis/client/listener.rb#L177):
`session.config.fetch('pusher').fetch('key')`
to
`5df8ac576dcccf4fd076`

The monitoring does not seem to be working, but still, fixing this on Travis CI's end should help the cli program from erroring out.

**Comment by 0atman** [comment]
Still erroring for me.

```
$ travis monitor
 end of file reached
for a full error report, run travis report
```

```
$ travis report
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Arch rolling
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.2
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2016-06-03 10:57:18 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "0atman"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)
pro:                      https://api.travis-ci.com/ (access token)
```

**Comment by duxet** [comment]
still broken :(

```
⨯ travis monitor
end of file reached
for a full error report, run travis report
```

```
⨯ travis report
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Mac OS X 10.11.5
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.2
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2016-07-13 08:30:10 +0200

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "duxet"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)
pro:                      https://api.travis-ci.com/ (access token)

Last Exception
An error occurred running `travis monitor`:
    EOFError: end of file reached
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:178:in `sysread_nonblock'
        from /usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/openssl/buffering.rb:178:in `read_nonblock'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/websocket.rb:71:in `receive'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:206:in `block in connect_internal'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `loop'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `connect_internal'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:76:in `connect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/listener.rb:123:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/methods.rb:90:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/api_command.rb:147:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/monitor.rb:103:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'
```

**Comment by nyarly** [comment]
I get no output from `travis monitor` after "Monitoring <repo>" - not "end of file".

```
travis monitor -r opentable/sous --debug
** Loading "/home/judson/.travis/config.yml"
** GET "repos/opentable/sous"
**   took 0.38 seconds
** Using notifications: LibNotify
** GET "config"
**   took 0.38 seconds
Monitoring opentable/sous:

 ⮀ travis report
System
Ruby:                     Ruby 2.3.4-p301
Operating System:         Linux
RubyGems:                 RubyGems 2.6.10

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-07-05 15:10:24 -0700

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "nyarly"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)
```

**Comment by jchamber904** [comment]
@larsbergstrom Are you still having this issue?  I'm not able to reproduce it.

**Comment by larsbergstrom** [comment]
Nope, thanks!
