### ISSUE TITLE
Can't get example of Travis.listen to work 

### ISSUE THREAD

**Issue by adriaanlabusc** [travis-ci/travis.rb#360]
Hi, 

I'm having trouble using the listen api. I basically copied the below code from the docs. I run it, then restart a build from the web interface, and expect to see build started and finished events printed to the terminal. Instead I get the error shown below the snippet after a minute or two. Am I doing something wrong?

Thanks for your time.

```ruby
gem 'travis', '= 1.8.2'
require 'travis'  

Travis.access_token = "secret token"
repo = Travis::Repository.find('account/repo')

Travis.listen(repo) do |stream|
  stream.on('build:started', 'build:finished') do |event|	
  	puts event.inspect
  end
end
```

The error:

```
/Users/adriaan/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/openssl/buffering.rb:182:in `sysread_nonblock': end of file reached (EOFError)
	from /Users/adriaan/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/openssl/buffering.rb:182:in `read_nonblock'
	from /Users/adriaan/.rvm/gems/ruby-2.1.0/gems/pusher-client-0.6.2/lib/pusher-client/websocket.rb:71:in `receive'
	from /Users/adriaan/.rvm/gems/ruby-2.1.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:206:in `block in connect_internal'
	from /Users/adriaan/.rvm/gems/ruby-2.1.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `loop'
	from /Users/adriaan/.rvm/gems/ruby-2.1.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `connect_internal'
	from /Users/adriaan/.rvm/gems/ruby-2.1.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:76:in `connect'
	from /Users/adriaan/.rvm/gems/ruby-2.1.0/gems/travis-1.8.2/lib/travis/client/listener.rb:123:in `listen'
	from /Users/adriaan/.rvm/gems/ruby-2.1.0/gems/travis-1.8.2/lib/travis/client/methods.rb:90:in `listen'
	from ./listen_test2.rb:15:in `<main>'
```

**Comment by tdaff** [comment]
Looks like this is the same thing as issue #353.
