### ISSUE TITLE
cli will not run when proxy is blocking rubygems.org

### ISSUE THREAD

**Issue by jasonwbarnett** [travis-ci/travis.rb#379]
How to reproduce:

1. Remove ~/.travis, e.g. `rm -rf ~/.travis`
1. Run travis, e.g. `travis help`

Sidenote: `travis version` works, but no other commands.

You will see error: 

```
$ travis help
undefined method `split' for nil:NilClass
for a full error report, run travis report

$ cat ~/.travis/error.log
An error occurred running `travis help`:
    NoMethodError: undefined method `split' for nil:NilClass
        from /home/jwb/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/tools/system.rb:10:in `recent_version?'
        from /home/jwb/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/cli/command.rb:161:in `check_version'
        from /home/jwb/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/cli/command.rb:195:in `execute'
        from /home/jwb/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/travis-1.7.7/lib/travis/cli.rb:64:in `run'
        from /home/jwb/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/travis-1.7.7/bin/travis:18:in `<top (required)>'
        from /home/jwb/.rbenv/versions/2.2.3/bin/travis:23:in `load'
        from /home/jwb/.rbenv/versions/2.2.3/bin/travis:23:in `<main>'
```

**Comment by CarltonHenderson** [comment]
Also happens if rubygems.org is down. (Like it was for some tens of minutes just a few minutes ago)
