### ISSUE TITLE
gem install fails: ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by tugberkugurlu** [travis-ci/travis.rb#391]
When I run `sudo gem install travis`, I get the below error:

```
Fetching: multipart-post-2.0.0.gem (100%)
Fetching: faraday-0.9.2.gem (100%)
Fetching: faraday_middleware-0.10.0.gem (100%)
Fetching: highline-1.7.8.gem (100%)
Fetching: backports-3.6.8.gem (100%)
Fetching: multi_json-1.11.2.gem (100%)
Fetching: addressable-2.4.0.gem (100%)
Fetching: net-http-persistent-2.9.4.gem (100%)
Fetching: net-http-pipeline-1.0.1.gem (100%)
Fetching: gh-0.14.0.gem (100%)
Fetching: launchy-2.4.3.gem (100%)
Fetching: ffi-1.9.10.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing travis:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:4:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.10 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/ffi-1.9.10/ext/ffi_c/gem_make.out
```

More info:

```
tugberk@ubuntu:~/Downloads$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

tugberk@ubuntu:~/Downloads$ gem --version
1.8.23
```

any thoughts?

**Comment by tugberkugurlu** [comment]
After installing the below stuff, it started working:

```
$ sudo apt-get install python-software-properties
$ sudo apt-add-repository ppa:brightbox/ruby-ng
$ sudo apt-get update
$ sudo apt-get install ruby2.1 ruby-switch
$ sudo ruby-switch --set ruby2.1
$ sudo apt-get install ruby2.1-dev
```

**Comment by Mokto** [comment]
Thanks man !

**Comment by nolanlawson** [comment]
This worked for me on Bash on Windows as well. The `sudo apt-get install ruby2.1-dev` is key for building the native extensions apparently.

**Comment by gakyoo** [comment]
Worked for me too

**Comment by BrianTerry** [comment]
Worked! Thanks!

**Comment by cahkene** [comment]
thanks bro, this is worked

**Comment by big-kahuna-burger** [comment]
Thanks, it worked in Bash for Windows

**Comment by orpheus** [comment]
`sudo apt-get install ruby-dev`

worked for me

**Comment by seelaman** [comment]
+1 on just ruby-dev

**Comment by dineshsonachalam** [comment]
> sudo apt-get install ruby-dev

Worked for me. Thanks.

**Comment by nomadster** [comment]
You need to install ruby-dev AND build-essentials
```bash
sudo apt-get install ruby-dev
sudo apt-get install build-essential
```

**Comment by pavelkomarov** [comment]
I needed `ruby-dev` and `libz-dev`

**Comment by VladRose** [comment]
Mac OS: `brew install travis`
