### ISSUE TITLE
Validation Failed

### ISSUE THREAD

**Issue by ray26** [travis-ci/travis.rb#394]
`Last Exception
An error occurred running `travis setup --org`:
    RuntimeError: Validation Failed
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:208:in `basic_auth'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:221:in `login'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:49:in `each_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:36:in `with_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/setup/releases.rb:12:in `block in run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/setup/service.rb:61:in `block in deploy'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/setup/service.rb:52:in `configure'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/setup/service.rb:60:in `deploy'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/setup/releases.rb:11:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/setup.rb:55:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'`

**# System information**
`System
Ruby:                     Ruby 2.0.0-p648
Operating System:         Mac OS X 10.11.5
RubyGems:                 RubyGems 2.0.14.1

CLI
Version:                  1.8.2
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2016-04-30 08:34:29 +0800

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)`

**Comment by derekparker** [comment]
I get the same error when running `travis setup releases`.

**Comment by davemachado** [comment]
Duplicate of Issue #359

**Comment by ellson** [comment]
I get the same problem on Fedora-23:

mldt:graphviz (master)$ travis login
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: ellson
Password for ellson: ****************
Successfully logged in as ellson!
mldt:graphviz (master)$ travis setup releases --force
Username: ellson
Password for ellson: ****************
Validation Failed
for a full error report, run travis report --org
mldt:graphviz (master)$

**Comment by ellson** [comment]
Problem is apparently fixed in the latest pre-release of travis.  which may be 1.8.3 
but "travis version" doesn't think so:

$ gem install travis --pre
Successfully installed travis-1.8.3.travis.745.4
Parsing documentation for travis-1.8.3.travis.745.4
Done installing documentation for travis after 1 seconds
1 gem installed
$ travis version
1.8.2

**Comment by davemachado** [comment]
any update on the pre-release? I'm not familiar with Travis' pre-release
work.

**Comment by ellson** [comment]
All I know is that I found the reference to the pre-release here:

      https://github.com/travis-ci/travis.rb#installation

**Comment by davemachado** [comment]
Can sometimes get `travis setup releases` to "complete," but nothing actually gets set up. Reading through the above reference does not assure me that this issue is resolved in next pre-release.
