### ISSUE TITLE
Issues with fresh install

### ISSUE THREAD

**Issue by funkymonkeymonk** [travis-ci/travis.rb#402]
I'm having some issues with a fresh install of travis on OSX. I can't seem to login or perform any function.

```
user@host$ travis login
/usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.0/lib/travis/client/session.rb:221:in `raw': 406: "" (Travis::Client::Error)
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.0/lib/travis/client/session.rb:330:in `check_ssl'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.0/lib/travis/client/session.rb:40:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.0/lib/travis/client.rb:36:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.0/lib/travis/client.rb:36:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.0/lib/travis/cli/api_command.rb:37:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.0/lib/travis/cli/parser.rb:36:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.0/lib/travis/cli/parser.rb:36:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.0/lib/travis/cli.rb:62:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:22:in `load'
	from /usr/local/bin/travis:22:in `<main>'
```

I have tried using gem version 1.8.0/1.8.1/1.8.2. I've also used both the native and brew versions of ruby. My current gem list for dependencies is below.

```
addressable (2.4.0)
backports (3.6.8)
faraday (0.9.2)
faraday_middleware (0.10.0)
gh (0.14.0)
highline (1.7.8)
launchy (2.4.3)
pry (0.9.12.6)
pusher-client (0.6.2)
typhoeus (0.8.0)
```

I'm currently trying to dive into the session object to get an idea as to what is happening.

**Comment by funkymonkeymonk** [comment]
Diving deeper into this it seems a 406 code is returned by the API, and that's the error message I'm seeing.

```
user@host$ curl -X HEAD -I http://api.travis-ci.org/
HTTP/1.1 406 Not Acceptable
Connection: keep-alive
Server: nginx
Date: Tue, 07 Jun 2016 22:06:53 GMT
Content-Type: text/html
Content-Length: 172
Via: 1.1 vegur
```

I'm getting the same result for GET as well so I'm not sure if this is the API is currently not working properly or if these are invalid verbs. The current API status is green on the status page.

**Comment by davemachado** [comment]
Also having the same problem. in `travis report --pro`, https://api.travis-ci.com/ says that i am logged in successfully, but when trying to run` travis setup releases`, `Validation Failed` is thrown.

**Comment by funkymonkeymonk** [comment]
I tried the curl command again today and it looks like it works as expected. I'm guessing this was an API problem that didn't make it to the status page.

I'll leave the issue open as it may be worth asking if there is a better error message that could have been thrown, as I had to pull apart the code to figure out what was going on. It may be worth catching the 406 error and returning something clear saying that a 406 was returned from the API and to check if the API is down.

**Comment by davemachado** [comment]
Still receiving this error as of 11:50PM EST:
```
Last Exception
An error occurred running `travis setup --pro`:
    RuntimeError: Validation Failed
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/tools/github.rb:208:in `basic_auth'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/tools/github.rb:221:in `login'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/tools/github.rb:49:in `each_token'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/tools/github.rb:36:in `with_token'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/cli/setup/releases.rb:12:in `block in run'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/cli/setup/service.rb:61:in `block in deploy'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/cli/setup/service.rb:52:in `configure'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/cli/setup/service.rb:60:in `deploy'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/cli/setup/releases.rb:11:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/cli/setup.rb:55:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/1.9.1/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by davemachado** [comment]
This seems to be a duplicate of Issue #394

**Comment by apanzerj** [comment]
arg. this is because of crazy. They must have changed their api at some point because before their api client was doing this:

```ruby
[requires and stuff]
module Travis
  module Client
    class Session
      PRIMITIVE   = [nil, false, true]
      SSL_OPTIONS = { :ca_file => Tools::Assets['cacert.pem'] }

      include Methods
      attr_reader :connection, :headers, :access_token, :instruments, :faraday_adapter, :agent_info, :ssl
      attr_accessor :debug_http

      def initialize(options = Travis::Client::ORG_URI)
        @headers         = {}
        @cache           = {}
        @instruments     = []
        @agent_info      = []
        @config          = nil
        @faraday_adapter = defined?(Typhoeus) ? :typhoeus : :net_http
        @ssl             = false #SSL_OPTIONS

        options = { :uri => options } unless options.respond_to? :each_pair
        options.each_pair { |key, value| public_send("#{key}=", value) }

        raise ArgumentError, "neither :uri nor :connection specified" unless connection
        headers['Accept'] = 'application/vnd.travis-ci.2+json'
        set_user_agent
        check_ssl
      end
```

Notice the header set for Accept? 

If you change that to:

        headers['Accept'] = 'text/json'

It should work.

**Comment by apanzerj** [comment]
Let's see what breaks...https://github.com/travis-ci/travis.rb/pull/404

**Comment by jahunt1** [comment]
Still seems to be an issue. I have 2-factor authentication enabled on my GitHub account which may or may not be part of the problem. 
```
➜  my-repo git:(master) ✗ travis login
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: jahunt1
Password for jahunt1: ******
Two-factor authentication code for jahunt1: 558084
Validation Failed
for a full error report, run travis report
➜  my-repo git:(master) ✗ travis report
System
Ruby:                     Ruby 2.0.0-p648
Operating System:         Mac OS X 10.12.1
RubyGems:                 RubyGems 2.0.14.1

CLI
Version:                  1.8.4
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2016-11-17 12:47:17 -0700

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis login`:
    RuntimeError: Validation Failed
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/lib/travis/tools/github.rb:208:in `basic_auth'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/lib/travis/tools/github.rb:214:in `rescue in basic_auth'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/lib/travis/tools/github.rb:208:in `basic_auth'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/lib/travis/tools/github.rb:221:in `login'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/lib/travis/tools/github.rb:49:in `each_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/lib/travis/tools/github.rb:36:in `with_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/lib/travis/cli/login.rb:31:in `login'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/lib/travis/cli/login.rb:40:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/lib/travis/cli/command.rb:198:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/lib/travis/cli.rb:64:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.4/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by OmgImAlexis** [comment]
Not sure if this is related but I'm getting this.

```
> travis login --org
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: OmgImAlexis
Password for OmgImAlexis: *************************
Two-factor authentication code for OmgImAlexis: 000000
Successfully logged in as OmgImAlexis!
Two-factor authentication code for OmgImAlexis: 000000
Two-factor authentication code for OmgImAlexis: 000000
```

**Comment by Cryptophobia** [comment]
Travis CI is turning into garbage with this login bullshit.

**Comment by JuniorSfeir** [comment]
This issue still persists unfortunately.
Logging in with a github token was however successful

`travis login --github-token <token>`

[https://github.com/settings/tokens](url)
