### ISSUE TITLE
undefined method `this'  in ruby 2.3

### ISSUE THREAD

**Issue by prdx** [travis-ci/travis.rb#405]
Hi guys!

I got this error after running travis:

step:

```
ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

gem install travis

travis login
```

error:
```
/home/bulan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x122d458 travis-1.8.2> (NoMethodError)
        from /home/bulan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /home/bulan/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /home/bulan/.rvm/gems/ruby-2.3.1/gems/travis-1.8.2/bin/travis:7:in `<top (required)>'
        from /home/bulan/.rvm/gems/ruby-2.3.1/bin/travis:23:in `load'
        from /home/bulan/.rvm/gems/ruby-2.3.1/bin/travis:23:in `<main>'
        from /home/bulan/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/bulan/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

However it works fine if I use ruby 2.1

**Comment by snoopdouglas** [comment]
Getting the same problem here. Any command (including simply running `travis` with no args) fails with the above error.

**Comment by seivan** [comment]
Yeah, I got this to. 

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/lolcat/.rvm/gems/ruby-2.3.1
  - USER INSTALLATION DIRECTORY: /Users/lolcat/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/lolcat/.rvm/rubies/ruby-2.3.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/lolcat/.rvm/gems/ruby-2.3.1/bin
  - SPEC CACHE DIRECTORY: /Users/lolcat/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/lolcat/.rvm/rubies/ruby-2.3.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/lolcat/.rvm/gems/ruby-2.3.1
     - /Users/lolcat/.rvm/gems/ruby-2.3.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :benchmark => false
     - "gem" => "--no-ri --no-rdoc"
     - "gemcutter_key" => "********************************"
     - :sources => ["http://gemcutter.org", "http://gems.github.com"]
  - REMOTE SOURCES:
     - http://gemcutter.org
     - http://gems.github.com
  - SHELL PATH:
     - /Users/lolcat/.rvm/gems/ruby-2.3.1/bin
     - /Users/lolcat/.rvm/gems/ruby-2.3.1@global/bin
     - /Users/lolcat/.rvm/rubies/ruby-2.3.1/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/lolcat/.rvm/bin
     - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```

**Comment by renee-travisci** [comment]
Hi All,
  Are you able to install a later patch version for Ruby 2.3.1? It seems there is an issue with the 112 patch for ruby 2.3.1 that's causing this. If not, could you try a reinstall of that version and let us know if the error goes away?
Thanks!
**Renée

**Comment by seivan** [comment]
I reinstalled Ruby 2.3.1 with the same patch level (112) and somehow it works now.
rvm reinstall ruby-2.3.1   

Thanks @renee-travisci

**Comment by renee-travisci** [comment]
@seivan Great! I'm glad it's working for you! 

I'm going to close this thread. Please re-open if anyone continues to have this problem after upgrade or reinstall.

Thanks!

**Comment by jedrekdomanski** [comment]
This solution didn't work for me.
> ruby -v # ruby2-3.0

**Comment by jedrekdomanski** [comment]
> gem update --system
It worked for me
