### ISSUE TITLE
Pyinvoke:  TypeError: Tasks must have an initial Context argument!  

### ISSUE THREAD

**Issue by assem-ch** [travis-ci/travis.rb#409]
Hi, I used pyinvoke as my taskmanager, all comands work fine for  me on desktop but when I added it to travis, it didnt work giving me this error:
> TypeError: Tasks must have an initial Context argument!  

```
$ invoke download
Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 269, in run
    self._parse(argv)
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 325, in _parse
    self.load_collection()
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 473, in load_collection
    coll = loader.load(coll_name) if coll_name else loader.load()
  File "/usr/local/lib/python2.7/dist-packages/invoke/loader.py", line 53, in load
    module = imp.load_module(name, fd, path, desc)
  File "/home/travis/build/ioGrow/iogrowCRM/tasks.py", line 24, in <module>
    @task(default=True)
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 303, in inner
    autoprint=autoprint,
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 58, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 149, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 144, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument!
The command "invoke download" failed and exited with 1 during .
```

**Comment by BanzaiMan** [comment]
Hello. Could you explain why you think this is an issue with the Travis CLI client?

**Comment by assem-ch** [comment]
It may not be an issue but a special configuration, Why there is no initial Context argument?

**Comment by BanzaiMan** [comment]
That is a Python error, and we don't use Python at all in the CLI.
