### ISSUE TITLE
Travis Pro: Intermittently receiving 'Invalid Auth Token'

### ISSUE THREAD

**Issue by dueckes** [travis-ci/travis.rb#410]
**Background**
I'm a maintainer of [build_eval](https://github.com/MYOB-Technology/build_eval), a project that combines the status of multiple builds from multiple sources, for display on build-lights and other radiators.

**Issue**
travis gem version: 1.8.2
Ruby version: 2.3.1

Requests issued to Travis Pro appear to be failing intermittently with the following error:

`Travis::Client::NotLoggedIn: invalid access token
/Users/matthew.ueckerman/.rvm/gems/ruby-1.9.3-p551/gems/travis-1.8.2/lib/travis/client/session.rb:221:in `raw'
/Users/matthew.ueckerman/.rvm/gems/ruby-1.9.3-p551/gems/travis-1.8.2/lib/travis/client/session.rb:190:in `post_raw'`

I'm intermittently experiencing this error both when attempting to authenticate via `github_auth` and when retrieving `recent_builds`.

When I say intermittently, occasionally requests succeed, but they predominantly fail.

I have attempted to work around this by using the `Travis::Client::Session` directly, to no avail.

I notice other issues mention that request / rate limiting may be in effect.
Could you confirm if this is the case?

Note that I have not experienced this issue for requests to Travis Org - it is only effecting Travis Pro.

**Comment by baccenfutter** [comment]
I had this too. Apparently this happens on outages such as this:

**Comment by baccenfutter** [comment]
I ran into this issue as well. Apparently this happens during outages of the Github authentication API. Had it all day yesterday, today all is good. Then I caught the RSS of the Github authentication outage. Time-frames matched.

The error message one is left with is more then misleading. The real bug here is that the application should catch the case of an unavailable or unreachable API and format the error message accordingly.
