### ISSUE TITLE
login fails all the time

### ISSUE THREAD

**Issue by ducin** [travis-ci/travis.rb#421]
I've installed 

```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x64-mingw32]
```

and the newest version of travis: `1.8.2`. I try to login to travis and I fail the same way, whether I do:
- travis login
- travis login --auto
- travis login --github-token

I run it from windows x64 under `git bash` shell.

```
Tomasz.Ducin@WAWLT548 MINGW64 ~/.ssh
$ travis login --github-token
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/session.rb:221:in `raw': invalid access token (Travis::Client::NotLoggedIn)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/session.rb:333:in `check_ssl'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/session.rb:41:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client.rb:36:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client.rb:36:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/api_command.rb:41:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/parser.rb:36:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/parser.rb:36:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli.rb:62:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
        from C:/Ruby23-x64/bin/travis:23:in `load'
        from C:/Ruby23-x64/bin/travis:23:in `<main>'
```

got no idea what is wrong. But it seems not windows-related.

**Comment by vincent-ogury** [comment]
same here :

```
travis init
/usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/session.rb:221:in `raw': invalid access token (Travis::Client::NotLoggedIn)
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/session.rb:333:in `check_ssl'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/session.rb:41:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client.rb:36:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client.rb:36:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/api_command.rb:41:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/parser.rb:36:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/parser.rb:36:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli.rb:62:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:23:in `load'
	from /usr/local/bin/travis:23:in `<main>'
```

or

```
travis login
/usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/session.rb:221:in `raw': invalid access token (Travis::Client::NotLoggedIn)
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/session.rb:333:in `check_ssl'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client/session.rb:41:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client.rb:36:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/client.rb:36:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/api_command.rb:41:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/parser.rb:36:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli/parser.rb:36:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/travis/cli.rb:62:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:23:in `load'
	from /usr/local/bin/travis:23:in `<main>'
```

same with --pro

```
travis version
1.8.2
```

**Comment by vincent-ogury** [comment]
This one fix the problem it seems :

**Comment by ducin** [comment]
but it's not merged and not available in the gem _yet_?

**Comment by vincent-ogury** [comment]
it seems not. I have edit directly my current installed files. this fix the problem of login for good.

I'm able to login and encrypt env

**Comment by dholdaway** [comment]
i contacted support and they sent me reply stating.

 

> I'm
> 
>  sorry to hear your are having trouble using our CLI.
> 
> This issue might be related to being blocked from using our API. 
> Could you please go to https://api.travis-ci.org/v3/ ? And let us know what do you see.
> 
> That being said, do you have some automated script(s) accessing this particular URL?
> 
> Or are you, by any chance, using the travis-ci-status package for Atom? This package already caused this kind of behaviour in the past.
> 
> Let me know if this particular API request rings a bell on your side or not and we will follow-up upon your 
> 
>  reply.

i was using the atom the plugin. once i removed that and it started working....

**Comment by jcasner** [comment]
I managed to get my account working again by going to https://github.com/settings/tokens and deleting the temporary token associated with github pro. I was then able to login again.
