### ISSUE TITLE
Playing with Travis CLI blocks IP, can't login on web

### ISSUE THREAD

**Issue by ujovlado** [travis-ci/travis.rb#425]
Looks like after few failed login attempts from Travis CLI my IP is blocked. Can't login at all.

From CLI I'm getting error:
```
/usr/local/bundle/gems/travis-1.8.2/lib/travis/client/session.rb:221:in `raw': invalid access token (Travis::Client::NotLoggedIn)
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/client/session.rb:333:in `check_ssl'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/client/session.rb:41:in `initialize'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/client.rb:36:in `new'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/client.rb:36:in `new'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/cli/api_command.rb:41:in `initialize'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/cli/parser.rb:36:in `new'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/cli/parser.rb:36:in `new'
	from /usr/local/bundle/gems/travis-1.8.2/lib/travis/cli.rb:62:in `run'
	from /usr/local/bundle/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
	from /usr/local/bundle/bin/travis:22:in `load'
	from /usr/local/bundle/bin/travis:22:in `<main>'
```
From web:

```
Request URL:https://api.travis-ci.org/auth/post_message?origin=https://travis-ci.org
Request Method:GET
Status Code:403 Forbidden
```

**Comment by ujovlado** [comment]
Closing the issue, looks like I'm no longer blocked.
