### ISSUE TITLE
Can't retrieve config from enterprise api

### ISSUE THREAD

**Issue by rjsamson** [travis-ci/travis.rb#429]
I've been trying to get the cli working with our new Travis enterprise setup and I'm running into some issues with SSL. Based on the output when I run the CLI with --explode it looks like it's it's having issues with SSL even with --insecure - I keep getting `Could not verify peer`. Here's the output of `travis login -X --exlplode`

```
/Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:216:in `raw': SSL error: could not verify peer (Travis::Client::SSLError)
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:186:in `get_raw'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:134:in `config'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/api_command.rb:126:in `load_gh'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/login.rb:45:in `github'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/login.rb:31:in `login'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/login.rb:40:in `run'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
	from /Users/robertsamson/.gem/ruby/2.3.1/bin/travis:23:in `load'
	from /Users/robertsamson/.gem/ruby/2.3.1/bin/travis:23:in `<main>'
```

I've also tried switching adapters which all result in errors. Using net/http actually gives me a 404 for some reason (it looks like when using net/http it just tried to get '/config' instead of the fqdn/config). Here's the output of `travis login -X --adapter net-http --explode`

```
/Users/robertsamson/.rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:120:in `error!': 404 "Not found" (Faraday::ConnectionFailed)
	from /Users/robertsamson/.rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:129:in `value'
	from /Users/robertsamson/.rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:920:in `connect'
	from /Users/robertsamson/.rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /Users/robertsamson/.rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /Users/robertsamson/.rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	from /Users/robertsamson/.rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1156:in `get'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:209:in `public_send'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:209:in `block in raw'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:276:in `block in instrumented'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:277:in `block in instrumented'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:278:in `instrumented'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:207:in `raw'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:186:in `get_raw'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:134:in `config'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/api_command.rb:126:in `load_gh'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/login.rb:45:in `github'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/login.rb:31:in `login'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/login.rb:40:in `run'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
	from /Users/robertsamson/.gem/ruby/2.3.1/bin/travis:23:in `load'
	from /Users/robertsamson/.gem/ruby/2.3.1/bin/travis:23:in `<main>'
```

And using excon gives me a similar SSL error to the default tyhpoeus adapter - `travis login -X --adapter excon --explode`

```
/Users/robertsamson/.gem/ruby/2.3.1/gems/excon-0.51.0/lib/excon/ssl_socket.rb:127:in `connect': SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol (OpenSSL::SSL::SSLError) (Faraday::ConnectionFailed)
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/excon-0.51.0/lib/excon/ssl_socket.rb:127:in `initialize'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/excon-0.51.0/lib/excon/connection.rb:404:in `new'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/excon-0.51.0/lib/excon/connection.rb:404:in `socket'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/excon-0.51.0/lib/excon/connection.rb:106:in `request_call'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/excon-0.51.0/lib/excon/middlewares/mock.rb:47:in `request_call'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/excon-0.51.0/lib/excon/middlewares/instrumentor.rb:25:in `request_call'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/excon-0.51.0/lib/excon/middlewares/base.rb:15:in `request_call'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/excon-0.51.0/lib/excon/middlewares/base.rb:15:in `request_call'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/excon-0.51.0/lib/excon/middlewares/base.rb:15:in `request_call'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/excon-0.51.0/lib/excon/connection.rb:250:in `request'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/adapter/excon.rb:55:in `call'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:209:in `public_send'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:209:in `block in raw'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:276:in `block in instrumented'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:277:in `block in instrumented'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:278:in `instrumented'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:207:in `raw'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:186:in `get_raw'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/client/session.rb:134:in `config'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/api_command.rb:126:in `load_gh'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/login.rb:45:in `github'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/login.rb:31:in `login'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/login.rb:40:in `run'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
	from /Users/robertsamson/.gem/ruby/2.3.1/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
	from /Users/robertsamson/.gem/ruby/2.3.1/bin/travis:23:in `load'
	from /Users/robertsamson/.gem/ruby/2.3.1/bin/travis:23:in `<main>'
```

I should mention that yes, I am on a corporate network and we've got our own certs since they MITM all the traffic - however, `--insecure` is supposed to ignore any ssl errors, right?

Thanks!

**Comment by rjsamson** [comment]
This turned out to be an issue with an internal proxy here - closing.
