### ISSUE TITLE
Setup - Validation Failed

### ISSUE THREAD

**Issue by SiNEXiST** [travis-ci/travis.rb#432]
Hi. As I was trying to setup releases deployment using "travis setup releases" it gives me a login which always fails. I use the same credentials as in the login command and on github but it still denies it.

Stacktrace / Report:
```
System
Ruby:                     Ruby 2.3.0-p0
Operating System:         Windows
RubyGems:                 RubyGems 2.5.1

CLI
Version:                  1.8.2
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       never

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis setup --org`:
    RuntimeError: Validation Failed
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/tools/github.rb:216:in `rescue in basic_auth'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/tools/github.rb:208:in `basic_auth'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/tools/github.rb:221:in `login'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/tools/github.rb:80:in `possible_tokens'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/tools/github.rb:49:in `each_token'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/tools/github.rb:36:in `with_token'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/cli/setup/releases.rb:12:in `block in run'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/cli/setup/service.rb:61:in `block in deploy'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/cli/setup/service.rb:52:in `configure'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/cli/setup/service.rb:60:in `deploy'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/cli/setup/releases.rb:11:in `run'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/cli/setup.rb:55:in `run'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/cli/command.rb:198:in `execute'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/lib/tra
vis/cli.rb:64:in `run'
        from C:/Program Files/Ruby/lib/ruby/gems/2.3.0/gems/travis-1.8.2/bin/tra
vis:18:in `<top (required)>'
        from C:/Program Files/Ruby/bin/travis:23:in `load'
        from C:/Program Files/Ruby/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci
/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or
 email support@travis-ci.com.
```

**Comment by SiNEXiST** [comment]
Sorry, duplication of [#359](https://github.com/travis-ci/travis.rb/issues/359)
