### ISSUE TITLE
encrypt-file is not working for me

### ISSUE THREAD

**Issue by Grawl** [travis-ci/travis.rb#435]
Ruby version: `2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]`

Gem version: `2.0.14.1`

Travis CLI version: `1.8.2`

``` bash
$ travis encrypt-file key
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- multi_json (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/response.rb:2:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/remote.rb:153:in `modify'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/remote.rb:74:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/normalizer.rb:8:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/parallel.rb:27:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/remote.rb:89:in `request'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/remote.rb:107:in `head'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/repo_command.rb:120:in `detect_api_endpoint'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/repo_command.rb:22:in `setup'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/encrypt_file.rb:50:in `setup'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/command.rb:197:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
    from /usr/local/bin/travis:23:in `load'
    from /usr/local/bin/travis:23:in `<main>'
```

I tried to login but with no luck too:

``` bash
$ travis login --auto
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- multi_json (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/backports-3.6.8/lib/backports/std_lib.rb:9:in `require_with_backports'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/response.rb:2:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/remote.rb:153:in `modify'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/remote.rb:74:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/normalizer.rb:8:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/parallel.rb:27:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:87:in `generate_response'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/wrapper.rb:82:in `[]'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/instrumentation.rb:24:in `block in []'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/instrumentation.rb:30:in `instrument'
    from /Library/Ruby/Gems/2.0.0/gems/gh-0.14.0/lib/gh/instrumentation.rb:24:in `[]'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:231:in `acceptable?'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:49:in `block in each_token'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:261:in `security'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:195:in `github_for_mac_token'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:67:in `possible_tokens'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:49:in `each_token'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/tools/github.rb:36:in `with_token'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/login.rb:31:in `login'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/login.rb:40:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
    from /usr/local/bin/travis:23:in `load'
    from /usr/local/bin/travis:23:in `<main>'
```

Also I faced an issue with `cannot load such file -- addressable/uri (LoadError)` and [installed an older version of `addressable`](https://github.com/travis-ci/travis.rb/issues/342#issuecomment-164376647):

``` bash
$ gem uninstall  addressable

You have requested to uninstall the gem:
    addressable-2.3.8

gh-0.14.0 depends on addressable (>= 0)
launchy-2.4.3 depends on addressable (~> 2.3)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]
Successfully uninstalled addressable-2.3.8
$ gem install -v2.3.8 addressable
Fetching: addressable-2.3.8.gem (100%)
Successfully installed addressable-2.3.8
1 gem installed
```

**Comment by BanzaiMan** [comment]
Please try a recent version, and if it persists, open a new issue.

Thanks.
