### ISSUE TITLE
`travis setup releases` generates token with inadequate scope

### ISSUE THREAD

**Issue by mdb** [travis-ci/travis.rb#438]
In attempting to to configure TravisCI [automated GitHub releases uploading](https://docs.travis-ci.com/user/deployment/releases) for a GitHub organization repo, `travis setup releases` generates a `automatic releases for organization-name/repo-name` access token with a seemingly inadequate scope of `public_repo`. In effect, this results in the following when a TravisCI build attempts to upload a release to GitHub:

```
Preparing deploy
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/connection.rb:19:in `get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/client/users.rb:34:in `user'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:43:in `user'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:68:in `setup_auth'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:72:in `check_auth'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider.rb:132:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/provider.rb:131:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.18/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy```

Visiting `Settings > Personal Access Tokens` and editing `automatic releases for organization-name/repo-name` to have a broader access scope seems to resolve this.

**Comment by Joshua-Anderson** [comment]
Are you on `.com` with a private repository? Ideally travis would notice that it's on .com and request `repo` instead of `public_repo`.

The travis team doesn't seem to be actively updating the client though, so a fix may not be coming soon.

**Comment by mdb** [comment]
@Joshua-Anderson Thanks for the fast response! I'm using non-enterprise, public `travis-ci.org` and a public, open source `github.com` repository.

**Comment by Joshua-Anderson** [comment]
Hmmm. This actually looks like a dpl bug: 

```
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
```

The dpl tries to access your username and gets permission denied. Was `user` ,the permission you added to make it work? You don't need any permissions to access username, so maybe octokit has changed and requires a different technique to get a token owners username.

**Comment by mdb** [comment]
@Joshua-Anderson I added `repo` scope to make the token work. Prior to my manual edit, the token generated by `travis setup releases` only had `public_repo` scope.

**Comment by rvhuang** [comment]
Same issue happens again and the error stacktrace seems exactly same as OP's.

**Comment by andreasmuelder** [comment]
same here

**Comment by MaxNoe** [comment]
Also for me

**Comment by yukota** [comment]
This problem is occurred in my environment.
In my case, I used https://travis-ci.com/(not https://travis-ci.org/) .
I should execute ```travis setup releases --pro```, not just ```travis setup releases``` without options.
