### ISSUE TITLE
travis setup releases fails

### ISSUE THREAD

**Issue by jeabakker** [travis-ci/travis.rb#443]
After using `travis setup releases --force` many time successfully today it fails every time.

I ran `travis setup releases --force --debug`:

>** Loading "C:/Users/user/.travis/config.yml"
** Faraday::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
** Loading gh
** GET "config"
**   took 0.44 seconds
** GitHub API: HEAD /repos/ColdTrick/ckeditor_extended
**   took 0.43 seconds
** GET "repos/ColdTrick/ckeditor_extended"
**   took 0.46 seconds
** GET "config"
**   took 0.45 seconds
Username: myusername
Password for myusername: ********
** GitHub API: POST /authorizations
Two-factor authentication code for myusername: code
** GitHub API: POST /authorizations
** Storing "C:/Users/user/.travis/error.log"
Validation Failed
for a full error report, run travis report --org

Looks like a certificate error occured

**Comment by jeabakker** [comment]
result of `travis report --org`

```text
System
Ruby:                     Ruby 2.1.5-p273
Operating System:         Windows
RubyGems:                 RubyGems 2.2.2

CLI
Version:                  1.7.5
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       never

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis setup --org`:
    RuntimeError: Validation Failed
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/tools/github.rb:216:in `rescue in basic_auth'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/tools/github.rb:208:in `basic_auth'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/tools/github.rb:214:in `rescue in basic_auth'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/tools/github.rb:208:in `basic_auth'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/tools/github.rb:221:in `login'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/tools/github.rb:80:in `possible_tokens'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/tools/github.rb:49:in `each_token'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/tools/github.rb:36:in `with_token'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/cli/setup/releases.rb:12:in `block in run'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/cli/setup/service.rb:61:in `block in deploy'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/cli/setup/service.rb:52:in `configure'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/cli/setup/service.rb:60:in `deploy'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/cli/setup/releases.rb:11:in `run'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/cli/setup.rb:54:in `run'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/cli/command.rb:198:in `execute'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/lib/travis/cli.rb:64:in `run'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/travis-1.7.5/bin/travis:18:in `<top (required)>'
        from C:/Ruby21-x64/bin/travis:23:in `load'
        from C:/Ruby21-x64/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by maxep** [comment]
Travis tries to generate a new personal access token with the same description, you can go to your github [settings](https://github.com/settings/tokens) and remove the existing token called `automatic releases for ...`

I guess `travis.rb` could first check if the token exist before creating it.

**Comment by jeabakker** [comment]
removing the token helped. I now added releases support. Thank you!
