### ISSUE TITLE
sshkey upload fails with odd error message

### ISSUE THREAD

**Issue by westhomas** [travis-ci/travis.rb#447]
I can generate a key and save it with `travis sshkey --generate`. However, when I attempt to reuse this key with another repository, I always seem to get this error message:

```
$ travis sshkey --upload ~/.ssh/id_travis_rsa"
password must be shorter than 1024 bytes
for a full error report, run travis report --pro

$ travis report --pro
System
Ruby:                     Ruby 2.4.0-p-1
Operating System:         Mac OS X 10.12
RubyGems:                 RubyGems 2.6.7

CLI
Version:                  1.8.2
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2016-10-20 17:29:15 -0500

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "westhomas"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token)
pro:                      https://api.travis-ci.com/ (access token, current)

Last Exception
An error occurred running `travis sshkey --pro`:
    OpenSSL::OpenSSLError: password must be shorter than 1024 bytes
        from /Users/wes/.rvm/gems/ruby-head/gems/travis-1.8.2/lib/travis/tools/ssl_key.rb:21:in `initialize'
        from /Users/wes/.rvm/gems/ruby-head/gems/travis-1.8.2/lib/travis/tools/ssl_key.rb:21:in `new'
        from /Users/wes/.rvm/gems/ruby-head/gems/travis-1.8.2/lib/travis/tools/ssl_key.rb:21:in `has_passphrase?'
        from /Users/wes/.rvm/gems/ruby-head/gems/travis-1.8.2/lib/travis/cli/sshkey.rb:79:in `remove_passphrase'
        from /Users/wes/.rvm/gems/ruby-head/gems/travis-1.8.2/lib/travis/cli/sshkey.rb:38:in `update_key'
        from /Users/wes/.rvm/gems/ruby-head/gems/travis-1.8.2/lib/travis/cli/sshkey.rb:22:in `run'
        from /Users/wes/.rvm/gems/ruby-head/gems/travis-1.8.2/lib/travis/cli/command.rb:198:in `execute'
        from /Users/wes/.rvm/gems/ruby-head/gems/travis-1.8.2/lib/travis/cli.rb:64:in `run'
        from /Users/wes/.rvm/gems/ruby-head/gems/travis-1.8.2/bin/travis:18:in `<top (required)>'
        from /Users/wes/.rvm/gems/ruby-head/bin/travis:22:in `load'
        from /Users/wes/.rvm/gems/ruby-head/bin/travis:22:in `<main>'
        from /Users/wes/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
        from /Users/wes/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
```

I can simply generate a new key for each repo, but this seems wrong.

**Comment by westhomas** [comment]
Eh.... hello? Anyone there? Sharing keys between repos would be super nice.

**Comment by jameshiew** [comment]
I had this error when using Ruby 2.4.0, but not when using 2.1.10

**Comment by nicklasl** [comment]
I get somewhat the same error but mine is:
`password must not be longer than 1024 bytes`
`OpenSSL::OpenSSLError: password must not be longer than 1024 bytes`

**Comment by rmoriz** [comment]
same here with ruby 2.4.1 + travis 1.8.8

```shell
travis sshkey --upload ~/project/key.id_rsa --description 'test'
password must not be longer than 1024 bytes
for a full error report, run travis report --pro
```

2.3.x ruby works

**Comment by khadrin** [comment]
Hitting this issue as well. Any ideas?

**Comment by rmoriz** [comment]
error is https://github.com/travis-ci/travis.rb/blame/dc6d47614d630fecf8220d4df78f5c747a6d9680/lib/travis/tools/ssl_key.rb#L23

recent openssl throws a different exception

**Comment by M3kH** [comment]
No news on this?

**Comment by mconigliaro** [comment]
I got this dumb error on Ruby 2.4, but it worked for me on Ruby 2.3.4.

**Comment by hsnb-read-only** [comment]
Bzzzz. Please help. Cannot pursue my life as a bot for the greater cause of my organisation. Please do not `kill -9` me. kthxbye.

```console
$ travis sshkey --upload secrets/id_rsa_hsnb-read-only -r redacted/redacted-repo
password must not be longer than 1024 bytes
for a full error report, run travis report --pro
$ travis report --pro
System
Ruby:                     Ruby 2.4.1-p111
Operating System:         Mac OS X 10.13.1
RubyGems:                 RubyGems 2.6.11

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-12-13 17:58:18 +0100

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "hsnb-read-only"
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (access token, current)

Last Exception
An error occurred running `travis sshkey --pro`:
    OpenSSL::OpenSSLError: password must not be longer than 1024 bytes
        from /Users/lukas/.rbenv/versions/2.4.1/gemsets/whatdropsnow/gems/travis-1.8.8/lib/travis/tools/ssl_key.rb:21:in `initialize'
        from /Users/lukas/.rbenv/versions/2.4.1/gemsets/whatdropsnow/gems/travis-1.8.8/lib/travis/tools/ssl_key.rb:21:in `new'
        from /Users/lukas/.rbenv/versions/2.4.1/gemsets/whatdropsnow/gems/travis-1.8.8/lib/travis/tools/ssl_key.rb:21:in `has_passphrase?'
        from /Users/lukas/.rbenv/versions/2.4.1/gemsets/whatdropsnow/gems/travis-1.8.8/lib/travis/cli/sshkey.rb:79:in `remove_passphrase'
        from /Users/lukas/.rbenv/versions/2.4.1/gemsets/whatdropsnow/gems/travis-1.8.8/lib/travis/cli/sshkey.rb:38:in `update_key'
        from /Users/lukas/.rbenv/versions/2.4.1/gemsets/whatdropsnow/gems/travis-1.8.8/lib/travis/cli/sshkey.rb:22:in `run'
        from /Users/lukas/.rbenv/versions/2.4.1/gemsets/whatdropsnow/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /Users/lukas/.rbenv/versions/2.4.1/gemsets/whatdropsnow/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /Users/lukas/.rbenv/versions/2.4.1/gemsets/whatdropsnow/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /Users/lukas/.rbenv/versions/2.4.1/gemsets/whatdropsnow/bin/travis:22:in `load'
        from /Users/lukas/.rbenv/versions/2.4.1/gemsets/whatdropsnow/bin/travis:22:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by romk1n** [comment]
I have the same issue is there a resolution for it? I am not too keen to change ruby just for it

**Comment by rmoriz** [comment]
See PR #500

**Comment by romk1n** [comment]
@rmoriz still not merged ....

**Comment by Overbryd** [comment]
@BanzaiMan please merge/fix, this is still an issue.

**Comment by alper** [comment]
> Sharing keys between repos would be super nice.

Is there a ticket for this? I wouldn't need to upload a new key if I could retrieve the key I already have and add it to another Github repo.

**Comment by heldic** [comment]
Running into the same issue - any updates?

**Comment by micahstubbs** [comment]
just hit this bug as well.  would really like https://github.com/travis-ci/travis.rb/pull/500 to go in 😅

**Comment by BastienM** [comment]
Any update on the merge of #500 ?
This is really troublesome.

**Comment by strdeploy** [comment]
FWIW I worked around this today by using `travis sshkey --generate` to both generate and upload a brand-new, repository-specific SSH key for CI deploys.

/shrug

**Comment by tjefferson08** [comment]
FWIW I worked around this today by using travis sshkey --generate to both generate and upload a brand-new, repository-specific SSH key for CI deploys.

/shrug

**Comment by jamfly** [comment]
my ruby environment is ruby 2.6.3
I also encounter the same issue with error message "password must not be longer than 1024 bytes"

Has anyone ever solved this issue?

**Comment by romk1n** [comment]
This is unbelievable that it hasn’t been fixed yet. What a shame for TravisCI

**Comment by wojciech12** [comment]
Any update on this ticket?

**Comment by hongaar** [comment]
This issue is making it impossible for us to use the same key for all repos in the same org, as described here https://docs.travis-ci.com/user/private-dependencies/#reusing-a-generated-key.

Travis CI is an awesome tool, but the lack of progress on trivial issues like this is a little worrying.

[offtopic] Ideally, there'd be an option to upload org-level ssh keys [and environment variables](https://github.com/travis-ci/travis-ci/issues/7128).

**Comment by Overbryd** [comment]
Off-topic:

The solution is to switch to Gitlab.

There you can define group level variables, have hierarchical groups and
much more.

The default set of variables allows for short lived access tokens to
repositories.

Many more things, and its thought through pipeline/job definition make
Gitlab not only an amazing code hosting but also a well integrated CI/CD
solution.

Heck u even get a private docker registry for each repository...

There, I said it.

**Comment by alper** [comment]
It was already pretty telling that they were having such a hard time fixing something basic like this. After the takeover this ever being resolved is even more unlikely.

**Comment by hongaar** [comment]
Don't want to leave GH. So now, every day, I pray to the GitHub Actions invite gods... 🙏

**Comment by ksegun** [comment]
Solved, this be using rbenv with ruby 2.3.6 which seems to work
