### ISSUE TITLE
Cannot login with username/password

### ISSUE THREAD

**Issue by rumpelsepp** [travis-ci/travis.rb#453]
```
System
Ruby:                     Ruby 2.3.2-p217
Operating System:         Arch rolling
RubyGems:                 RubyGems 2.5.2

CLI
Version:                  1.8.4
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2016-11-20 19:44:41 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis login`:
    GH::Error: GH request failed
verb:               :delete
url:                /authorizations/63106368
headers:            {"User-Agent"=>"GH/0.15.0", "Accept"=>"application/vnd.github.v3+json", "Accept-Charset"=>"utf-8", "X-GitHub-OTP"=>"628910"}
error:              Faraday::ClientError: the server responded with status 401
payload:            nil
response_status:    401
response_headers:   {"server"=>"GitHub.com", "date"=>"Sun, 20 Nov 2016 18:45:24 GMT", "content-type"=>"application/json; charset=utf-8", "content-length"=>"160", "connection"=>"close", "status"=>"401 Unauthorized", "x-github-otp"=>"required; sms", "x-github-media-type"=>"github.v3; format=json", "x-ratelimit-limit"=>"60", "x-ratelimit-remaining"=>"58", "x-ratelimit-reset"=>"1479671110", "access-control-expose-headers"=>"ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval", "access-control-allow-origin"=>"*", "content-security-policy"=>"default-src 'none'", "strict-transport-security"=>"max-age=31536000; includeSubdomains; preload", "x-content-type-options"=>"nosniff", "x-frame-options"=>"deny", "x-xss-protection"=>"1; mode=block", "x-github-request-id"=>"5B2271CC:0858:DDCF980:5831EF44"}
response_body:      {"message":"Must specify two-factor authentication OTP code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"}
        from /home/stefan/.gem/ruby/2.3.0/gems/faraday-0.10.0/lib/faraday/response/raise_error.rb:13:in `on_complete'
        from /home/stefan/.gem/ruby/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:9:in `block in call'
        from /home/stefan/.gem/ruby/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:61:in `on_complete'
        from /home/stefan/.gem/ruby/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:8:in `call'
        from /home/stefan/.gem/ruby/2.3.0/gems/faraday-0.10.0/lib/faraday/request/retry.rb:116:in `call'
        from /home/stefan/.gem/ruby/2.3.0/gems/faraday-0.10.0/lib/faraday/request/authorization.rb:38:in `call'
        from /home/stefan/.gem/ruby/2.3.0/gems/faraday-0.10.0/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/stefan/.gem/ruby/2.3.0/gems/faraday-0.10.0/lib/faraday/connection.rb:377:in `run_request'
        from /home/stefan/.gem/ruby/2.3.0/gems/gh-0.15.0/lib/gh/remote.rb:77:in `http'
        from /home/stefan/.gem/ruby/2.3.0/gems/gh-0.15.0/lib/gh/token_check.rb:28:in `http'
        from /home/stefan/.gem/ruby/2.3.0/gems/gh-0.15.0/lib/gh/instrumentation.rb:16:in `block in http'
        from /home/stefan/.gem/ruby/2.3.0/gems/gh-0.15.0/lib/gh/instrumentation.rb:30:in `instrument'
        from /home/stefan/.gem/ruby/2.3.0/gems/gh-0.15.0/lib/gh/instrumentation.rb:16:in `http'
        from /home/stefan/.gem/ruby/2.3.0/gems/gh-0.15.0/lib/gh/remote.rb:84:in `request'
        from /home/stefan/.gem/ruby/2.3.0/gems/gh-0.15.0/lib/gh/remote.rb:100:in `delete'
        from /home/stefan/.gem/ruby/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:223:in `block (2 levels) in login'
        from /home/stefan/.gem/ruby/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:52:in `ensure in each_token'
        from /home/stefan/.gem/ruby/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:52:in `each_token'
        from /home/stefan/.gem/ruby/2.3.0/gems/travis-1.8.4/lib/travis/tools/github.rb:36:in `with_token'
        from /home/stefan/.gem/ruby/2.3.0/gems/travis-1.8.4/lib/travis/cli/login.rb:31:in `login'
        from /home/stefan/.gem/ruby/2.3.0/gems/travis-1.8.4/lib/travis/cli/login.rb:40:in `run'
        from /home/stefan/.gem/ruby/2.3.0/gems/travis-1.8.4/lib/travis/cli/command.rb:198:in `execute'
        from /home/stefan/.gem/ruby/2.3.0/gems/travis-1.8.4/lib/travis/cli.rb:64:in `run'
        from /home/stefan/.gem/ruby/2.3.0/gems/travis-1.8.4/bin/travis:18:in `<top (required)>'
        from /home/stefan/.gem/ruby/2.3.0/bin/travis:22:in `load'
        from /home/stefan/.gem/ruby/2.3.0/bin/travis:22:in `<main>'
```

**Comment by rkh** [comment]
This has been fixed by #454, which you should be able to try out right now via `gem install travis --pre`.
