### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by MitchK** [travis-ci/travis.rb#456]
I have this issue on OSX:

```
$ travis login
/Users/user/.rvm/gems/ruby-2.3.1/gems/ffi-1.9.14/lib/ffi_c.bundle: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0038 p:-17583182697726 s:0171 e:000170 TOP    [FINISH]
c:0037 p:---- s:0169 e:000168 CFUNC  :require
c:0036 p:0115 s:0165 e:000164 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0035 p:0020 s:0155 e:000154 RESCUE /Users/user/.rvm/gems/ruby-2.3.1/gems/ffi-1.9.14/lib/ffi.rb:6
c:0034 p:0099 s:0152 e:000151 TOP    /Users/user/.rvm/gems/ruby-2.3.1/gems/ffi-1.9.14/lib/ffi.rb:3 [FINISH]
c:0033 p:---- s:0150 e:000149 CFUNC  :require
c:0032 p:0115 s:0146 e:000145 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0031 p:0015 s:0136 e:000135 TOP    /Users/user/.rvm/gems/ruby-2.3.1/gems/ethon-0.9.1/lib/ethon.rb:2 [FINISH]
c:0030 p:---- s:0134 e:000133 CFUNC  :require
c:0029 p:0115 s:0130 e:000129 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0028 p:0015 s:0120 e:000119 TOP    /Users/user/.rvm/gems/ruby-2.3.1/gems/typhoeus-0.8.0/lib/typhoeus.rb:2 [FINISH]
c:0027 p:---- s:0118 e:000117 CFUNC  :require
c:0026 p:0115 s:0114 e:000113 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0025 p:0016 s:0104 e:000103 METHOD /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/middleware.rb:14
c:0024 p:0029 s:0099 e:000098 CLASS  /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/adapter/typhoeus.rb:10
c:0023 p:0019 s:0097 e:000096 CLASS  /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/adapter/typhoeus.rb:3
c:0022 p:0011 s:0095 e:000094 CLASS  /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/adapter/typhoeus.rb:2
c:0021 p:0009 s:0093 e:000092 TOP    /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/adapter/typhoeus.rb:1 [FINISH]
c:0020 p:0019 s:0091 e:000090 CLASS  /Users/user/.rvm/gems/ruby-2.3.1/gems/typhoeus-0.8.0/lib/typhoeus/adapters/faraday.rb:18
c:0019 p:0011 s:0089 e:000088 CLASS  /Users/user/.rvm/gems/ruby-2.3.1/gems/typhoeus-0.8.0/lib/typhoeus/adapters/faraday.rb:4
c:0018 p:0017 s:0087 e:000086 TOP    /Users/user/.rvm/gems/ruby-2.3.1/gems/typhoeus-0.8.0/lib/typhoeus/adapters/faraday.rb:3 [FINISH]
c:0017 p:---- s:0085 e:000084 CFUNC  :require
c:0016 p:0115 s:0081 e:000080 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0015 p:0075 s:0071 e:000070 TOP    /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/client/session.rb:10 [FINISH]
c:0014 p:---- s:0069 e:000068 CFUNC  :require
c:0013 p:0115 s:0065 e:000064 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0012 p:0076 s:0055 e:000054 TOP    /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/client.rb:8 [FINISH]
c:0011 p:---- s:0053 e:000052 CFUNC  :require
c:0010 p:0115 s:0049 e:000048 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0009 p:0009 s:0039 e:000038 TOP    /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/cli.rb:2 [FINISH]
c:0008 p:---- s:0036 e:000035 CFUNC  :require
c:0007 p:0115 s:0032 e:000031 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0006 p:0070 s:0022 e:000021 TOP    /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/bin/travis:7 [FINISH]
c:0005 p:---- s:0019 e:000018 CFUNC  :load
c:0004 p:0118 s:0015 E:0005a8 EVAL   /Users/user/.rvm/gems/ruby-2.3.1/bin/travis:23 [FINISH]
c:0003 p:---- s:0011 e:000010 CFUNC  :eval
c:0002 p:0118 s:0005 E:0025d0 EVAL   /Users/user/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15 [FINISH]
c:0001 p:0000 s:0002 E:0000d8 TOP    [FINISH]

/Users/user/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
/Users/user/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/user/.rvm/gems/ruby-2.3.1/bin/travis:23:in `<main>'
/Users/user/.rvm/gems/ruby-2.3.1/bin/travis:23:in `load'
/Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/bin/travis:7:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/cli.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/client.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/client/session.rb:10:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/user/.rvm/gems/ruby-2.3.1/gems/typhoeus-0.8.0/lib/typhoeus/adapters/faraday.rb:3:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.3.1/gems/typhoeus-0.8.0/lib/typhoeus/adapters/faraday.rb:4:in `<module:Faraday>'
/Users/user/.rvm/gems/ruby-2.3.1/gems/typhoeus-0.8.0/lib/typhoeus/adapters/faraday.rb:18:in `<class:Adapter>'
/Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/adapter/typhoeus.rb:1:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/adapter/typhoeus.rb:2:in `<module:Faraday>'
/Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/adapter/typhoeus.rb:3:in `<class:Adapter>'
/Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/adapter/typhoeus.rb:10:in `<class:Typhoeus>'
/Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/middleware.rb:14:in `dependency'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/user/.rvm/gems/ruby-2.3.1/gems/typhoeus-0.8.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/user/.rvm/gems/ruby-2.3.1/gems/ethon-0.9.1/lib/ethon.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/user/.rvm/gems/ruby-2.3.1/gems/ffi-1.9.14/lib/ffi.rb:3:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.3.1/gems/ffi-1.9.14/lib/ffi.rb:6:in `rescue in <top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------

* Loaded script: /Users/user/.rvm/gems/ruby-2.3.1/bin/travis

* Loaded features:

    0 enumerator.so
    1 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/enc/encdb.bundle
    2 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/enc/trans/transdb.bundle
    3 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb
    4 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/compatibility.rb
    5 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/defaults.rb
    6 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/deprecate.rb
    7 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/errors.rb
    8 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb
    9 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/requirement.rb
   10 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/platform.rb
   11 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb
   12 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/exceptions.rb
   13 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
   14 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb
   15 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb
   16 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
   17 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb
   18 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/path_support.rb
   19 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb
   20 /Users/user/.rvm/gems/ruby-2.3.1@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb
   21 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/etc.bundle
   22 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb
   23 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/pathname.bundle
   24 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb
   25 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/errors.rb
   26 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/environment_preserver.rb
   27 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/user_interaction.rb
   28 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/cgi/core.rb
   29 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/cgi/util.rb
   30 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/cgi/cookie.rb
   31 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/cgi.rb
   32 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb
   33 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/generic.rb
   34 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/ftp.rb
   35 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/http.rb
   36 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/https.rb
   37 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/ldap.rb
   38 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/ldaps.rb
   39 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/mailto.rb
   40 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri.rb
   41 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/socket.bundle
   42 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/socket.rb
   43 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/fcntl.bundle
   44 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb
   45 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/digest.bundle
   46 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb
   47 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/openssl.bundle
   48 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/bn.rb
   49 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/cipher.rb
   50 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/stringio.bundle
   51 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/config.rb
   52 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/digest.rb
   53 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/x509.rb
   54 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb
   55 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/ssl.rb
   56 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl.rb
   57 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/securerandom.rb
   58 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/resolv.rb
   59 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/remote_fetcher.rb
   60 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/gem_remote_fetcher.rb
   61 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/digest/sha1.bundle
   62 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/plugin/api/source.rb
   63 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/plugin/api.rb
   64 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/plugin.rb
   65 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/source.rb
   66 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/gem_helpers.rb
   67 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/match_platform.rb
   68 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/rubygems_ext.rb
   69 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/config_file.rb
   70 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/rubygems_integration.rb
   71 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/version.rb
   72 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/constants.rb
   73 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/current_ruby.rb
   74 /Users/user/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler.rb
   75 /Users/user/.rvm/gems/ruby-2.3.1@global/gems/bundler-unload-1.0.2/lib/bundler-unload.rb
   76 /Users/user/.rvm/gems/ruby-2.3.1@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb
   77 /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/client/error.rb
   78 /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/client/states.rb
   79 /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/client/restartable.rb
   80 /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/client/not_loadable.rb
   81 /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/client/has_uuid.rb
   82 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/syntax_error.rb
   83 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/psych.bundle
   84 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/nodes/node.rb
   85 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/nodes/stream.rb
   86 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/nodes/document.rb
   87 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/nodes/sequence.rb
   88 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/nodes/scalar.rb
   89 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/nodes/mapping.rb
   90 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/nodes/alias.rb
   91 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/nodes.rb
   92 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/streaming.rb
   93 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/visitors/visitor.rb
   94 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/strscan.bundle
   95 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/scalar_scanner.rb
   96 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/visitors/to_ruby.rb
   97 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/visitors/emitter.rb
   98 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/visitors/yaml_tree.rb
   99 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/json/ruby_events.rb
  100 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/visitors/json_tree.rb
  101 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/visitors/depth_first.rb
  102 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/visitors.rb
  103 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/handler.rb
  104 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/tree_builder.rb
  105 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/parser.rb
  106 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/omap.rb
  107 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/set.rb
  108 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/coder.rb
  109 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/core_ext.rb
  110 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/date_core.bundle
  111 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/date/format.rb
  112 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/date.rb
  113 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/deprecated.rb
  114 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/stream.rb
  115 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/json/yaml_events.rb
  116 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/json/tree_builder.rb
  117 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/json/stream.rb
  118 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych/handlers/document_stream.rb
  119 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb
  120 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/yaml.rb
  121 /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/client/methods.rb
  122 /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/version.rb
  123 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb
  124 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/forwardable.rb
  125 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/utils.rb
  126 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/options.rb
  127 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/connection.rb
  128 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/rack_builder.rb
  129 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/parameters.rb
  130 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/middleware.rb
  131 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/adapter.rb
  132 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/request.rb
  133 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/response.rb
  134 /Users/user/.rvm/gems/ruby-2.3.1/gems/multipart-post-2.0.0/lib/composite_io.rb
  135 /Users/user/.rvm/gems/ruby-2.3.1/gems/multipart-post-2.0.0/lib/parts.rb
  136 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/upload_io.rb
  137 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/error.rb
  138 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday/autoload.rb
  139 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday-0.10.0/lib/faraday.rb
  140 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday_middleware-0.10.1/lib/faraday_middleware/backwards_compatibility.rb
  141 /Users/user/.rvm/gems/ruby-2.3.1/gems/faraday_middleware-0.10.1/lib/faraday_middleware.rb
  142 /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/tools/system.rb
  143 /Users/user/.rvm/gems/ruby-2.3.1/gems/travis-1.8.4/lib/travis/tools/assets.rb
  144 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/digest/sha2.bundle
  145 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest/sha2.rb
  146 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/logger.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
```

**Comment by BanzaiMan** [comment]
Looks like FFI was corrupt. Try re-installing or updating it. I'm closing this now, since it's 2 years old. Open a new issue if it's still an issue. Thanks.
