### ISSUE TITLE
No Worky in 2.3.1

### ISSUE THREAD

**Issue by kitplummer** [travis-ci/travis.rb#460]
Anyone else seeing this with Ruby 2.3.1?

```
➜  kermit git:(sslserver) travis report --pro
/Users/kplummer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fc1fd551c58 travis-1.8.6.travis.796.4> (NoMethodError)
	from /Users/kplummer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/kplummer/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/kplummer/.rvm/gems/ruby-2.3.1/gems/travis-1.8.6.travis.796.4/bin/travis:7:in `<top (required)>'
	from /Users/kplummer/.rvm/gems/ruby-2.3.1/bin/travis:23:in `load'
	from /Users/kplummer/.rvm/gems/ruby-2.3.1/bin/travis:23:in `<main>'
	from /Users/kplummer/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kplummer/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by BanzaiMan** [comment]
Could you try updating RubyGems?

**Comment by kitplummer** [comment]
That did the trick!  Thanks much.
