### ISSUE TITLE
private method `load' called for nil:NilClass

### ISSUE THREAD

**Issue by mdarmetko** [travis-ci/travis.rb#470]
I'm getting the following error message when attempting to run many travis commands
```
mdarmetko$ travis status
private method `load' called for nil:NilClass
for a full error report, run travis report --pro
```
travis report:
```
System
Ruby:                     Ruby 2.4.0-p0
Operating System:         Mac OS X 10.12.1
RubyGems:                 RubyGems 2.6.8

CLI
Version:                  1.8.5
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-01-06 10:41:24 -0700

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "mdarmetko"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)
pro:                      https://api.travis-ci.com/ (access token)

Last Exception
An error occurred running `travis status --pro`:
    NoMethodError: private method `load' called for nil:NilClass
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.5/lib/travis/cli/repo_command.rb:24:in `setup'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.5/lib/travis/cli/command.rb:197:in `execute'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.5/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.5/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'
```
I did eventually get it working with the -r option to specify the repository name as in
```
mdarmetko$ travis status -r mdarmetko/run-this-town-api
build #26 passed
```
but it took me a good long while to figure out that solution

**Comment by BanzaiMan** [comment]
Happy to see that you were able to find a solution.

Closing as stale. If you see this again, please include `--debug` output.
