### ISSUE TITLE
Getting error as "resource not found" when trying to login to travis using CLI

### ISSUE THREAD

**Issue by pawanks84** [travis-ci/travis.rb#473]
Hello,
I am getting error as "resource not found" when trying to login to travis using command line as given below. Can you please let me know what is the problem here ? 

**travis login --github-token xxxxxxxxxxxxxxxx
resource not found ({"file":"not found"})**

Many thanks in advance !!

**Comment by pawanks84** [comment]
Hello,
Can we have any update on this issue ? This is blocking us. Let me know if you need any other details.

Thanks !!

**Comment by chrisdhanaraj** [comment]
Echoing the same issue here

**Comment by RamakrishnanArun** [comment]
The same when I try to login

```bash
srm-common-java $ travis login -X --github-token <token> --debug --explode
** Loading "/Users/arunrama/.travis/config.yml"
** Timeout::Error: execution expired
** Loading gh
** GET "config"
**   took 0.56 seconds
** GET "https://<host>/api/config"
**   took 1 seconds
** GitHub API: GET /api/v3/user?per_page=100
**   took 1.2 seconds
** POST "auth/github" {:github_token=>"<token>"}
**   took 0.29 seconds
** GET "https://<host>/api/auth/github"
**   took 1.1 seconds
/usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:222:in `raw': {"file":"not found"} (Travis::Client::NotFound)
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:218:in `raw'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:190:in `post_raw'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/methods.rb:20:in `github_auth'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/login.rb:32:in `block in login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:36:in `block in with_token'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:49:in `block in each_token'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:60:in `possible_tokens'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:49:in `each_token'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:36:in `with_token'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/login.rb:31:in `login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/login.rb:40:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:23:in `load'
	from /usr/local/bin/travis:23:in `<main>'
srm-common-java $ 
```

This is our own enterprise deployment of github and travis. I've been able to login before. I updated the gem today and them this happened.
