### ISSUE TITLE
undefined method `receive' for nil:NilClass

### ISSUE THREAD

**Issue by bblacey** [travis-ci/travis.rb#476]
Exception occurred at the conclusion of the job while running travis logs <job.subjob>

```
[blacey@bbl ~/Projects/FreeCAD-MacOS-CI (qt5)]$ travis report --org
System
Ruby:                     Ruby 2.3.3-p222
Operating System:         Mac OS X 10.12.3
RubyGems:                 RubyGems 2.5.2

CLI
Version:                  1.8.5
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-01-19 19:49:25 -0800

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "bblacey"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `receive' for nil:NilClass
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:206:in `block in connect_internal'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `loop'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `connect_internal'
        from /usr/local/lib/ruby/gems/2.3.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:76:in `connect'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/client/listener.rb:123:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/client/methods.rb:90:in `listen'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/client/artifact.rb:54:in `body'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/cli/logs.rb:39:in `display_log'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/cli/logs.rb:23:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.3.0/gems/travis-1.8.5/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by atimmer** [comment]
I have the same issue:
```
System
Ruby:                     Ruby 2.0.0-p648
Operating System:         Mac OS X 10.12.3
RubyGems:                 RubyGems 2.0.14.1

CLI
Version:                  1.8.6
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-02-22 10:24:02 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "atimmer"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)
pro:                      https://api.travis-ci.com/ (access token)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `receive' for nil:NilClass
        from /Library/Ruby/Gems/2.0.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:206:in `block in connect_internal'
        from /Library/Ruby/Gems/2.0.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `loop'
        from /Library/Ruby/Gems/2.0.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `connect_internal'
        from /Library/Ruby/Gems/2.0.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:76:in `connect'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/client/listener.rb:123:in `listen'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/client/methods.rb:90:in `listen'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/client/artifact.rb:54:in `body'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/cli/logs.rb:39:in `display_log'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/cli/logs.rb:23:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/cli/command.rb:198:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/cli.rb:64:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'
```

**Comment by seripap** [comment]
Here as well

```
$ travis report --pro
System
Ruby:                     Ruby 2.0.0-p648
Operating System:         Mac OS X 10.12.3
RubyGems:                 RubyGems 2.0.14.1

CLI
Version:                  1.8.6
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-02-22 13:00:38 -0500

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "seripap"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token)
pro:                      https://api.travis-ci.com/ (access token, default, current)

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `receive' for nil:NilClass
        from /Library/Ruby/Gems/2.0.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:206:in `block in connect_internal'
        from /Library/Ruby/Gems/2.0.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `loop'
        from /Library/Ruby/Gems/2.0.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `connect_internal'
        from /Library/Ruby/Gems/2.0.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:76:in `connect'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/client/listener.rb:123:in `listen'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/client/methods.rb:90:in `listen'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/client/artifact.rb:54:in `body'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/cli/logs.rb:39:in `display_log'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/cli/logs.rb:23:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/cli/command.rb:198:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/lib/travis/cli.rb:64:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.6/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by guyzmo** [comment]
So you know, I'm having the same issue but I'm *NOT* running OSX like all the others above 😀

```
System
Ruby:                     Ruby 2.4.0-p0
Operating System:         Arch rolling
RubyGems:                 RubyGems 2.6.8

CLI
Version:                  1.8.6
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2017-02-24 23:40:05 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `receive' for nil:NilClass
        from /home/guyzmo/.gem/ruby/2.4.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:206:in `block in connect_in
ternal'
        from /home/guyzmo/.gem/ruby/2.4.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `loop'
        from /home/guyzmo/.gem/ruby/2.4.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:205:in `connect_internal'
        from /home/guyzmo/.gem/ruby/2.4.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:76:in `connect'
        from /home/guyzmo/.gem/ruby/2.4.0/gems/travis-1.8.6/lib/travis/client/listener.rb:123:in `listen'
        from /home/guyzmo/.gem/ruby/2.4.0/gems/travis-1.8.6/lib/travis/client/methods.rb:90:in `listen'
        from /home/guyzmo/.gem/ruby/2.4.0/gems/travis-1.8.6/lib/travis/client/artifact.rb:54:in `body'
        from /home/guyzmo/.gem/ruby/2.4.0/gems/travis-1.8.6/lib/travis/cli/logs.rb:39:in `display_log'
        from /home/guyzmo/.gem/ruby/2.4.0/gems/travis-1.8.6/lib/travis/cli/logs.rb:23:in `run'
        from /home/guyzmo/.gem/ruby/2.4.0/gems/travis-1.8.6/lib/travis/cli/command.rb:198:in `execute'
        from /home/guyzmo/.gem/ruby/2.4.0/gems/travis-1.8.6/lib/travis/cli.rb:64:in `run'
        from /home/guyzmo/.gem/ruby/2.4.0/gems/travis-1.8.6/bin/travis:18:in `<top (required)>'
        from /home/guyzmo/bin/travis:22:in `load'
        from /home/guyzmo/bin/travis:22:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by michaelmior** [comment]
Same here. Not sure if this is the case with others, but for me it happens when a build completes while streaming logs.

**Comment by guyzmo** [comment]
yes this is the exact use case. But it's not directly an issue with `travis.rb`, but rather with `pusher` as referenced from the issue I opened on their project.
