### ISSUE TITLE
SSL certificate verification breaks displaying logs

### ISSUE THREAD

**Issue by marpet** [travis-ci/travis.rb#505]
I've problems working with logs too. It seems to be related to SSL certificate. I haven't found any information about this on the internet. And as I saw other logs related issues here I thought this might be an issue of travis too.

This is the report:
```
C:\Users\Marco\Projects\senbox\s3tbx>travis logs
displaying logs for senbox-org/s3tbx#597.1
SSL_connect returned=1 errno=0 state=error: certificate verify failed
for a full error report, run travis report --org

C:\Users\Marco\Projects\senbox\s3tbx>travis report --org
System
Ruby:                     Ruby 2.3.3-p222
Operating System:         Windows
RubyGems:                 RubyGems 2.5.2

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       never

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "marpet"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1398:in `request'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1156:in `get'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:78:in `perform_request'
```

**Comment by ferki** [comment]
Using `travis logs` gives me the following error message:

```
SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
for a full error report, run travis report --pro
```

The output of `travis report --pro` is the following:

```
System
Ruby:                     Ruby 2.5.8-p224
Operating System:         Linux
RubyGems:                 RubyGems 2.7.10

CLI
Version:                  1.8.13
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2020-04-17 16:56:27 +0200

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "ferki"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token)
com:                      https://api.travis-ci.com/ (access token, default, current)

Last Exception
An error occurred running `travis logs --pro`:
    OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
        from /usr/lib64/ruby/gems/2.5.0/gems/pusher-client-0.6.2/lib/pusher-client/websocket.rb:33:in `connect'
        from /usr/lib64/ruby/gems/2.5.0/gems/pusher-client-0.6.2/lib/pusher-client/websocket.rb:33:in `initialize'
        from /usr/lib64/ruby/gems/2.5.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:197:in `new'
        from /usr/lib64/ruby/gems/2.5.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:197:in `connect_internal'
        from /usr/lib64/ruby/gems/2.5.0/gems/pusher-client-0.6.2/lib/pusher-client/socket.rb:76:in `connect'
        from /usr/lib64/ruby/gems/2.5.0/gems/travis-1.8.13/lib/travis/client/listener.rb:123:in `listen'
        from /usr/lib64/ruby/gems/2.5.0/gems/travis-1.8.13/lib/travis/client/methods.rb:94:in `listen'
        from /usr/lib64/ruby/gems/2.5.0/gems/travis-1.8.13/lib/travis/client/artifact.rb:54:in `body'
        from /usr/lib64/ruby/gems/2.5.0/gems/travis-1.8.13/lib/travis/cli/logs.rb:39:in `display_log'
        from /usr/lib64/ruby/gems/2.5.0/gems/travis-1.8.13/lib/travis/cli/logs.rb:23:in `run'
        from /usr/lib64/ruby/gems/2.5.0/gems/travis-1.8.13/lib/travis/cli/command.rb:198:in `execute'
        from /usr/lib64/ruby/gems/2.5.0/gems/travis-1.8.13/lib/travis/cli.rb:64:in `run'
        from /usr/lib64/ruby/gems/2.5.0/gems/travis-1.8.13/bin/travis:18:in `<top (required)>'
        from /usr/bin/travis:9:in `load'
        from /usr/bin/travis:9:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

It works correctly when adding `-I` or `--insecure` to the command.

ps.: the same issue is also true for `travis monitor` for me, so it might actually be a more systematic problem which affects more functionality than just `logs`.
