### ISSUE TITLE
Unable to install travis on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by acastaner** [travis-ci/travis.rb#509]
Using a Windows 10 pro with the Windows Subsystem for Linux (aka "Bash on Windows") I'm unable to install travis. I have followed [these instructions](https://github.com/travis-ci/travis.rb#installation) to install Ruby, which itself works:

```
arnaud@CLAVAIN:/mnt/e/GitHub/acastaner.fr-mvc6$ ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
```

But when I try to install the gem, I get this:

```
arnaud@CLAVAIN:/mnt/e/GitHub/acastaner.fr-mvc6$ sudo gem install travis -v 1.8.8 --no-rdoc --no-ri
[sudo] Mot de passe de arnaud :
Building native extensions.  This could take a while...
ERROR:  Error installing travis:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.18/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20170602-3195-1q3fgc8.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib/ruby/2.3.0/mkmf.rb:587:in `try_cpp'
        from /usr/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
        from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
        from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
        from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
        from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
        from /usr/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
        from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.18/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ffi-1.9.18 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.18/gem_make.out
```

Not sure why it's complaining that I have to install development tools first. I have installed ruby-full as well as make and all the generic Linux development tools.

Is this a problem from Travis? From me? From WSL maybe?

**Comment by AraHaan** [comment]
I think it is from WSL.

**Comment by jspenguin2017** [comment]
Try `apt install make gcc`... Had the same problem today, I don't think it's WSL.

**Comment by tnguyen14** [comment]
I ran into the same problem, and following @jspenguin2017 instructions helped.

```
sudo apt install ruby make gcc
sudo gem install travis
```

**Comment by dudleycodes** [comment]
For Ubuntu 18.04 on WSL I also had to `install ruby-dev`

```shell
sudo apt install ruby ruby-dev make gcc
sudo gem install travis
```

**Comment by Whernog** [comment]
Thank you ! @dudleycodes
