### ISSUE TITLE
travis --version tries to mkdir

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [travis-ci/travis.rb#519]
When running `travis --version` in a read-only directory I get:
```
+ travis --version
/var/lib/gems/1.9.1/gems/travis-1.8.8/lib/travis/cli/command.rb:346:in `mkdir': Permission denied - /.travis (Errno::EACCES)
	from /var/lib/gems/1.9.1/gems/travis-1.8.8/lib/travis/cli/command.rb:346:in `config_path'
	from /var/lib/gems/1.9.1/gems/travis-1.8.8/lib/travis/cli/command.rb:363:in `save_file'
	from /var/lib/gems/1.9.1/gems/travis-1.8.8/lib/travis/cli/command.rb:282:in `store_error'
	from /var/lib/gems/1.9.1/gems/travis-1.8.8/lib/travis/cli/command.rb:214:in `rescue in execute'
	from /var/lib/gems/1.9.1/gems/travis-1.8.8/lib/travis/cli/command.rb:191:in `execute'
	from /var/lib/gems/1.9.1/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
	from /var/lib/gems/1.9.1/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:23:in `load'
	from /usr/local/bin/travis:23:in `<main>'
```

Why does `travis` has to create any directories to tell me its version?

**Comment by AndyHaas** [comment]
@leandro-lucarella-sociomantic did you ever get this to work?

**Comment by leandro-lucarella-sociomantic** [comment]
This was an year an a half ago, honestly I don't remember. Also I don't understand what do you mean by "get this to work". The problem is only when running it in a read-only directory, so the obvious workaround is to just run it in a directory where you have write access.

But the point is, travis should not create (or even try) to create any directories when just wanting to query the version.

**Comment by BanzaiMan** [comment]
I can't reproduce this.

```
bash-4.4$ ls -lad .
dr-xr-xr-x  2 asari  staff  64 Nov  3 16:30 .
bash-4.4$ travis --version
1.8.9
```

**Comment by leandro-lucarella-sociomantic** [comment]
Feel free to close if you can't reproduce now!
