### ISSUE TITLE
EOFError: The input stream is exhausted

### ISSUE THREAD

**Issue by cmhughes** [travis-ci/travis.rb#581]
When I run 
```
gem list addressable --local``` 
```
I get
```
*** LOCAL GEMS ***

addressable (2.3.8)
```

Then, when I run 
```sudo gem install "addressable:~> 2.4.0"
gem list addressable --local
```
I get
```

*** LOCAL GEMS ***

addressable (2.4.0, 2.3.8)
```
Then, when I run 
```
echo GH_TOKEN=<my token details here> |travis encrypt --add 
```
I get
```
Detected repository as cmhughes/ci-test, is this correct? |yes| Please enter "yes" or "no".
Detected repository as cmhughes/ci-test, is this correct? |yes| The input stream is exhausted.
for a full error report, run travis report
```
So I run 
```
travis report
```
and receive
```
System
Ruby:                     Ruby 2.3.1-p112
Operating System:         Ubuntu 16.04
RubyGems:                 RubyGems 2.5.2.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2018-02-12 18:53:06 +0000

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis encrypt`:
    EOFError: The input stream is exhausted.
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:868:in `get_line'
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:891:in `get_response'
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:264:in `ask'
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:227:in `agree'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/repo_command.rb:73:in `detect_slug'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/repo_command.rb:59:in `find_slug'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/repo_command.rb:20:in `setup'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:197:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

I'm not sure how to fix this -- do you have any ideas?

**Comment by bresicwhitney-website** [comment]
You probably have a private GitHub repository but your travis ci login only has access to the public version.
Try login
`travis login --pro`

**Comment by Hax4us** [comment]
I am also having this problem

**Comment by kipkurui** [comment]
I am having the same problem, and I do not have a private repository. I can log in successfully `travis login --pro`, though.

**Comment by claresloggett** [comment]
I had the same problem when using `travis encrypt`. It was with a public github repository, so I don't think that's the issue. I was able to apparently solve it by adding `-r username/reponame` to my `travis encrypt` call in order to stop it querying the repo. Also note I think login is only `--pro` if you're using travis.com; if you're using travis.org (as I am) it's `--org`.
