### ISSUE TITLE
Travis encrypt requests login and login fails

### ISSUE THREAD

**Issue by joerghall** [travis-ci/travis.rb#585]
I am trying to encrypt a value and it is not working. Following the documentation I can't even request the public key manually.

1) Encrypt is requesting login
```bash
travis encrypt SOMEVAR="secretvalue" --debug
** Loading gh
** GET "config"
**   took 0.18 seconds
** GitHub API: HEAD /repos/joerghall/cbt-openssl
not logged in, please run travis login --pro
```
2) Login is not working
```bash
travis login --org --github-token XXXXX
travis login --org 

no implicit conversion of nil into String
for a full error report, run travis report

travis report
System
Ruby:                     Ruby 2.0.0-p648
Operating System:         Mac OS X 10.12.6
RubyGems:                 RubyGems 2.0.14.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2018-02-27 22:43:26 -0800

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis login`:
    TypeError: no implicit conversion of nil into String
        from /Library/Ruby/Gems/2.0.0/gems/json-2.1.0/lib/json/common.rb:156:in `initialize'
        from /Library/Ruby/Gems/2.0.0/gems/json-2.1.0/lib/json/common.rb:156:in `new'
        from /Library/Ruby/Gems/2.0.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:262:in `gh_error'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:254:in `rescue in acceptable?'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:243:in `acceptable?'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:49:in `block in each_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:60:in `[]'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:60:in `possible_tokens'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:49:in `each_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:36:in `with_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/cli/login.rb:31:in `login'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/cli/login.rb:40:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

3) Requesting the public key is not working as well

https://api.travis-ci.org/repos/travis-ci/travis-ci/key

Request URL:https://api.travis-ci.org/repos/travis-ci/travis-ci/key
Request Method:GET
Status Code:404 Not Found

**Comment by andreaceccanti** [comment]
I have the same issue

**Comment by james-siteclick** [comment]
Me too:

System
Ruby:                     Ruby 2.0.0-p648
Operating System:         Mac OS X 10.12.6
RubyGems:                 RubyGems 2.0.14.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2018-03-12 12:43:21 +0000

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis login`:
    TypeError: no implicit conversion of nil into String
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `initialize'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `new'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:262:in `gh_error'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:211:in `rescue in basic_auth'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:208:in `basic_auth'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:215:in `login'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:49:in `each_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/tools/github.rb:36:in `with_token'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/cli/login.rb:31:in `login'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/cli/login.rb:40:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:23:in `load'
        from /usr/local/bin/travis:23:in `<main>'

**Comment by dursic** [comment]
@andreaceccanti I've had the same issue and exact same configuration as you (Ruby 2.0.0-p648, Mac OS X 10.11.6, RubyGems 2.0.14.1), fixed it by installing newer version of Ruby as suggested in #190 and #586. Might be the case with other posters too.

**Comment by stopsopa** [comment]
Ok, so. I found that I've been logged in already in 'travis' tool under command:

    travis report

it listed between other informations something like this:

![image](https://user-images.githubusercontent.com/3743506/38178534-fd64afbc-360c-11e8-94bf-5f50aa547a56.png)

... so then i checked if i can pass --pro argument to encrypt command and i found that actually i need to run:

    travis encrypt "my secret data" --org

and it helped... at least so far

**Comment by wtfbbqhax** [comment]
I have the same issue however, I can't perform any task with the Travis tool. Namely, `travis setup release`. 

Perhaps this is an issue with dual-factor?
