### ISSUE TITLE
`travis logs` shows plain travis_time

### ISSUE THREAD

**Issue by fenollp** [travis-ci/travis.rb#587]
I was going to report that `travis logs` show the lines that start with `travis_time:` as just plain text. Would be nice to show something more humanly readable and colorful :)

But then my build finished, I opened a new terminal window and typed the same command again and got this crash:

```
0 erlang-formatter.git PR-1728 (20.2) ∀ travis logs
displaying logs for fenollp/erlang-formatter#140.1
undefined method `each_pair' for #<String:0x00562f61094160>
Did you mean?  each_char
for a full error report, run travis report --org
1 erlang-formatter.git PR-1728 (20.2) ∀ travis report --org
System
Ruby:                     Ruby 2.3.3-p222
Operating System:         Ubuntu 17.10
RubyGems:                 RubyGems 2.5.2.1

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2018-03-05 15:45:27 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "fenollp"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `each_pair' for #<String:0x00562f61094160>
Did you mean?  each_char
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:139:in `load'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:166:in `get'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:319:in `fetch_one'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/session.rb:128:in `reload'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:208:in `load_attribute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:194:in `relation'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/entity.rb:71:in `block (2 levels) in has'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/client/artifact.rb:51:in `body'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:39:in `display_log'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /var/lib/gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'
```

**Comment by tback** [comment]
This is probably a duplicate of #578
