### ISSUE TITLE
can't login to travis 

### ISSUE THREAD

**Issue by Ahmedshabaz06** [travis-ci/travis.rb#599]
# **cannot login to travis:** 

C02VT1CYHTDD:.travis mshaikh$ travis login
We need your GitHub login to identify you.
This information will not be sent to Travis CI, only to api.github.com.
The password will not be displayed.

Try running with --github-token or --auto if you don't want to enter your password anyway.

Username: mahmed
Password for mahmed: **********************
Bad credentials
for a full error report, run travis report --pro
C02VT1CYHTDD:.travis mshaikh$ travis report --pro
System
Ruby:                     Ruby 2.3.3-p222
Operating System:         Mac OS X 10.13.4
RubyGems:                 RubyGems 2.5.2

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2018-05-15 10:48:23 -0700

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ ()
pro:                      https://api.travis-ci.com/ (default, current)

Last Exception
An error occurred running `travis login --pro`:
    RuntimeError: Bad credentials
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:211:in `rescue in basic_auth'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:208:in `basic_auth'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:215:in `login'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:49:in `each_token'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.8/lib/travis/tools/github.rb:36:in `with_token'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/login.rb:31:in `login'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/login.rb:40:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/Cellar/travis/1.8.8_3/libexec/bin/travis:22:in `load'
        from /usr/local/Cellar/travis/1.8.8_3/libexec/bin/travis:22:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
---------------------------

Besides uninstalled travis and re-installed travis, updated ruby. still the same issue.
Also tried using github token, didn't work.

**Comment by Ahmedshabaz06** [comment]
solved, one of your representatives, very quick. thanks

was using in-house travis: so I had to use - $ travis login -X
