### ISSUE TITLE
travis login:     NoMethodError: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by hans-d** [travis-ci/travis.rb#604]
```
# travis report
System
Ruby:                     Ruby 2.4.4-p296
Operating System:         Linux
RubyGems:                 RubyGems 2.7.7

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2018-06-13 11:46:04 +0000

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis login`:
    NoMethodError: undefined method `each' for nil:NilClass
        from /usr/local/bundle/gems/travis-1.8.8/lib/travis/tools/github.rb:100:in `netrc_tokens'
        from /usr/local/bundle/gems/travis-1.8.8/lib/travis/tools/github.rb:63:in `possible_tokens'
        from /usr/local/bundle/gems/travis-1.8.8/lib/travis/tools/github.rb:49:in `each_token'
        from /usr/local/bundle/gems/travis-1.8.8/lib/travis/tools/github.rb:36:in `with_token'
        from /usr/local/bundle/gems/travis-1.8.8/lib/travis/cli/login.rb:31:in `login'
        from /usr/local/bundle/gems/travis-1.8.8/lib/travis/cli/login.rb:40:in `run'
        from /usr/local/bundle/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/bundle/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /usr/local/bundle/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bundle/bin/travis:23:in `load'
        from /usr/local/bundle/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by hans-d** [comment]
caused by `.netrc` being empty (or in this case, being a folder)
