### ISSUE TITLE
Crash during `travis logs [NUMBER] --delete`

### ISSUE THREAD

**Issue by spencerwilson-optimizely** [travis-ci/travis.rb#612]
Here's the report:
```
» travis report --pro
System
Ruby:                     Ruby 2.4.1-p111
Operating System:         Mac OS X 10.13.3
RubyGems:                 RubyGems 2.6.11

CLI
Version:                  1.8.8
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2018-07-20 20:14:40 -0700

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "spencerwilson-optimizely"
Verify SSL:               yes
Enterprise:               no

Endpoints
pro:                      https://api.travis-ci.com/ (access token, current)
org:                      https://api.travis-ci.org/ ()

Last Exception
An error occurred running `travis logs --pro`:
    NoMethodError: undefined method `each_pair' for #<String:0x007f900913edb8>
Did you mean?  each_char
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/session.rb:139:in `load'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/session.rb:166:in `get'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/session.rb:319:in `fetch_one'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/session.rb:128:in `reload'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/entity.rb:208:in `load_attribute'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/artifact.rb:19:in `delete_body'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/client/job.rb:49:in `delete_log'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:33:in `delete_log'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/cli/logs.rb:23:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/lib/travis/cli.rb:64:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/travis-1.8.8/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'
```
Please let me know if there's anything else I can provide!

**Comment by arvenil** [comment]
Got the same error, I didn't use `--delete` flag.
```
✗ travis report --org
System
Ruby:                     Ruby 2.3.7-p456
Operating System:         Mac OS X 10.13.6
RubyGems:                 RubyGems 2.5.2.3

CLI
Version:                  1.8.9
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2018-09-05 18:11:33 +0200

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis logs --org`:
    NoMethodError: undefined method `each_pair' for #<String:0x00007faa0f0c0330>
Did you mean?  each_char
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/client/session.rb:139:in `load'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/client/session.rb:166:in `get'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/client/session.rb:319:in `fetch_one'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/client/session.rb:128:in `reload'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/client/entity.rb:208:in `load_attribute'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/client/entity.rb:54:in `block (2 levels) in attributes'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/client/entity.rb:194:in `relation'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/client/entity.rb:71:in `block (2 levels) in has'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/client/artifact.rb:51:in `body'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/cli/logs.rb:39:in `display_log'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/cli/logs.rb:23:in `run'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/lib/travis/cli.rb:64:in `run'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/gems/travis-1.8.9/bin/travis:18:in `<top (required)>'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/bin/travis:22:in `load'
        from /usr/local/Cellar/travis/1.8.9_1/libexec/bin/travis:22:in `<main>'
```
