### ISSUE TITLE
travis encrypt error: Errno::EACCES: Permission denied @ rb_sysopen - ~/.travis/travis.sh

### ISSUE THREAD

**Issue by alunduil** [travis-ci/travis.rb#629]
This was working before my travis client was updated (via nix-env -u) to version 1.8.9.  Now when I run encrypt, I get the following error on the console:

```
Permission denied @ rb_sysopen - /home/alunduil/.travis/travis.sh
for a full error report, run travis report
```
When I run travis report I see the exact same error, but in `~/.travis/error.log` I see:

```
An error occurred running `travis encrypt`:
    Errno::EACCES: Permission denied @ rb_sysopen - /home/alunduil/.travis/travis.sh
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1292:in `initialize'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1292:in `open'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1292:in `block in copy_file'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1291:in `open'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1291:in `copy_file'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:432:in `copy_file'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:359:in `block in cp'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1463:in `block in fu_each_src_dest'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1479:in `fu_each_src_dest0'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:1461:in `fu_each_src_dest'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/fileutils.rb:358:in `cp'
        from /nix/store/q746bff3vwd45l6ixvvkrnmgkd1vf567-ruby2.5.1-travis-1.8.9/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/tools/completion.rb:34:in `update_completion'
        from /nix/store/q746bff3vwd45l6ixvvkrnmgkd1vf567-ruby2.5.1-travis-1.8.9/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli/command.rb:175:in `block in check_completion'
        from /nix/store/q746bff3vwd45l6ixvvkrnmgkd1vf567-ruby2.5.1-travis-1.8.9/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli/command.rb:117:in `write_to'
        from /nix/store/q746bff3vwd45l6ixvvkrnmgkd1vf567-ruby2.5.1-travis-1.8.9/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli/command.rb:174:in `check_completion'
        from /nix/store/q746bff3vwd45l6ixvvkrnmgkd1vf567-ruby2.5.1-travis-1.8.9/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli/command.rb:196:in `execute'
        from /nix/store/q746bff3vwd45l6ixvvkrnmgkd1vf567-ruby2.5.1-travis-1.8.9/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli.rb:64:in `run'
        from /nix/store/3k6p3422hcjcfgsp6ibiifgw5785bpic-travis-1.8.9/lib/ruby/gems/2.5.0/gems/travis-1.8.9/bin/travis:18:in `<top (required)>'
        from /home/alunduil/.nix-profile/bin/travis:18:in `load'
        from /home/alunduil/.nix-profile/bin/travis:18:in `<main>'
```

**Comment by Legogris** [comment]
Same here, on NixOS. Full read and execute permissions on `~/.travis/travis.sh`.

**Comment by Legogris** [comment]
@alunduil Turns out you need write permissions to that file:
`chmod o+x ~/.travis/travis.sh`

**Comment by alunduil** [comment]
Ha, I knew it'd be something silly.  I'll see about checking why that file doesn't get write permissions when it's created.

**Comment by Enteee** [comment]
@Legogris, I bet you ment:
```
 chmod u+w ~/.travis/travis.sh
```

but thanks for the hint, solved it for me.
