### ISSUE TITLE
travis encrypt raises MultiJson::AdapterError

### ISSUE THREAD

**Issue by scls19fr** [travis-ci/travis.rb#636]
Hello,

I'm trying:

```
$ travis encrypt my_password --add deploy.password
```

to fix https://github.com/python-constraint/python-constraint/issues/45

but I'm getting 

```
Ignoring curb-0.8.8 because its extensions are not built.  Try: gem pristine curb --version 0.8.8
Ignoring eventmachine-1.2.1 because its extensions are not built.  Try: gem pristine eventmachine --version 1.2.1
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring ffi-1.9.14 because its extensions are not built.  Try: gem pristine ffi --version 1.9.14
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring msgpack-0.4.7 because its extensions are not built.  Try: gem pristine msgpack --version 0.4.7
Ignoring nokogiri-1.8.3 because its extensions are not built.  Try: gem pristine nokogiri --version 1.8.3
Ignoring nokogiri-1.6.8.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8.1
Ignoring nokogumbo-1.4.10 because its extensions are not built.  Try: gem pristine nokogumbo --version 1.4.10
Ignoring posix-spawn-0.3.12 because its extensions are not built.  Try: gem pristine posix-spawn --version 0.3.12
Ignoring redcarpet-3.4.0 because its extensions are not built.  Try: gem pristine redcarpet --version 3.4.0
Ignoring rugged-0.27.0 because its extensions are not built.  Try: gem pristine rugged --version 0.27.0
Ignoring thin-1.6.4 because its extensions are not built.  Try: gem pristine thin --version 1.6.4
Ignoring unf_ext-0.0.7.5 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.5
Ignoring yajl-ruby-1.2.1 because its extensions are not built.  Try: gem pristine yajl-ruby --version 1.2.1
Did not recognize your adapter specification (incompatible library version - /Users/scls/.rvm/gems/ruby-2.3.0/gems/json-2.1.0/lib/json/ext/parser.bundle).
for a full error report, run travis report
```

I installed it using `brew install travis`

Here is Travis report output:

```
$ travis report
Ignoring curb-0.8.8 because its extensions are not built.  Try: gem pristine curb --version 0.8.8
Ignoring eventmachine-1.2.1 because its extensions are not built.  Try: gem pristine eventmachine --version 1.2.1
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring ffi-1.9.14 because its extensions are not built.  Try: gem pristine ffi --version 1.9.14
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring json-1.8.6 because its extensions are not built.  Try: gem pristine json --version 1.8.6
Ignoring msgpack-0.4.7 because its extensions are not built.  Try: gem pristine msgpack --version 0.4.7
Ignoring nokogiri-1.8.3 because its extensions are not built.  Try: gem pristine nokogiri --version 1.8.3
Ignoring nokogiri-1.6.8.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8.1
Ignoring nokogumbo-1.4.10 because its extensions are not built.  Try: gem pristine nokogumbo --version 1.4.10
Ignoring posix-spawn-0.3.12 because its extensions are not built.  Try: gem pristine posix-spawn --version 0.3.12
Ignoring redcarpet-3.4.0 because its extensions are not built.  Try: gem pristine redcarpet --version 3.4.0
Ignoring rugged-0.27.0 because its extensions are not built.  Try: gem pristine rugged --version 0.27.0
Ignoring thin-1.6.4 because its extensions are not built.  Try: gem pristine thin --version 1.6.4
Ignoring unf_ext-0.0.7.5 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.5
Ignoring yajl-ruby-1.2.1 because its extensions are not built.  Try: gem pristine yajl-ruby --version 1.2.1
System
Ruby:                     Ruby 2.3.7-p456
Operating System:         Mac OS X 10.13.6
RubyGems:                 RubyGems 2.5.2.3

CLI
Version:                  1.8.9
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2018-11-05 09:33:55 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis encrypt`:
    MultiJson::AdapterError: Did not recognize your adapter specification (incompatible library version - /Users/scls/.rvm/gems/ruby-2.3.0/gems/json-2.1.0/lib/json/ext/parser.bundle).
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/scls/.rvm/gems/ruby-2.3.0/gems/json-2.1.0/lib/json/ext.rb:7:in `<module:Ext>'
        from /Users/scls/.rvm/gems/ruby-2.3.0/gems/json-2.1.0/lib/json/ext.rb:6:in `<module:JSON>'
        from /Users/scls/.rvm/gems/ruby-2.3.0/gems/json-2.1.0/lib/json/ext.rb:3:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/multi_json-1.13.1/lib/multi_json/adapters/json_gem.rb:1:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:157:in `load_adapter_from_string_name'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:101:in `load_adapter'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:103:in `load_adapter'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:91:in `use'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:73:in `adapter'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:133:in `current_adapter'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:139:in `dump'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/response.rb:34:in `initialize'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/remote.rb:152:in `new'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/remote.rb:152:in `modify'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/remote.rb:72:in `generate_response'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/normalizer.rb:8:in `generate_response'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/parallel.rb:27:in `generate_response'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/remote.rb:87:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `request'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/gh-0.15.1/lib/gh/remote.rb:105:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `head'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/travis-1.8.9/lib/travis/cli/repo_command.rb:120:in `detect_api_endpoint'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/travis-1.8.9/lib/travis/cli/repo_command.rb:22:in `setup'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/travis-1.8.9/lib/travis/cli/command.rb:197:in `execute'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/travis-1.8.9/lib/travis/cli.rb:64:in `run'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/gems/travis-1.8.9/bin/travis:18:in `<top (required)>'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/bin/travis:22:in `load'
        from /usr/local/Cellar/travis/1.8.9_2/libexec/bin/travis:22:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

Any idea?

Kind regards

**Comment by BanzaiMan** [comment]
The `travis` installation seems broken, but I can't tell what is causing it.

**Comment by Dina-Nashaat** [comment]
In case someone else encounters this, for me, the error occurred for `ruby-2.6.3` - when I installed and used the latest release `ruby-2.7.0` and re-ran the command, it was successful.
