### ISSUE TITLE
travis console is not working

### ISSUE THREAD

**Issue by conao3** [travis-ci/travis.rb#654]
Hi.
`travis console` is not working for me. I got below error.
Any ideas?

```
~/D/g/playground    pry -v   
Pry version 0.12.2 on Ruby 2.5.3


 ~/D/g/playground    pry
[1] pry(main)>
C-d

 ~/D/g/playground    travis report 
System
Ruby:                     Ruby 2.5.3-p105
Operating System:         Mac OS X 10.13.6
RubyGems:                 RubyGems 2.7.6

CLI
Version:                  1.8.9
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2019-01-30 14:38:40 +0900

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "conao3"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis console`:
    NameError: uninitialized constant Pry::SIMPLE_PROMPT
Did you mean?  Pry::SIMPLE_PRINT
        from /Users/conao/.anyenv/envs/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli/console.rb:17:in `run'
        from /Users/conao/.anyenv/envs/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli/command.rb:198:in `execute'
        from /Users/conao/.anyenv/envs/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/travis-1.8.9/lib/travis/cli.rb:64:in `run'
        from /Users/conao/.anyenv/envs/rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/travis-1.8.9/bin/travis:18:in `<top (required)>'
        from /Users/conao/.anyenv/envs/rbenv/versions/2.5.3/bin/travis:23:in `load'
        from /Users/conao/.anyenv/envs/rbenv/versions/2.5.3/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by conao3** [comment]
#227 may be relevant.

**Comment by johnjohndoe** [comment]
Same here. I just installed the `travis` gem via `gem install travis -v 1.8.9 --no-rdoc --no-ri` and the `pry` gem (pry-0.12.2) via `gem install pry` when `travis console` prompted me to do so.

``` bash
$ travis report 

System
Ruby:                     Ruby 2.2.4-p230
Operating System:         Ubuntu 18.04
RubyGems:                 RubyGems 2.4.8

CLI
Version:                  1.8.9
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2019-02-17 13:15:36 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "***"
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, current)

Last Exception
An error occurred running `travis console`:
    NameError: uninitialized constant Pry::SIMPLE_PROMPT
        from /home/***/.rvm/gems/ruby-2.2.4/gems/travis-1.8.9/lib/travis/cli/console.rb:17:in `run'
        from /home/***/.rvm/gems/ruby-2.2.4/gems/travis-1.8.9/lib/travis/cli/command.rb:198:in `execute'
        from /home/***/.rvm/gems/ruby-2.2.4/gems/travis-1.8.9/lib/travis/cli.rb:64:in `run'
        from /home/***/.rvm/gems/ruby-2.2.4/gems/travis-1.8.9/bin/travis:18:in `<top (required)>'
        from /home/***/.rvm/gems/ruby-2.2.4/bin/travis:23:in `load'
        from /home/***/.rvm/gems/ruby-2.2.4/bin/travis:23:in `<main>'
        from /home/***/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
        from /home/***/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by aphofstede** [comment]
This got travis console working for me:
```
gem uninstall pry
gem install pry -v 0.9.12.6
```

**Comment by tchiaspko** [comment]
Any reason we can't include the pry version 0.9.12.6 as a runtime dependency in the gemspec file?

**Comment by tchia04** [comment]
Any reason we don't include the pry version 0.9.12.6 as a runtime dependency in the gemspec file?

**Comment by Nic30** [comment]
I had to manually reinstall the pry on ubuntu 19.04 as well. At least update the help string at:
https://github.com/travis-ci/travis.rb/blob/11d6f6fad51065861d7437fc3d3c9f14bf801f9e/lib/travis/cli/console.rb#L26
to contain install command for some working version.

**Comment by winterz** [comment]
thank you for the tip.  On Fedora 29 I had to do explicitly install pry 0.9.12.6 as well

**Comment by nverno** [comment]
Patching with 

        binding.pry(:quiet => true, :prompt => Pry::Prompt[:simple][:value],
                    :output => $stdout, :hooks => hooks)

seems to work fine for me
