### ISSUE TITLE
Travis Login Fails When Using a GitHub Token from a Rate-Limited IP Address

### ISSUE THREAD

**Issue by copperlight** [travis-ci/travis.rb#674]
Steps to Reproduce:

1. `travis login --github-token $PERSONAL_ACCESS_TOKEN`
2. Response: `not logged in - try running travis login`
3. `travis report`

```
System
Ruby:                     Ruby 2.3.7-p456
Operating System:         Mac OS X 10.14.5
RubyGems:                 RubyGems 2.5.2.3

CLI
Version:                  1.8.10
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2019-06-26 16:59:41 -0700

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis login`:
    RuntimeError: API rate limit exceeded for A.B.C.D. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.10/lib/travis/tools/github.rb:211:in `rescue in basic_auth'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.10/lib/travis/tools/github.rb:207:in `basic_auth'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.10/lib/travis/tools/github.rb:215:in `login'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.10/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.10/lib/travis/tools/github.rb:49:in `each_token'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.10/lib/travis/tools/github.rb:36:in `with_token'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.10/lib/travis/cli/login.rb:31:in `login'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.10/lib/travis/cli/login.rb:40:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.10/lib/travis/cli/command.rb:198:in `execute'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.10/lib/travis/cli.rb:64:in `run'
        from /Library/Ruby/Gems/2.3.0/gems/travis-1.8.10/bin/travis:18:in `<top (required)>'
        from /usr/local/bin/travis:22:in `load'
        from /usr/local/bin/travis:22:in `<main>'
```

Work-around:

Use `travis login` and provide GitHub credentials.

Problem:

This defeats the purpose of being able to use a GitHub personal access token for initial login, so that you can avoid providing your GitHub password.

The personal access token provided should be used with the GitHub API calls, so that they are not rate limited during this initialization step.

**Comment by devstuff** [comment]
Same issue using `travis login --pro --auto`.

**Comment by lulubobst** [comment]
same issue getting API rate limit exceeded for user ID XXXXXXX
