### ISSUE TITLE
travis report error  

### ISSUE THREAD

**Issue by snowtreetree** [travis-ci/travis.rb#724]
when I run travis report , I got message:
```
An error occurred running `travis login`:
    MultiJson::AdapterError: Did not recognize your adapter specification (incompatible library version - /Users/zhangxuelin/.rvm/gems/ruby-2.7.0-preview1/gems/json-2.3.0/lib/json/ext/parser.bundle).
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /Users/zhangxuelin/.rvm/gems/ruby-2.7.0-preview1/gems/json-2.3.0/lib/json/ext.rb:7:in `<module:Ext>'
        from /Users/zhangxuelin/.rvm/gems/ruby-2.7.0-preview1/gems/json-2.3.0/lib/json/ext.rb:6:in `<module:JSON>'
        from /Users/zhangxuelin/.rvm/gems/ruby-2.7.0-preview1/gems/json-2.3.0/lib/json/ext.rb:3:in `<top (required)>'
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/multi_json-1.13.1/lib/multi_json/adapters/json_gem.rb:1:in `<top (required)>'
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:157:in `load_adapter_from_string_name'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:101:in `load_adapter'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:103:in `load_adapter'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:91:in `use'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:73:in `adapter'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:133:in `current_adapter'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/multi_json-1.13.1/lib/multi_json.rb:139:in `dump'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/gh-0.15.1/lib/gh/response.rb:34:in `initialize'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/gh-0.15.1/lib/gh/remote.rb:89:in `new'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/gh-0.15.1/lib/gh/remote.rb:89:in `rescue in request'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/gh-0.15.1/lib/gh/remote.rb:83:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/gh-0.15.1/lib/gh/remote.rb:95:in `post'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/lib/travis/tools/github.rb:224:in `create_token'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/lib/travis/tools/github.rb:216:in `block in login'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/lib/travis/tools/github.rb:235:in `with_otp'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/lib/travis/tools/github.rb:209:in `basic_auth'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/lib/travis/tools/github.rb:215:in `login'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/lib/travis/tools/github.rb:80:in `possible_tokens'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/lib/travis/tools/github.rb:49:in `each_token'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/lib/travis/tools/github.rb:36:in `with_token'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/lib/travis/cli/login.rb:31:in `login'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/lib/travis/cli/login.rb:40:in `run'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/lib/travis/cli/command.rb:198:in `execute'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/lib/travis/cli.rb:64:in `run'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/gems/travis-1.8.11/bin/travis:18:in `<top (required)>'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/bin/travis:23:in `load'
        from /usr/local/Cellar/travis/1.8.11_1/libexec/bin/travis:23:in `<main>'
```

**Comment by BanzaiMan** [comment]
You seem to have an environment where RVM (`/Users/xxx/.rvm/gems/ruby-2.7.0-preview1/`) and the system Ruby (`/System/Library/Frameworks/Ruby.framework/Versions/2.6`) are intertwined. How did you install your Ruby? Is it 2.7 (as RVM claims), or 2.6 (as the system default)?
