### ISSUE TITLE
Not working on Arch Linux

### ISSUE THREAD

**Issue by tanayseven** [travis-ci/travis.rb#743]
I ran the following different installations, each after uninstalling the previous installation
`gem install travis --no-document`
`gem install travis`
`gem install travis --pre`
`yay -S ruby-travis`
After each and every installation, the cli fails with the same error:
```
$ travis                               
Traceback (most recent call last):
	6: from /home/tanayseven/.gem/ruby/2.7.0/bin/travis:23:in `<main>'
	5: from /usr/lib/ruby/site_ruby/2.7.0/rubygems.rb:297:in `activate_bin_path'
	4: from /usr/lib/ruby/site_ruby/2.7.0/rubygems.rb:297:in `synchronize'
	3: from /usr/lib/ruby/site_ruby/2.7.0/rubygems.rb:299:in `block in activate_bin_path'
	2: from /usr/lib/ruby/site_ruby/2.7.0/rubygems.rb:232:in `finish_resolve'
	1: from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `require'
/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
```

**Comment by BanzaiMan** [comment]
I cannot reproduce this problem.

```
$ docker run --rm -it archlinux /bin/bash
[root@e432707da81f /]# pacman -Sy gcc make ruby
:: Synchronizing package databases...
 core                                                                                                                                                                                          131.4 KiB   912 KiB/s 00:00 [##########################################################################################################################################] 100%
 extra                                                                                                                                                                                        1638.6 KiB  2.87 MiB/s 00:01 [##########################################################################################################################################] 100%
 community                                                                                                                                                                                       4.9 MiB  4.62 MiB/s 00:01 [##########################################################################################################################################] 100%
resolving dependencies...
looking for conflicting packages...
warning: dependency cycle detected:
warning: rubygems will be installed before its ruby dependency
warning: dependency cycle detected:
warning: ruby-irb will be installed before its ruby dependency
warning: dependency cycle detected:
warning: ruby-reline will be installed before its ruby dependency

Packages (15) binutils-2.34-2  elfutils-0.178-2  gc-8.0.4-3  guile-2.2.6-2  libmicrohttpd-0.9.70-3  libmpc-1.1.0-2  libtool-2.4.6+42+gb88cebd5-12  libyaml-0.2.4-1  ruby-irb-1.2.1-1  ruby-reline-0.0.7-2  rubygems-3.1.2-4  texinfo-6.7-3  gcc-9.3.0-1  make-4.3-3  ruby-2.7.1-2

Total Download Size:    48.37 MiB
Total Installed Size:  244.61 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 libmicrohttpd-0.9.70-3-x86_64                                                                                                                                                                 202.8 KiB  1102 KiB/s 00:00 [##########################################################################################################################################] 100%
 elfutils-0.178-2-x86_64                                                                                                                                                                       599.7 KiB  1904 KiB/s 00:00 [##########################################################################################################################################] 100%
 binutils-2.34-2-x86_64                                                                                                                                                                          5.2 MiB  4.69 MiB/s 00:01 [##########################################################################################################################################] 100%
 libmpc-1.1.0-2-x86_64                                                                                                                                                                          65.1 KiB   739 KiB/s 00:00 [##########################################################################################################################################] 100%
 gcc-9.3.0-1-x86_64                                                                                                                                                                             29.8 MiB  12.6 MiB/s 00:02 [##########################################################################################################################################] 100%
 libtool-2.4.6+42+gb88cebd5-12-x86_64                                                                                                                                                          407.4 KiB  1358 KiB/s 00:00 [##########################################################################################################################################] 100%
 texinfo-6.7-3-x86_64                                                                                                                                                                         1397.6 KiB  1165 KiB/s 00:01 [##########################################################################################################################################] 100%
 make-4.3-3-x86_64                                                                                                                                                                             481.6 KiB  1180 KiB/s 00:00 [##########################################################################################################################################] 100%
 gc-8.0.4-3-x86_64                                                                                                                                                                             221.1 KiB   925 KiB/s 00:00 [##########################################################################################################################################] 100%
 guile-2.2.6-2-x86_64                                                                                                                                                                            6.4 MiB  3.00 MiB/s 00:02 [##########################################################################################################################################] 100%
 libyaml-0.2.4-1-x86_64                                                                                                                                                                         59.2 KiB   650 KiB/s 00:00 [##########################################################################################################################################] 100%
 rubygems-3.1.2-4-any                                                                                                                                                                          216.2 KiB   965 KiB/s 00:00 [##########################################################################################################################################] 100%
 ruby-2.7.1-2-x86_64                                                                                                                                                                             3.3 MiB  2.74 MiB/s 00:01 [##########################################################################################################################################] 100%
 ruby-reline-0.0.7-2-any                                                                                                                                                                        30.5 KiB   677 KiB/s 00:00 [##########################################################################################################################################] 100%
 ruby-irb-1.2.1-1-any                                                                                                                                                                           53.7 KiB   584 KiB/s 00:00 [##########################################################################################################################################] 100%
(15/15) checking keys in keyring                                                                                                                                                                                           [##########################################################################################################################################] 100%
(15/15) checking package integrity                                                                                                                                                                                         [##########################################################################################################################################] 100%
(15/15) loading package files                                                                                                                                                                                              [##########################################################################################################################################] 100%
(15/15) checking for file conflicts                                                                                                                                                                                        [##########################################################################################################################################] 100%
:: Processing package changes...
( 1/15) installing libmicrohttpd                                                                                                                                                                                           [##########################################################################################################################################] 100%
( 2/15) installing elfutils                                                                                                                                                                                                [##########################################################################################################################################] 100%
( 3/15) installing binutils                                                                                                                                                                                                [##########################################################################################################################################] 100%
( 4/15) installing libmpc                                                                                                                                                                                                  [##########################################################################################################################################] 100%
( 5/15) installing gcc                                                                                                                                                                                                     [##########################################################################################################################################] 100%
Optional dependencies for gcc
    lib32-gcc-libs: for generating code for 32-bit ABI
( 6/15) installing libtool                                                                                                                                                                                                 [##########################################################################################################################################] 100%
( 7/15) installing texinfo                                                                                                                                                                                                 [##########################################################################################################################################] 100%
( 8/15) installing gc                                                                                                                                                                                                      [##########################################################################################################################################] 100%
( 9/15) installing guile                                                                                                                                                                                                   [##########################################################################################################################################] 100%
(10/15) installing make                                                                                                                                                                                                    [##########################################################################################################################################] 100%
(11/15) installing libyaml                                                                                                                                                                                                 [##########################################################################################################################################] 100%
(12/15) installing rubygems                                                                                                                                                                                                [##########################################################################################################################################] 100%
(13/15) installing ruby-reline                                                                                                                                                                                             [##########################################################################################################################################] 100%
(14/15) installing ruby-irb                                                                                                                                                                                                [##########################################################################################################################################] 100%
(15/15) installing ruby                                                                                                                                                                                                    [##########################################################################################################################################] 100%
Optional dependencies for ruby
    ruby-docs: Ruby documentation
    tk: for Ruby/TK
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[root@e432707da81f /]# gem install travis
Fetching concurrent-ruby-1.1.6.gem
Fetching multipart-post-2.1.1.gem
Fetching faraday-1.0.1.gem
Fetching faraday_middleware-1.0.0.gem
Fetching highline-2.0.3.gem
Fetching thread_safe-0.3.6.gem
Fetching tzinfo-1.2.7.gem
Fetching public_suffix-4.0.4.gem
Fetching i18n-1.8.2.gem
Fetching minitest-5.14.0.gem
Fetching activesupport-5.2.4.2.gem
Fetching multi_json-1.14.1.gem
Fetching net-http-persistent-2.9.4.gem
Fetching net-http-pipeline-1.0.1.gem
Fetching addressable-2.7.0.gem
Fetching gh-0.17.0.gem
Fetching launchy-2.5.0.gem
Fetching ffi-1.12.2.gem
Fetching ethon-0.12.0.gem
Fetching typhoeus-0.8.0.gem
Fetching travis-1.9.0.gem
Fetching websocket-1.2.8.gem
Fetching pusher-client-0.6.2.gem
WARNING:  You don't have /root/.gem/ruby/2.7.0/bin in your PATH,
          gem executables will not run.
Successfully installed multipart-post-2.1.1
Successfully installed faraday-1.0.1
Successfully installed faraday_middleware-1.0.0
Successfully installed highline-2.0.3
Successfully installed concurrent-ruby-1.1.6

HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.

If you are upgrading your Rails application from an older version of Rails:

Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.

If you are starting a NEW Rails application, you can ignore this notice.

For more info see:
https://github.com/svenfuchs/i18n/releases/tag/v1.1.0

Successfully installed i18n-1.8.2
Successfully installed thread_safe-0.3.6
Successfully installed tzinfo-1.2.7
Successfully installed minitest-5.14.0
Successfully installed activesupport-5.2.4.2
Successfully installed multi_json-1.14.1
Successfully installed public_suffix-4.0.4
Successfully installed addressable-2.7.0
Successfully installed net-http-persistent-2.9.4
Successfully installed net-http-pipeline-1.0.1
Successfully installed gh-0.17.0
Successfully installed launchy-2.5.0
Building native extensions. This could take a while...
Successfully installed ffi-1.12.2
Successfully installed ethon-0.12.0
Successfully installed typhoeus-0.8.0
Successfully installed websocket-1.2.8
Successfully installed pusher-client-0.6.2
Successfully installed travis-1.9.0
23 gems installed
[root@e432707da81f /]# export PATH=$PATH:/root/.gem/ruby/2.7.0/bin
[root@e432707da81f /]# travis
Usage: travis COMMAND ...

Available commands:

        accounts       displays accounts and their subscription status
        branches       displays the most recent build for each branch
        cache          lists or deletes repository caches
        cancel         cancels a job or build
        console        interactive shell; requires `pry`
        disable        disables a project
        enable         enables a project
        encrypt        encrypts values for the .travis.yml
        encrypt-file   encrypts a file and adds decryption steps to .travis.yml
        endpoint       displays or changes the API endpoint
        env            show or modify build environment variables
        help           helps you out when in dire need of information
        history        displays a project's build history
        init           generates a .travis.yml and enables the project
        lint           display warnings for a .travis.yml
        login          authenticates against the API and stores the token
        logout         deletes the stored API token
        logs           streams test logs
        monitor        live monitor for what's going on
        open           opens a build or job in the browser
        pubkey         prints out a repository's public key
        raw            makes an (authenticated) API call and prints out the result
        report         generates a report useful for filing issues
        repos          lists repositories the user has certain permissions on
        requests       lists recent requests
        restart        restarts a build or job
        settings       access repository settings
        setup          sets up an addon or deploy target
        show           displays a build or job
        sshkey         checks, updates or deletes an SSH key
        status         checks status of the latest build
        sync           triggers a new sync with GitHub
        token          outputs the secret API token
        version        outputs the client version
        whatsup        lists most recent builds
        whoami         outputs the current user

run `/root/.gem/ruby/2.7.0/bin/travis help COMMAND` for more info
```

**Comment by tanayseven** [comment]
Can I give any more info here?
Is it possible for someone to try it on an actual Arch instance that is being run instead of a Docker container?

**Comment by tanayseven** [comment]
Can anyone help regarding this?

**Comment by tanayseven** [comment]
No action is taken, should I close this issue?

**Comment by BanzaiMan** [comment]
Sorry, but I don't think I can help you. I can't reproduce the problem, and the error message indicates to me that your Ruby setup has a problem outside of travis.rb.

A simple search such as https://duckduckgo.com/?q=%60ensure+in+require%27%3A+CRITICAL%3A+RUBYGEMS_ACTIVATION_MONITOR.owned%3F%3A+before+false+-%3E+after+true+(RuntimeError)&ia=web may help you get more help.

**Comment by tanayseven** [comment]
I'll close this issue as of now. I'm using the built executable from `bin/travis` with works fine. I will re-open and resolve this issue if I happen to find a solution for the above.
