### ISSUE TITLE
Error running travis version on Windows

### ISSUE THREAD

**Issue by HipDragon** [travis-ci/travis.rb#760]
Installed RubyInstaller(Ruby+Devkit 2.6.6-1 (x64) ) then installed travis with gem install travis. There where no errors during installation. When I attempt to verify the install I get the following error below. I'm not sure why it's trying to use the H drive, I have no H drive on the windows machine. The home directory is set to the standard C:\Users\username

PS C:\WINDOWS\system32> travis version
Traceback (most recent call last):
        8: from C:/Ruby26-x64/bin/travis:23:in `<main>'
        7: from C:/Ruby26-x64/bin/travis:23:in `load'
        6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/bin/travis:18:in `<top (required)>'
        5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli.rb:64:in `run'
        4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli/command.rb:196:in `execute'
        3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli/command.rb:378:in `load_config'
        2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli/command.rb:356:in `load_file'
        1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli/command.rb:351:in `config_path'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli/command.rb:351:in `mkdir': No such file or directory @ dir_s_mkdir - H:/.travis (Errno::ENOENT)
        9: from C:/Ruby26-x64/bin/travis:23:in `<main>'
        8: from C:/Ruby26-x64/bin/travis:23:in `load'
        7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/bin/travis:18:in `<top (required)>'
        6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli.rb:64:in `run'
        5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli/command.rb:192:in `execute'
        4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli/command.rb:219:in `rescue in execute'
        3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli/command.rb:287:in `store_error'
        2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli/command.rb:368:in `save_file'
        1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli/command.rb:351:in `config_path'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.9.1/lib/travis/cli/command.rb:351:in `mkdir': No such file or directory @ dir_s_mkdir - H:/.travis (Errno::ENOENT)

OS: Windows 10 64Bit
Ruby: ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]

**Comment by HipDragon** [comment]
Ruby command Dir.home() gives the wrong folder. Not sure where that is obtained in a windows setup to change it, also not sure what the correct windows setting should be.
