### ISSUE TITLE
Expired certificate

### ISSUE THREAD

**Issue by bdunne** [travis-ci/travis.rb#791]
https://github.com/travis-ci/travis.rb/blob/1766fc76495d43f7035278c8f4e5a569606bd4f6/assets/cacert.pem#L1-L23 expired May 30 10:48:38 2020 GMT

**Comment by arieltango** [comment]
I got this error today when I was deploying through travis to Heroku:

Preparing deploy
No stash entries found.
/home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired) (Faraday::SSLError)
	from /home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
	from /home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:996:in `connect'
	from /home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /home/travis/.rvm/gems/ruby-2.6.6/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:138:in `request_via_get_method'

**Comment by adriyanstanchev** [comment]
> I got this error today when I was deploying through travis to Heroku:
> 
> Preparing deploy No stash entries found. /home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired) (Faraday::SSLError) from /home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect' from /home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:996:in `connect' from /home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:930:in `do_start' from /home/travis/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/net/http.rb:919:in `start' from /home/travis/.rvm/gems/ruby-2.6.6/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:138:in `request_via_get_method'

Did you manage to fix this somehow?
