### ISSUE TITLE
Faraday::ConnectionFailed: SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by bdunne** [travis-ci/travis.rb#792]
Possibly related to #791 

```
System
Ruby:                     Ruby 2.5.7-p206
Operating System:         Linux
RubyGems:                 RubyGems 3.0.6

CLI
Version:                  1.10.0
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2020-12-23 17:13:15 -0500

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "bdunne"
Verify SSL:               no
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, insecure)
com:                      https://api.travis-ci.com/ (access token, insecure, default, current)

Last Exception
An error occurred running `travis encrypt`:
    Faraday::ConnectionFailed: SSL peer certificate or SSH remote key was not OK
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb:106:in `block in request'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/callbacks.rb:146:in `block in execute_callbacks'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/callbacks.rb:145:in `each'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/callbacks.rb:145:in `execute_callbacks'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:35:in `finish'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/easy_factory.rb:164:in `block in set_callback'
        from /home/bdunne/.gem/ruby/2.5.7/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
        from /home/bdunne/.gem/ruby/2.5.7/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `each'
        from /home/bdunne/.gem/ruby/2.5.7/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `complete'
        from /home/bdunne/.gem/ruby/2.5.7/gems/ethon-0.12.0/lib/ethon/easy/operations.rb:33:in `perform'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:16:in `run'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/cacheable.rb:18:in `run'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/block_connection.rb:31:in `run'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/stubbable.rb:25:in `run'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/before.rb:26:in `run'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb:82:in `perform_request'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb:72:in `call'
        from /home/bdunne/.gem/ruby/2.5.7/gems/faraday-1.2.0/lib/faraday/request/retry.rb:148:in `call'
        from /home/bdunne/.gem/ruby/2.5.7/gems/faraday-1.2.0/lib/faraday/request/url_encoded.rb:25:in `call'
        from /home/bdunne/.gem/ruby/2.5.7/gems/faraday-1.2.0/lib/faraday/rack_builder.rb:154:in `build_response'
        from /home/bdunne/.gem/ruby/2.5.7/gems/faraday-1.2.0/lib/faraday/connection.rb:492:in `run_request'
        from /home/bdunne/.gem/ruby/2.5.7/gems/faraday-1.2.0/lib/faraday/connection.rb:198:in `get'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:210:in `public_send'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:210:in `block in raw'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:283:in `block in instrumented'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:284:in `block in instrumented'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:285:in `instrumented'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:208:in `raw'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:187:in `get_raw'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:135:in `config'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/cli/api_command.rb:132:in `load_gh'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/cli/repo_command.rb:122:in `detect_api_endpoint'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/cli/repo_command.rb:25:in `setup'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/cli/command.rb:199:in `execute'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/cli.rb:64:in `run'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/bin/travis:18:in `<top (required)>'
        from /home/bdunne/.gem/ruby/2.5.7/bin/travis:23:in `load'
        from /home/bdunne/.gem/ruby/2.5.7/bin/travis:23:in `<main>'
```

**Comment by BanzaiMan** [comment]
What is the command you ran?

**Comment by bdunne** [comment]
Hi @BanzaiMan sorry for the delay, I was off for a few days.  I'm trying to encrypt a file containing some secrets.

```
$ travis encrypt-file -r bdunne/external_rpm config/settings.local.yml
SSL peer certificate or SSH remote key was not OK
for a full error report, run travis report
```
```
$ travis report
System
Ruby:                     Ruby 2.5.7-p206
Operating System:         Linux
RubyGems:                 RubyGems 3.0.6

CLI
Version:                  1.10.0
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2021-01-05 15:55:27 -0500

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "bdunne"
Verify SSL:               no
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (access token, insecure)
com:                      https://api.travis-ci.com/ (access token, insecure, default, current)

Last Exception
An error occurred running `travis encrypt-file`:
    Faraday::ConnectionFailed: SSL peer certificate or SSH remote key was not OK
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb:106:in `block in request'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/callbacks.rb:146:in `block in execute_callbacks'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/callbacks.rb:145:in `each'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/callbacks.rb:145:in `execute_callbacks'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:35:in `finish'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/easy_factory.rb:164:in `block in set_callback'
        from /home/bdunne/.gem/ruby/2.5.7/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
        from /home/bdunne/.gem/ruby/2.5.7/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `each'
        from /home/bdunne/.gem/ruby/2.5.7/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `complete'
        from /home/bdunne/.gem/ruby/2.5.7/gems/ethon-0.12.0/lib/ethon/easy/operations.rb:33:in `perform'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:16:in `run'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/cacheable.rb:18:in `run'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/block_connection.rb:31:in `run'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/stubbable.rb:25:in `run'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/request/before.rb:26:in `run'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb:82:in `perform_request'
        from /home/bdunne/.gem/ruby/2.5.7/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb:72:in `call'
        from /home/bdunne/.gem/ruby/2.5.7/gems/faraday-1.2.0/lib/faraday/request/retry.rb:148:in `call'
        from /home/bdunne/.gem/ruby/2.5.7/gems/faraday-1.2.0/lib/faraday/request/url_encoded.rb:25:in `call'
        from /home/bdunne/.gem/ruby/2.5.7/gems/faraday-1.2.0/lib/faraday/rack_builder.rb:154:in `build_response'
        from /home/bdunne/.gem/ruby/2.5.7/gems/faraday-1.2.0/lib/faraday/connection.rb:492:in `run_request'
        from /home/bdunne/.gem/ruby/2.5.7/gems/faraday-1.2.0/lib/faraday/connection.rb:198:in `get'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:210:in `public_send'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:210:in `block in raw'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:283:in `block in instrumented'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:284:in `block in instrumented'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:285:in `instrumented'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:208:in `raw'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:187:in `get_raw'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/client/session.rb:135:in `config'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/cli/api_command.rb:132:in `load_gh'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/cli/repo_command.rb:122:in `detect_api_endpoint'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/cli/repo_command.rb:25:in `setup'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/cli/encrypt_file.rb:52:in `setup'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/cli/command.rb:199:in `execute'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/lib/travis/cli.rb:64:in `run'
        from /home/bdunne/.gem/ruby/2.5.7/gems/travis-1.10.0/bin/travis:18:in `<top (required)>'
        from /home/bdunne/.gem/ruby/2.5.7/bin/travis:23:in `load'
        from /home/bdunne/.gem/ruby/2.5.7/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by bdunne** [comment]
Ok, so after discussing with a colleague, `$ travis encrypt-file --pro -r bdunne/external_rpm config/settings.local.yml` worked.  I didn't know that I had to include the `--pro` in the command since `com` is both the `default` and `current` endpoint.

This feels like a bug to me.  Do you agree?

**Comment by yuceltoluyag** [comment]
travis encrypt 'GIT_NAME="yuceltoluyag" GIT_EMAIL="ytoluyag@gmail.com" GITHUB_TOKEN=xxxx'  

SSL peer certificate or SSH remote key was not OK
for a full error report, run travis report

```
travis report
System
Ruby:                     Ruby 3.0.1-p64
Operating System:         Arch rolling
RubyGems:                 RubyGems 3.2.15

CLI
Version:                  1.10.0
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2021-05-04 22:25:16 +0300

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis encrypt`:
    Faraday::ConnectionFailed: SSL peer certificate or SSH remote key was not OK
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb:106:in `block in request'
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/callbacks.rb:146:in `block in execute_callbacks'
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/callbacks.rb:145:in `each'
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/callbacks.rb:145:in `execute_callbacks'
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:35:in `finish'
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/easy_factory.rb:164:in `block in set_callback'
        from /home/friday13/.gem/gems/ethon-0.13.0/lib/ethon/easy/response_callbacks.rb:69:in `block in complete'
        from /home/friday13/.gem/gems/ethon-0.13.0/lib/ethon/easy/response_callbacks.rb:69:in `each'
        from /home/friday13/.gem/gems/ethon-0.13.0/lib/ethon/easy/response_callbacks.rb:69:in `complete'
        from /home/friday13/.gem/gems/ethon-0.13.0/lib/ethon/easy/operations.rb:48:in `perform'
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/operations.rb:16:in `run'
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/cacheable.rb:18:in `run'
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/block_connection.rb:31:in `run'
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/stubbable.rb:25:in `run'
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/request/before.rb:26:in `run'
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb:82:in `perform_request'
        from /home/friday13/.gem/gems/typhoeus-1.4.0/lib/typhoeus/adapters/faraday.rb:72:in `call'
        from /home/friday13/.gem/gems/faraday-1.3.0/lib/faraday/request/retry.rb:148:in `call'
        from /home/friday13/.gem/gems/faraday-1.3.0/lib/faraday/request/url_encoded.rb:25:in `call'
        from /home/friday13/.gem/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
        from /home/friday13/.gem/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
        from /home/friday13/.gem/gems/faraday-1.3.0/lib/faraday/connection.rb:198:in `get'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/client/session.rb:210:in `public_send'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/client/session.rb:210:in `block in raw'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/client/session.rb:283:in `block in instrumented'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/client/session.rb:284:in `block in instrumented'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/client/session.rb:285:in `instrumented'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/client/session.rb:208:in `raw'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/client/session.rb:187:in `get_raw'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/client/session.rb:135:in `config'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/cli/api_command.rb:132:in `load_gh'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/cli/repo_command.rb:122:in `detect_api_endpoint'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/cli/repo_command.rb:25:in `setup'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/cli/command.rb:199:in `execute'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/lib/travis/cli.rb:64:in `run'
        from /home/friday13/.gem/ruby/3.0.0/gems/travis-1.10.0/bin/travis:18:in `<top (required)>'
        from /home/friday13/.gem/ruby/3.0.0/bin/travis:23:in `load'
        from /home/friday13/.gem/ruby/3.0.0/bin/travis:23:in `<main>'


For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```
