### ISSUE TITLE
ArgumentError: tried to create Proc object without a block

### ISSUE THREAD

**Issue by khatchad** [travis-ci/travis.rb#829]
```
$ travis report
System
Ruby:                     Ruby 3.0.4-p208
Operating System:         Ubuntu 22.10
RubyGems:                 RubyGems 3.3.15

CLI
Version:                  1.11.1
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2023-01-05 08:47:55 -0500

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
com:                      https://api.travis-ci.com/ (access token)
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis history`:
    ArgumentError: tried to create Proc object without a block
        from /home/rk1424/gems/gems/multi_json-1.13.1/lib/multi_json/options_cache.rb:12:in `new'
        from /home/rk1424/gems/gems/multi_json-1.13.1/lib/multi_json/options_cache.rb:12:in `fetch'
        from /home/rk1424/gems/gems/multi_json-1.13.1/lib/multi_json/adapter.rb:37:in `cached_dump_options'
        from /home/rk1424/gems/gems/multi_json-1.13.1/lib/multi_json/adapter.rb:25:in `dump'
        from /home/rk1424/gems/gems/multi_json-1.13.1/lib/multi_json.rb:139:in `dump'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/response.rb:34:in `initialize'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/remote.rb:156:in `new'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/remote.rb:156:in `modify'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/remote.rb:75:in `generate_response'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/normalizer.rb:8:in `generate_response'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/parallel.rb:27:in `generate_response'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/wrapper.rb:87:in `generate_response'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/remote.rb:91:in `request'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `request'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `request'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `request'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `request'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `request'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `request'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `request'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `request'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `request'
        from /home/rk1424/gems/gems/gh-0.18.0/lib/gh/remote.rb:109:in `head'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `head'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `head'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `head'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `head'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `head'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `head'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `head'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `head'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `head'
        from /usr/lib/ruby/3.0.0/forwardable.rb:238:in `head'
        from /home/rk1424/gems/gems/travis-1.11.1/lib/travis/cli/repo_command.rb:124:in `detect_api_endpoint'
        from /home/rk1424/gems/gems/travis-1.11.1/lib/travis/cli/repo_command.rb:26:in `setup'
        from /home/rk1424/gems/gems/travis-1.11.1/lib/travis/cli/command.rb:199:in `execute'
        from /home/rk1424/gems/gems/travis-1.11.1/lib/travis/cli.rb:64:in `run'
        from /home/rk1424/gems/gems/travis-1.11.1/bin/travis:18:in `<top (required)>'
        from /home/rk1424/gems/bin/travis:25:in `load'
        from /home/rk1424/gems/bin/travis:25:in `<main>'
```

**Comment by khatchad** [comment]
Oh, maybe I'm not logged in.

**Comment by khatchad** [comment]
Actually, I still get this error when I try to login.

**Comment by szpak** [comment]
Today I've got the same error with 1.11.1:

```
$ travis login --com --github-token XXXX
tried to create Proc object without a block
for a full error report, run travis report --pro
```

Fedora 38, ruby 3.2.2. The report is similar to the aforementioned.

**Comment by szpak** [comment]
@BanzaiMan Is Ruby 3 supported by Travis?
