### ISSUE TITLE
Problem with uploading secret files 

### ISSUE THREAD

**Issue by mll** [travis-ci/travis.rb#838]
We suddenly have a problem uploading a secret file for travis (which used to work for a few years):

travis encrypt-file secrets.tgz --add --com

produces:

System
Ruby:                     Ruby 3.2.2-p53
Operating System:         macOS 13.3.1
RubyGems:                 RubyGems 3.4.10

CLI
Version:                  1.11.1
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2023-07-27 10:07:06 +0200

Session
API Endpoint:             https://api.travis-ci.com/
Logged In:                as "mll"
Verify SSL:               yes
Enterprise:               no

Endpoints
com:                      https://api.travis-ci.com/ (access token, current)
org:                      https://api.travis-ci.org/ ()

Last Exception
An error occurred running `travis encrypt-file --pro`:
    Psych::AliasesNotEnabled: Alias parsing was not enabled. To enable it, pass `aliases: true` to `Psych::load` or `Psych::safe_load`.
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:432:in `visit_Psych_Nodes_Alias'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:347:in `block in revive_hash'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each_slice'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `revive_hash'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:169:in `visit_Psych_Nodes_Mapping'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:340:in `block in register_empty'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:340:in `each'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:340:in `register_empty'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:148:in `visit_Psych_Nodes_Sequence'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:347:in `block in revive_hash'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each_slice'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `revive_hash'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:169:in `visit_Psych_Nodes_Mapping'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:340:in `block in register_empty'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:340:in `each'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:340:in `register_empty'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:148:in `visit_Psych_Nodes_Sequence'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:347:in `block in revive_hash'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each_slice'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `revive_hash'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:169:in `visit_Psych_Nodes_Mapping'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:347:in `block in revive_hash'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `each_slice'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:345:in `revive_hash'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:169:in `visit_Psych_Nodes_Mapping'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:320:in `visit_Psych_Nodes_Document'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych.rb:334:in `safe_load'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych.rb:369:in `load'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych.rb:671:in `block in load_file'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych.rb:670:in `open'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/psych.rb:670:in `load_file'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/travis-1.11.1/lib/travis/cli/repo_command.rb:134:in `travis_config'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/travis-1.11.1/lib/travis/cli/encrypt_file.rb:65:in `store_command'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/travis-1.11.1/lib/travis/cli/encrypt_file.rb:45:in `run'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/travis-1.11.1/lib/travis/cli/command.rb:200:in `execute'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/travis-1.11.1/lib/travis/cli.rb:64:in `run'
        from /opt/homebrew/lib/ruby/gems/3.2.0/gems/travis-1.11.1/bin/travis:18:in `<top (required)>'
        from /opt/homebrew/Cellar/travis/1.11.1_2/libexec/bin/travis:25:in `load'
        from /opt/homebrew/Cellar/travis/1.11.1_2/libexec/bin/travis:25:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email [support@travis-ci.com](mailto:support@travis-ci.com)

What can I do about it?

**Comment by juanesarango** [comment]
Im having the same issue? Any idea on how to fix?
