### ISSUE TITLE
travis 1.12.0 build failure

### ISSUE THREAD

**Issue by chenrui333** [travis-ci/travis.rb#851]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
==> /home/linuxbrew/.linuxbrew/Cellar/travis/1.12.0/bin/travis whoami 2>&1 --pro
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/ignorable.rb:29:in `block in raise'
Minitest::Assertion: --- expected
+++ actual
@@ -1 +1,21 @@
-"not logged in, please run travis login --pro"
+"<internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require': cannot load such file -- rack/test (LoadError)
+\tfrom <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
+\tfrom /home/linuxbrew/.linuxbrew/Cellar/travis/1.12.0/libexec/gems/faraday-rack-2.0.0/lib/faraday/adapter/rack.rb:3:in `<top (required)>'
+\tfrom <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
+\tfrom <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
+\tfrom /home/linuxbrew/.linuxbrew/Cellar/travis/1.12.0/libexec/gems/faraday-rack-2.0.0/lib/faraday/rack.rb:4:in `<top (required)>'
+\tfrom <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
+\tfrom <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
+\tfrom /home/linuxbrew/.linuxbrew/Cellar/travis/1.12.0/libexec/gems/travis-1.12.0/lib/travis/client/session.rb:9:in `<top (required)>'
+\tfrom <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
+\tfrom <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
+\tfrom /home/linuxbrew/.linuxbrew/Cellar/travis/1.12.0/libexec/gems/travis-1.12.0/lib/travis/client.rb:9:in `<top (required)>'
+\tfrom <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
+\tfrom <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
+\tfrom /home/linuxbrew/.linuxbrew/Cellar/travis/1.12.0/libexec/gems/travis-1.12.0/lib/travis/cli.rb:4:in `<top (required)>'
+\tfrom <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
+\tfrom <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
+\tfrom /home/linuxbrew/.linuxbrew/Cellar/travis/1.12.0/libexec/gems/travis-1.12.0/bin/travis:9:in `<top (required)>'
+\tfrom /home/linuxbrew/.linuxbrew/Cellar/travis/1.12.0/libexec/bin/travis:25:in `load'
+\tfrom /home/linuxbrew/.linuxbrew/Cellar/travis/1.12.0/libexec/bin/travis:25:in `<main>'
```

</details>

relates to Homebrew/homebrew-core#164871

**Comment by chenrui333** [comment]
1.14.0 works for the brew build, https://github.com/Homebrew/homebrew-core/pull/173434

close the issue for now
