### ISSUE TITLE
command.rb:334:in `format': wrong number of arguments (given 5, expected 1..3

### ISSUE THREAD

**Issue by NathanBoxall** [travis-ci/travis.rb#863]
There is an issue whenever I run "travis login --pro". Getting the error:
/home/bear/.gem/ruby/3.3.0/gems/travis-1.14.0/lib/travis/cli/command.rb:334:in `format': wrong number of arguments (given 5, expected 1..3) (ArgumentError)

and

/home/bear/.gem/ruby/3.3.0/gems/faraday-typhoeus-1.1.0/lib/faraday/adapter/typhoeus.rb:91:in `block in request': SSL peer certificate or SSH remote key was not OK (Faraday::ConnectionFailed)

OS - Fedora 40
travis - 1.14.0
Ruby - 3.3.0
Gem - 3.5.1

Is this a known issue?

**Comment by fluxink** [comment]
I have same issue.
Try installing version 1.11.1 . 
`gem install travis -v 1.11.1`
It worked for me.
